### ISSUE TITLE
Add "WandaVision" from WandaVision

### ISSUE THREAD

**Issue by clairemation** [lynnandtonic/nestflix.fun#101]
Please add as much of the following info as you can:

Title: WandaVision

Type (film/tv show): 50s, 60s, 70s, 80s, 90s, 2000s, and 2010s-era sitcom (TV show)

Film or show in which it appears: WandaVision

Is the parent film/show streaming anywhere? Disney+

About when in the parent film/show does it appear? Starts in episode 1 at 00:00:00 and comprises the majority of the runtime of the show. First revealed to be an in-universe show actually playing on a TV in episode 4 at about 00:15:32 (or, arguably, at the beginning of the ending credits in episode 1).

Actual footage of the film/show can be seen (yes/no)? Yes.

May not qualify since the show (in-universe) is not traditionally produced and distributed; but created, produced, and broadcast using magic (though enacted with "real" people) and seen only by a few characters.

**Comment by avipars** [comment]
+1

**Comment by lynnandtonic** [comment]
Going to think about this one. Maybe right on the line 😄

**Comment by lynnandtonic** [comment]
Ended up adding it. Thank you! https://nestflix.fun/wandavision/
