### ISSUE TITLE
TV Show in the movie Time Bandits

### ISSUE THREAD

**Issue by Boomshakaboom** [lynnandtonic/nestflix.fun#102]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by lynnandtonic** [comment]
@Boomshakaboom Could you give me a bit more details? Do you know the name of the show or when it appears in the film?

**Comment by Boomshakaboom** [comment]
Hi Lynn!
There’s a faux TV game show (hosted by Jim Broadbent) called “Your Money or
Your Life” featured at the beginning of Terry Gilliam’s 1981 film Time
Bandits.
I love Nestflix! I’ve always been fascinated by the movies within movies.
A while back, I worked with musicians in SF who created a mock record label
called Clubbo.com
I played a country singer called Breaker Bear who sang the 1995 classic
“Log On”. The website is still running and you can hear my song if you’re
interested. Thanks again for Nestflix…

**Comment by lynnandtonic** [comment]
Ah perfect, thank you!

Also that is AMAZING!! Going to go look for this!

**Comment by Boomshakaboom** [comment]
Cool, thanks!

**Comment by lynnandtonic** [comment]
It’s up! https://nestflix.fun/your-money-or-your-life/

Thank you!
