### ISSUE TITLE
"Camp Bloodbath" from "The Final Girls"

### ISSUE THREAD

**Issue by nicwolff** [lynnandtonic/nestflix.fun#107]
Please add as much of the following info as you can:

Title: Camp Bloodbath

Type (film/tv show): film

Film or show in which it appears: The Final Girls

Is the parent film/show streaming anywhere? Hulu for subscribers, or rent from Amazon Prime Video or YouTube

About when in the parent film/show does it appear? At the beginning, and throughout

Actual footage of the film/show can be seen (yes/no)? Yes

**Comment by lynnandtonic** [comment]
Thank you! https://nestflix.fun/camp-bloodbath/
