### ISSUE TITLE
Spaceballs 2: The Search for More Money

### ISSUE THREAD

**Issue by arungapatchka** [lynnandtonic/nestflix.fun#110]
Spaceballs 2: The Search for More Money is a supposed sequel to [Spaceballs](https://spaceballs.fandom.com/wiki/Spaceballs_2:_The_Search_for_More_Money), mentioned by Yogurt.

**Comment by ururk** [comment]
I noticed this was missing too, but the submission criteria states:

- Must show actual footage (not just mentioned in dialogue or seen in a poster)

I could be wrong, but this was the only place in the movie I could find it mentioned:

https://www.youtube.com/watch?v=aN8wxQDqfRk

**Comment by HarleysTwin** [comment]
You're right, @ururk.  They never show footage of the actual film.  And since submissions also aren't including meta movies yet, even the original Spaceballs doesn't fit the criteria.

**Comment by lynnandtonic** [comment]
Thanks, y’all but yeah this doesn’t fit current criteria. Closing for now!
