### ISSUE TITLE
Add The Passion of Saint Tibulus (Father Ted)

### ISSUE THREAD

**Issue by chriselion** [lynnandtonic/nestflix.fun#113]
Please add as much of the following info as you can:

Title: The Passion of Saint Tibulus

Type (film/tv show): film

Film or show in which it appears: Father Ted

Is the parent film/show streaming anywhere? Amazon Prime

About when in the parent film/show does it appear? Series 1, Episode 3

Actual footage of the film/show can be seen (yes/no)? no, sign outside the theater at approx 15:00, movie posters at approx 19:45

More info: https://fatherted.fandom.com/wiki/The_Passion_of_Saint_Tibulus (note that the picture is the title card for the real show, not the fake film)

**Comment by lynnandtonic** [comment]
I’m only adding titles that show footage for now, so going to close this one. Thank you!
