### ISSUE TITLE
Vital Social Issues N' Stuff 

### ISSUE THREAD

**Issue by jonathan-dueck** [lynnandtonic/nestflix.fun#116]
Please add as much of the following info as you can:

Title:Vital Social Issues N' Stuff

Type (film/tv show):Public access TV Show

Film or show in which it appears:Married with Children

Is the parent film/show streaming anywhere?Hulu

About when in the parent film/show does it appear?S6 Ep 9 10m:08s

sActual footage of the film/show can be seen (yes/no)?Yes
![vital social issues n stuff](https://user-images.githubusercontent.com/11180833/129305679-2e1230bb-b740-43f2-9dde-3282f5a14b17.png)

**Comment by lynnandtonic** [comment]
Thank you @jonathan-dueck! https://nestflix.fun/vital-social-issues-n-stuff/
