### ISSUE TITLE
Add Black Hammer, White Lightning

### ISSUE THREAD

**Issue by ApolloVI** [lynnandtonic/nestflix.fun#118]
Please add as much of the following info as you can:

Title: Black Hammer, White Lightning

Type (film/tv show): film

Film or show in which it appears: Major League II

Is the parent film/show streaming anywhere? Starz, DirectTV, Spectrum on Demand

About when in the parent film/show does it appear? 12:52

Actual footage of the film/show can be seen (yes/no)? Yes
https://www.youtube.com/watch?v=NoZzyL1KEis

![image0004](https://user-images.githubusercontent.com/88874071/129313277-2274d1eb-df0a-42e4-9410-878731f09424.jpg)

**Comment by lynnandtonic** [comment]
Thank you, @ApolloVI! https://nestflix.fun/black-hammer-white-lightning/
