### ISSUE TITLE
Add Red is Dead

### ISSUE THREAD

**Issue by Ash-Crow** [lynnandtonic/nestflix.fun#120]
Please add as much of the following info as you can:

Title: Red Is Dead

Type (film/tv show): film

Film or show in which it appears: La Cité de la Peur

Is the parent film/show streaming anywhere? Netflix

About when in the parent film/show does it appear? 2:13

Actual footage of the film/show can be seen (yes/no)? yes
[https://www.youtube.com/watch?v=S6zAJG2PpOg](https://www.youtube.com/watch?v=S6zAJG2PpOg)

Quote: "Meurs, pourriture communiste !"

(Note: it is famous enough to have [a Wikipedia article](https://fr.wikipedia.org/wiki/Red_Is_Dead) separated from the one of the actual movie)

![Capture d’écran de 2021-08-13 08-49-26](https://user-images.githubusercontent.com/765956/129318222-e0ab3d57-381c-4227-98aa-84a910f72830.png)

**Comment by Nathagamelle** [comment]
Starring: 
Simon Jeremi as Benjamin
Sandy Brookshield as Sandy
Bob J. MacLef as Maximilien
Ryon O'Nouille as Ludovic
Don Voyelle as Susan
Clint Consonne as Jean-Paul
Pascal Pascal as Bernard
Robert Miro as Robert
Albert Mozzarella as un serveur
Roberta Sunshine as une serveuse
Luke as gardien de la paix 1
Serge Durens as un présentateur
Roy Gicle as l'ouvreur
Frank Robert as un videur
Bob Geli as rien

**Comment by lynnandtonic** [comment]
It’s up! https://nestflix.fun/red-is-dead/

Thank you!
