### ISSUE TITLE
Add Johnny Karate 

### ISSUE THREAD

**Issue by Mommommommooom** [lynnandtonic/nestflix.fun#123]
Please add as much of the following info as you can:

Title: Johnny Karate

Type (film/tv show): variety show for kids 

Film or show in which it appears: parks and rec 

Is the parent film/show streaming anywhere? Probably but not in Canada 

About when in the parent film/show does it appear? Last season 

Actual footage of the film/show can be seen (yes/no)? Yes and I would watch an entire season of it

**Comment by Cqoicebordel** [comment]
Episode 7x10 of Parks and Rec https://www.imdb.com/title/tt3784782/?ref_=ttep_ep10

**Comment by oscarbartos** [comment]
Title: The Johnny Karate Super Awesome Musical Explosion Show
Type: TV show
Is the parent film/show streaming anywhere? Peacock
About when in the parent film/show does it appear? 7x10 (entire episode)

**Comment by lynnandtonic** [comment]
It’s up! https://nestflix.fun/johnny-karate-super-awesome-musical-explosion-show/

Thank you!!
