### ISSUE TITLE
Add a film by kirk

### ISSUE THREAD

**Issue by MargaritaB21** [lynnandtonic/nestflix.fun#125]
Please add as much of the following info as you can:

Title: a film by kirk

Type (film/tv show): film

Film or show in which it appears: Gilmore Girls

Is the parent film/show streaming anywhere? Netflix

About when in the parent film/show does it appear? Season 2, Episode 19

Actual footage of the film/show can be seen (yes/no)? yes

**Comment by lynnandtonic** [comment]
Thank you, @MargaritaB21! https://nestflix.fun/a-film-by-kirk/
