### ISSUE TITLE
Add a second film by kirk

### ISSUE THREAD

**Issue by MargaritaB21** [lynnandtonic/nestflix.fun#126]
Please add as much of the following info as you can:

Title: a second film by kirk

Type (film/tv show): film

Film or show in which it appears: Gilmore Girls: A Year In The Life

Is the parent film/show streaming anywhere? Netflix

About when in the parent film/show does it appear? Episode "Fall"

Actual footage of the film/show can be seen (yes/no)? Yes

**Comment by lynnandtonic** [comment]
Thank you, @MargaritaB21! https://nestflix.fun/a-second-film-by-kirk/
