### ISSUE TITLE
Add Da Derp Dee Derp Da Teetley Derpee Derpee Dumb

### ISSUE THREAD

**Issue by dalyUSN** [lynnandtonic/nestflix.fun#128]
Please add as much of the following info as you can:

Title: Da Derp Dee Derp Da Teetley Derpee Derpee Dumb

Type (film/tv show): Film

Film or show in which it appears: South Park (https://www.imdb.com/title/tt0705968/ Season 06 Episode 15)

Is the parent film/show streaming anywhere? Amazon Prime in the UK. 

About when in the parent film/show does it appear? 15 minute

Actual footage of the film/show can be seen (yes/no)? https://www.youtube.com/watch?v=ZxYA6duF-9E

**Comment by lynnandtonic** [comment]
Thanks @dalyUSN! https://nestflix.fun/da-derp-dee-derp-da-teetley-derpee-derpee-dumb/
