### ISSUE TITLE
Add A Carrot

### ISSUE THREAD

**Issue by dalyUSN** [lynnandtonic/nestflix.fun#129]
Please add as much of the following info as you can:

Title: A Carrot

Type (film/tv show): Film

Film or show in which it appears: South Park (https://www.imdb.com/title/tt0705968/ Season 06 Episode 15)

Is the parent film/show streaming anywhere? Amazon Prime in the UK.

About when in the parent film/show does it appear? 09 minutes 12 seconds

Actual footage of the film/show can be seen (yes/no)? Yes. https://www.youtube.com/watch?v=6uK2WMc9L8c

**Comment by lynnandtonic** [comment]
Thanks! https://nestflix.fun/a-carrot/
