### ISSUE TITLE
Add The Stapler

### ISSUE THREAD

**Issue by dalyUSN** [lynnandtonic/nestflix.fun#130]
Please add as much of the following info as you can:

Title: The Stapler

Type (film/tv show): Film

Film or show in which it appears: South Park (https://www.imdb.com/title/tt0705968/ Season 06 Episode 15)

Is the parent film/show streaming anywhere? Amazon Prime in the UK

About when in the parent film/show does it appear? 03 minutes 16 seconds

Actual footage of the film/show can be seen (yes/no)? Yes. https://www.youtube.com/watch?v=iS9H9WPPDS8

**Comment by lynnandtonic** [comment]
Thank you! https://nestflix.fun/the-stapler/
