### ISSUE TITLE
Add 'Knife After Dark'

### ISSUE THREAD

**Issue by Sanderth** [lynnandtonic/nestflix.fun#131]
Please add as much of the following info as you can:

Title: Knife After Dark

Type (film/tv show): Film

Film or show in which it appears: Neither, mentioned in GTA Vice City

Is the parent film/show streaming anywhere? N.A.

About when in the parent film/show does it appear? Radio ad, Flash FM

Actual footage of the film/show can be seen (yes/no)? No

https://gta.fandom.com/wiki/Knife_After_Dark

**Comment by lynnandtonic** [comment]
I don’t plan on adding any titles from video games right now, sorry! Thank you @Sanderth!
