### ISSUE TITLE
Midnight Coterie Of Sinister Intruders from SNL

### ISSUE THREAD

**Issue by Spencerwriter** [lynnandtonic/nestflix.fun#133]
Please add as much of the following info as you can:

Title: Midnight Coterie Of Sinister intruders 

Type (film/tv show): horror comedy feature

Film or show in which it appears: SNL

Is the parent film/show streaming anywhere?

NBC/Clip is on YouTube
About when in the parent film/show does it appear? Sketch 

Actual footage of the film/show can be seen (yes/no)? Yes

**Comment by lynnandtonic** [comment]
Thank you for the suggestion, @Spencerwriter! Right now I don’t have plans on adding shows from comedy sketch shows like SNL. Maybe someday though! Closing this for now.
