### ISSUE TITLE
Add [Orgazmo]

### ISSUE THREAD

**Issue by Mojojo7224** [lynnandtonic/nestflix.fun#135]
Please add as much of the following info as you can:

Title: Orgazmo

Type (film/tv show): Comedy XXX

Film or show in which it appears: Captain Orgazmo by Trey Parker

Is the parent film/show streaming anywhere? Youtube

About when in the parent film/show does it appear?

Actual footage of the film/show can be seen (yes/no)? No

**Comment by lynnandtonic** [comment]
Thank you! https://nestflix.fun/orgazmo/
