### ISSUE TITLE
Add [Ass Movie]

### ISSUE THREAD

**Issue by Mojojo7224** [lynnandtonic/nestflix.fun#137]
Please add as much of the following info as you can:

Title: Ass Movie

Type (film/tv show): Dramatic movie

Film or show in which it appears: Idiocracy

Is the parent film/show streaming anywhere? 

About when in the parent film/show does it appear? Idiocracy

Actual footage of the film/show can be seen (yes/no)? Yes

**Comment by HarleysTwin** [comment]
@Mojojo7224, "Ass" is not a drama.  It's a comedy.  They show people laughing in the theater.

Is the parent film/show streaming anywhere? Yes - Amazon Prime

About when in the parent film/show does it appear? probably after the first 1/4

Actual footage of the film/show can be seen (yes/no)? Yes - Here is a clip with the footage. https://www.youtube.com/watch?v=iE5aKNAcU2I

Awards: 8 Oscars including Best Screenplay

**Comment by lynnandtonic** [comment]
I may not add this one because I’m not sure I want a picture of a butt on the site. 😆 Going to think it over.

**Comment by lynnandtonic** [comment]
Thank you! https://nestflix.fun/ass/
