### ISSUE TITLE
Add Rochelle Rochelle

### ISSUE THREAD

**Issue by akamarvin** [lynnandtonic/nestflix.fun#139]
Title: Rochelle Rochelle

Type (film/tv show): film

Film or show in which it appears: Seinfeld

Is the parent film/show streaming anywhere?  Netflix, Amazon prime

About when in the parent film/show does it appear? 2 episodes of Season 4, one of season 6

Actual footage of the film/show can be seen (yes/no)? No, just poster, and audio bits when they watch it in a theater. 

This is kinda cult, a running gag on multiple episodes. Even got Bette Midler involved in a potential musical version of Rochelle Rochelle. 

Subtitled "A young girl's strange erotic journey from Milan to Minsk" 
https://seinfeld.fandom.com/wiki/Rochelle,_Rochelle

To me, it as as worthy as the Rural Juror, even with no footage.

**Comment by lynnandtonic** [comment]
Sorry, not including any films without footage for now (as iconic as Rochelle, Rochelle is). 

Thank you!
