### ISSUE TITLE
The Night The Reindeer Died

### ISSUE THREAD

**Issue by travstone** [lynnandtonic/nestflix.fun#140]
Please add as much of the following info as you can:

Title: The Night The Reindeer Died

Type (film/tv show): Film

Film or show in which it appears: Scrooged

Is the parent film/show streaming anywhere? unknown

About when in the parent film/show does it appear? Beginning

Actual footage of the film/show can be seen (yes/no)? Yes: https://www.youtube.com/watch?v=gkOYenddJ8g

**Comment by lynnandtonic** [comment]
That one is on the site! https://nestflix.fun/the-night-the-reindeer-died/

**Comment by travstone** [comment]
Lol, I'm sorry! I didn't look close enough : ) Great job on the site BTW, super fun.

**Comment by lynnandtonic** [comment]
No problem! Thank you!!
