### ISSUE TITLE
Add: American Hero Story: Minutemen

### ISSUE THREAD

**Issue by oscarbartos** [lynnandtonic/nestflix.fun#142]
Please add as much of the following info as you can:

Title: American Hero Story: Minutemen

Type (film/tv show): TV Show

Film or show in which it appears: Watchmen (2019)

Is the parent film/show streaming anywhere? HBO/HBO Max

About when in the parent film/show does it appear? Episode 2, 34:00, Episode 6, 01:20

Actual footage of the film/show can be seen (yes/no)? Yes

**Comment by oscarbartos** [comment]
Logo typeface: https://fonts.adobe.com/fonts/industry

**Comment by lynnandtonic** [comment]
Thank you! https://nestflix.fun/american-hero-story/
