### ISSUE TITLE
Add Hell Hazers

### ISSUE THREAD

**Issue by ChokolatteJedi** [lynnandtonic/nestflix.fun#143]
Please add as much of the following info as you can:

Title: Hell Hazers II (And I)

Type (film/tv show): Film

Film or show in which it appears: Supernatural

Is the parent film/show streaming anywhere? Yes, Netflix

About when in the parent film/show does it appear? 2x18  Hollywood Babylon (https://supernatural.fandom.com/wiki/Hollywood_Babylon) (http://www.supernaturalwiki.com/Hell_Hazers)

Actual footage of the film/show can be seen (yes/no)? Yes.

There are several crew names available in the episode, which are easy to get from the wiki, and I'm pretty sure there's footage from Hell Hazers I in the episode too. Also, the other "movies" that Martin has written for have footage (from other SPN episodes, not sure if that counts for you or not) The second wiki link has info about finding other tidbits for the Hell Hazers series and other internal movies and in which episodes.

**Comment by lynnandtonic** [comment]
Thank you! https://nestflix.fun/hell-hazers-ii-the-reckoning/
