### ISSUE TITLE
Why Me? The Bob Lamonta Story from Mr. Show

### ISSUE THREAD

**Issue by selfsimilar** [lynnandtonic/nestflix.fun#145]
Please add as much of the following info as you can:

Title: Why Me? The Bob Lamonta Story

Type (film/tv show): Film

Film or show in which it appears: Mr. Show (Season 3, Episode 2 - "Peanut Butter, Eggs, and Dice")

Is the parent film/show streaming anywhere? Yes. HBO Max, Amazon Prime, more...

About when in the parent film/show does it appear? 21:30

Actual footage of the film/show can be seen (yes/no)? yes (https://youtu.be/_AXFlPR9inY?t=239)

**Comment by lynnandtonic** [comment]
I’m not going to be adding any titles from Mr. Show for now (sketch show). Might come back to it later!

Thank you!
