### ISSUE TITLE
Add The Dueling Cavalier

### ISSUE THREAD

**Issue by ChokolatteJedi** [lynnandtonic/nestflix.fun#146]
Please add as much of the following info as you can:

Title: The Dueling Cavalier

Type (film/tv show): Film

Film or show in which it appears: Singing In The Rain

Is the parent film/show streaming anywhere? Amazon Prime, Youtube and others, but it costs money. Plenty of clips are on youtube, though.

About when in the parent film/show does it appear? Throughout. The parent film is about making the internal film

Actual footage of the film/show can be seen (yes/no)? Yes

**Comment by lynnandtonic** [comment]
It’s on the site! https://nestflix.fun/the-duelling-cavalier/
