### ISSUE TITLE
Add I Can Do Better & Balance of Power

### ISSUE THREAD

**Issue by ChokolatteJedi** [lynnandtonic/nestflix.fun#147]
Please add as much of the following info as you can:

Title:  I Can Do Better

Type (film/tv show): TV Show

Film or show in which it appears: The Stepford Wives (2004)

Is the parent film/show streaming anywhere? Not for free, but the relevant clip is on youtube here: https://www.youtube.com/watch?v=C-Ad2a7UD0A&ab_channel=Movieclips

About when in the parent film/show does it appear? In the first section

Actual footage of the film/show can be seen (yes/no)? Yes

Also another TV show from that movie, Balance of Power, is in this clip: https://www.youtube.com/watch?v=Tz8V7WRYD0Q&ab_channel=BobI

**Comment by lynnandtonic** [comment]
They’re live now!

https://nestflix.fun/i-can-do-better/
https://nestflix.fun/balance-of-power/

Thank you! 🎉
