### ISSUE TITLE
Add "Fast Animals, Slow Children"

### ISSUE THREAD

**Issue by M0nSt3rManu** [lynnandtonic/nestflix.fun#148]
Please add as much of the following info as you can:

Title: Fast Animals, Slow Children

Type (film/tv show): TV Show

Film or show in which it appears: Family Guy ( Season 1, Episode 2 - "I Never Met the Dead Man")

Is the parent film/show streaming anywhere? Yes. Netflix and Disney+

About when in the parent film/show does it appear? 04:31

Actual footage of the film/show can be seen (yes/no)? Yes. https://www.youtube.com/watch?v=abFllTlLqVI

**Comment by lynnandtonic** [comment]
It's live! https://nestflix.fun/fast-animals-slow-children/

Thank you!
