### ISSUE TITLE
Add Li'l Butler

### ISSUE THREAD

**Issue by mckeed** [lynnandtonic/nestflix.fun#149]
Title: Li'l Butler

Type (film/tv show): TV Sitcom

Film or show in which it appears: Steven Universe

Is the parent film/show streaming anywhere? Hulu

About when in the parent film/show does it appear? Season 1, Episode 43

Actual footage of the film/show can be seen (yes/no)? Yes

https://youtu.be/7ykCjdgzcnU

**Comment by lynnandtonic** [comment]
It’s up! https://nestflix.fun/lil-butler/

Thank you, @mckeed!
