### ISSUE TITLE
Add [The littlest elf]

### ISSUE THREAD

**Issue by Mojojo7224** [lynnandtonic/nestflix.fun#155]
Please add as much of the following info as you can:

Title: The Littlest elf

Type (film/tv show): Animation

Film or show in which it appears: Lemony Snicket's A Series of Unfortunate Events

Is the parent film/show streaming anywhere? 

About when in the parent film/show does it appear? at the beginning of the film

Actual footage of the film/show can be seen (yes/no)? yes

**Comment by lynnandtonic** [comment]
Thank you, @Mojojo7224! It’s on the site now: https://nestflix.fun/the-littlest-elf/
