### ISSUE TITLE
Days of Our Lives

### ISSUE THREAD

**Issue by KIAMR** [lynnandtonic/nestflix.fun#157]
Add Days of our Lives with Dr. Drake Ramoray a.k.a. Joey from friends

**Comment by lynnandtonic** [comment]
Hi @KIAMR! Unfortunately (for our current scenario), Days of Our Lives is a real show so I won’t be adding it to Nestflix. https://en.wikipedia.org/wiki/Days_of_Our_Lives

Thanks for taking the time to submit! ❤️
