### ISSUE TITLE
Add Serve & Protect

### ISSUE THREAD

**Issue by TomDWI** [lynnandtonic/nestflix.fun#159]
**Title**
Serve & Protect

**Type**
Tv show

**Show in which it appears**
Brooklyn Nine-Nine

**Is the parent film/show streaming anywhere?**
In my country it's on Netflix, I know it's on Peacock in the United States.

**About when in the parent film/show does it appear?**
S04E14 "Serve & Protect"

**Actual footage of the film/show can be seen?**
Yes

**Comment by lynnandtonic** [comment]
It‘s live! Thank you! https://nestflix.fun/serve-and-protect/
