### ISSUE TITLE
Add Evil Bratt

### ISSUE THREAD

**Issue by Darkakali02** [lynnandtonic/nestflix.fun#160]
Please add as much of the following info as you can:

Title: Evil Bratt

Type (film/tv show): TV show

Film or show in which it appears: Despicable Me 3

Is the parent film/show streaming anywhere? No

About when in the parent film/show does it appear? Don’t know exact time stamp 

Actual footage of the film/show can be seen (yes/no)? Y https://youtu.be/OLxBkVGQjZ8

**Comment by lynnandtonic** [comment]
It’s up! https://nestflix.fun/evil-bratt/

Thanks, @Darkakali02!
