### ISSUE TITLE
Add Crocodile Tears (from Along Came Polly)

### ISSUE THREAD

**Issue by broox9** [lynnandtonic/nestflix.fun#162]
Please add as much of the following info as you can:

Title: Crocodile Tears

Type (film/tv show):coming of age teen Comedy / Drama (kind of like Breakfast Club)

Film or show in which it appears: Along came Polly

Is the parent film/show streaming anywhere?
Starz/Prime

About when in the parent film/show does it appear?

Mainly toward the beginning, mentioned briefly throughout and also toward the end at the scene where Phillip Seymour Hoffman is in a play. 

Actual footage of the film/show can be seen (yes/no)?

No. A poster is shown towards the beginning of the movie

Phillip Seymour Hoffman plays in Along came Polly as Sanford "Sandy" Lyle, a former child star, known for a movie called "Crocodile Tears"

**Comment by lynnandtonic** [comment]
I’m only adding titles that show footage for now, so going to close this. Thank you!
