### ISSUE TITLE
Add "The Making of the Making of Titanic", from Mad About You

### ISSUE THREAD

**Issue by rrcook** [lynnandtonic/nestflix.fun#164]
Please add as much of the following info as you can:

Title: 
The Making of the Making of Titanic

Type (film/tv show): 
Documentary

Film or show in which it appears:
Mad About You (original), Season 6, Episode 23

Is the parent film/show streaming anywhere?
Amazon Prime

About when in the parent film/show does it appear?
3:40, 12:48, also https://www.youtube.com/watch?v=fR3byPCz7X8

Actual footage of the film/show can be seen (yes/no)?
Yes

**Comment by lynnandtonic** [comment]
Thank you! https://nestflix.fun/the-making-of-the-making-of-titanic/
