### ISSUE TITLE
Mr. Banagrabber from Arrested Development

### ISSUE THREAD

**Issue by shawntaylor** [lynnandtonic/nestflix.fun#167]
Please add as much of the following info as you can:

Title: Mr. Bananagrabber

Type (film/tv show): TV show

Film or show in which it appears: Arrested Development

Is the parent film/show streaming anywhere? Netflix (at least in Canada)

About when in the parent film/show does it appear? Season 1, very briefly on a few episodes

Actual footage of the film/show can be seen (yes/no)? Y (like a second)

Quote: Why would a banana grab another banana?

**Comment by lynnandtonic** [comment]
Do you know if Mr. Bananagrabber is actually a tv show? I know GOB sells the animation rights, but it's not super clear if it's just a mascot from a commercial.

**Comment by lynnandtonic** [comment]
Ok I have decided not to add this one at least for now. It isn't super clear if it's a TV show or commercial or what and it's only one short clip (https://www.youtube.com/watch?v=fmVWFS9j5YU). Thank you so much for the suggestion!
