### ISSUE TITLE
Irma Vep from Irma Vep

### ISSUE THREAD

**Issue by timkellaway** [lynnandtonic/nestflix.fun#168]
Please add as much of the following info as you can:

Title: Irma Vep

Type (film/tv show): Film

Film or show in which it appears: Irma Vep (1996) (apparently being remade as a limited series)

Is the parent film/show streaming anywhere? Not sure (prev. Criterion Channel)

About when in the parent film/show does it appear? Throughout, but final product at the end

Actual footage of the film/show can be seen (yes/no)? Yes

**Comment by lynnandtonic** [comment]
Thank you!! https://nestflix.fun/irma-vep/
