### ISSUE TITLE
Johnny Chimpo

### ISSUE THREAD

**Issue by gravygravel** [lynnandtonic/nestflix.fun#171]
Please add as much of the following info as you can:

Title: Johnny Chimpo

Type (film/tv show): TV Show

Film or show in which it appears: Super Troopers

Is the parent film/show streaming anywhere? Yes

About when in the parent film/show does it appear? Middle

Actual footage of the film/show can be seen (yes/no)? Yes

https://www.youtube.com/watch?v=UJtQhv9dp9o

**Comment by lynnandtonic** [comment]
It’s live! Thank you! https://nestflix.fun/johnny-chimpo/
