### ISSUE TITLE
Diamond Jim

### ISSUE THREAD

**Issue by gravygravel** [lynnandtonic/nestflix.fun#172]
Please add as much of the following info as you can:

Title: Bonjour, Diamond Jim

Type (film/tv show): Film

Film or show in which it appears: Tim and Eric's Billion Dollar Movie

Is the parent film/show streaming anywhere? Yes

About when in the parent film/show does it appear? Start

Actual footage of the film/show can be seen (yes/no)? Yes

https://www.youtube.com/watch?v=nUpvDOxg8as

**Comment by lynnandtonic** [comment]
Thank you!! https://nestflix.fun/bonjour-diamond-jim/
