### ISSUE TITLE
Invitation to Love

### ISSUE THREAD

**Issue by gravygravel** [lynnandtonic/nestflix.fun#173]
Please add as much of the following info as you can:

Title: Invitation to Love

Type (film/tv show): TV Show, Soap Opera

Film or show in which it appears: Twin Peaks, Season 1

Is the parent film/show streaming anywhere? https://www.hulu.com/series/twin-peaks-72678117-3cc6-45dc-a294-270ef30a937a

About when in the parent film/show does it appear? Throughout S1 in 15-30 second snippets

Actual footage of the film/show can be seen (yes/no)? Yes

https://www.youtube.com/watch?v=PiItVFyA-iI

**Comment by lynnandtonic** [comment]
It’s on the site! https://nestflix.fun/invitation-to-love/
