### ISSUE TITLE
Question on Vlog Eligibility - iCarly

### ISSUE THREAD

**Issue by moocow1452** [lynnandtonic/nestflix.fun#174]
I understand that the iCarly stream is logged on Nestflix, but is it eligible if it's not really a film or tv series, but an internet project? Would the Blog of Doctor Horrible or Katie Mitchell's YouTube channel be eligible for inclusion, or is it the artifice of iCarly having good production values and being presented in a variety show format that makes it eligible?

**Comment by lynnandtonic** [comment]
@moocow1452 Ah good question. I think the project having a title/logo is a good indicator that it’s something I would include. Rather than just a series of vlogs or a YouTube channel.
