### ISSUE TITLE
Add Thundergun

### ISSUE THREAD

**Issue by davidribyrne** [lynnandtonic/nestflix.fun#178]
Please add as much of the following info as you can:

Title: Thundergun 

Type (film/tv show): film

Film or show in which it appears: From It's Always Sunny in Philadelphia

Is the parent film/show streaming anywhere? Yes, on Hulu

About when in the parent film/show does it appear?

Actual footage of the film/show can be seen (yes/no)? Yes

**Comment by lynnandtonic** [comment]
Closing this as it’s a duplicate of #51.
