### ISSUE TITLE
Add "The Gray Ghost"

### ISSUE THREAD

**Issue by HarleysTwin** [lynnandtonic/nestflix.fun#179]
Please add as much of the following info as you can:

Title: The Gray Ghost (The episode of "The Gray Ghost" within the Batman episode is called 'The Mad Bomber')

Type (film/tv show): TV show - superhero action

Film or show in which it appears: Batman: The Animated Series/The Adventures of Batman & Robin (1992-1995)

Is the parent film/show streaming anywhere? Yes: HBO Max

About when in the parent film/show does it appear? twice in ep. 1x18 - "Beware the Gray Ghost" starting from the very beginning of the episode: https://www.youtube.com/watch?v=b4nfqEjennA

Also starting at 14:49 - 15:10 (though partically obscured by Bruce's head)

Actual footage of the film/show can be seen (yes/no)? Yes

Cast: Simon Trent

**Comment by lynnandtonic** [comment]
Thank you, @HarleysTwin! https://nestflix.fun/the-gray-ghost/
