### ISSUE TITLE
Wizard Robot and his less successful friend

### ISSUE THREAD

**Issue by Galaxyboy542** [lynnandtonic/nestflix.fun#180]
Title: Wizard Robot and his less successful friend

Type (film/tv show): Show

Film or show in which it appears: Family guy

Is the parent film/show streaming anywhere? Hulu

About when in the parent film/show does it appear?  S12E17 

Actual footage of the film/show can be seen (yes/no)? yes

https://www.youtube.com/watch?v=hyoQZfENFJk

**Comment by lynnandtonic** [comment]
Thank you! https://nestflix.fun/wizard-robot-and-his-less-successful-friend/
