### ISSUE TITLE
Add 'Love that Baby'

### ISSUE THREAD

**Issue by HarleysTwin** [lynnandtonic/nestflix.fun#181]
Please add as much of the following info as you can:

Title: Love that Baby

Type (film/tv show): TV show - family sitcom

Film or show in which it appears: Batman: The Animated Series/The Adventures of Batman & Robin

Is the parent film/show streaming anywhere? Yes - HBO Max

About when in the parent film/show does it appear? - sprinkled in episode 3x04 "Baby-Doll"
Timestamps (use link https://www.b98.tv/video/baby-doll/): 2:28 - 2:47; 3:25 - 3:36; 10:40 - 10:43, 10:57 - 11:04; 11:07 - 11:08, 11:23 - 11:29 <- Some of these are repeated footage.
                                                                                       
Actual footage of the film/show can be seen (yes/no)? Yes

Cast: Mary Louise Dahl, Tod Baker, June Winthrop, Tammy Vance, Brian Daly, "Spunky" Spencer, & Buster the dog 

Quote: "I didn't mean to."

**Comment by lynnandtonic** [comment]
Thank you, @HarleysTwin! https://nestflix.fun/love-that-baby/
