### ISSUE TITLE
Add Moonquake Lake

### ISSUE THREAD

**Issue by deborahgu** [lynnandtonic/nestflix.fun#182]
Please add as much of the following info as you can:

Title: Moonquake Lake

Type (film/tv show): film

Film or show in which it appears: Annie

Is the parent film/show streaming anywhere?

About when in the parent film/show does it appear?

Actual footage of the film/show can be seen (yes/no)? Yes

The entire trailer: https://www.youtube.com/watch?v=IS0dl0FtCXk

**Comment by lynnandtonic** [comment]
It’s up! https://nestflix.fun/moonquake-lake/

Thank you!
