### ISSUE TITLE
Add Face Punch

### ISSUE THREAD

**Issue by deborahgu** [lynnandtonic/nestflix.fun#183]
Please add as much of the following info as you can:

Title: Face Punch

Type (film/tv show): Film

Film or show in which it appears: Twilight: New Moon

Is the parent film/show streaming anywhere?

About when in the parent film/show does it appear? Conversation begins at 48m, the movie itself begins at 49m50s.

Actual footage of the film/show can be seen (yes/no)? Yes heard, no seen. (They're in the theatre listening to it for 1 minute.)

**Comment by lynnandtonic** [comment]
Because we don’t see any footage, I won’t be adding Face Punch right now. As much as I do love that scene! Thanks, @deborahgu!
