### ISSUE TITLE
Add Hunger Games 74 and 75

### ISSUE THREAD

**Issue by moocow1452** [lynnandtonic/nestflix.fun#187]
Please add as much of the following info as you can:

Title: The 74th/75th Annual Hunger Games

Type (film/tv show): Television Event

Film or show in which it appears: Hunger Games Series

Is the parent film/show streaming anywhere? Peacock

About when in the parent film/show does it appear? Often

Actual footage of the film/show can be seen (yes/no)? Yea

**Comment by lynnandtonic** [comment]
I thought about this one a lot. Still undecided whether it qualifies as a sporting event? I will noodle on it more.

**Comment by moocow1452** [comment]
It's a sporting event, but it's also on scale with the Super Bowl or the Grammys for their society as something that is an unmistakable cultural event. Not sure if that separates it from something like the All Valley Karate Tournament or the Bubblebowl Halftime Show, but maybe more in the realm of a Nestflix+ or another project entirely.

**Comment by lynnandtonic** [comment]
Went back and forth on this one, but I'm not going to add it at least right now. Thank you!
