### ISSUE TITLE
Add The Cooper Clan

### ISSUE THREAD

**Issue by TheAmazingRaspberry** [lynnandtonic/nestflix.fun#189]
Title: The Cooper Clan

Type (film/tv show): TV show

Show in which it appears: Monk

Is the parent show streaming anywhere? Amazon Prime and Peacock

About when in the parent show does it appear? Season 8, Episode 1, "Mr. Monk's Favorite Show"

Actual footage of the show can be seen (yes/no)? Yes

Cast:
Christine Rapp as Kathy Cooper
Brendan Collins as Mr. Cooper
Gail Rodono as Mrs. Cooper
Lauren Perkins as Janey Cooper
Steven Dorn as William "Billy" Cooper

Show most likely ended in 1974 (the show is mentioned to have ended "35 years ago," and if the Monk episode occurred the same year it aired, 2009, that would mean the show was cancelled in 1974. That happens to be the same year The Brady Bunch was cancelled.)

Link to Monk wiki: https://monk.fandom.com/wiki/Mr._Monk%27s_Favorite_Show

**Comment by lynnandtonic** [comment]
Thank you again! https://nestflix.fun/the-cooper-clan/
