### ISSUE TITLE
Add Explosión Gigantesca de Romance

### ISSUE THREAD

**Issue by TheAmazingRaspberry** [lynnandtonic/nestflix.fun#190]
Title: Explosión Gigantesca de Romance

Type (film/tv show): TV show

Show in which it appears: Psych

Is the parent film/show streaming anywhere? Amazon Prime, Peacock

About when in the parent film/show does it appear? Season 2, Episode 13, "Lights, Camera... Homicidio"

Actual footage of the film/show can be seen (yes/no)? Yes

Cast
Jorge Gama-Lobo
Quintessa Gabriel as Corinne
Shawn Spencer as Chad

Head writer: Lance Rothstein

Link to Psych wiki: https://psychusa.fandom.com/wiki/Lights,_Camera..._Homicidio

![Lights, Camera, Homicidio](https://user-images.githubusercontent.com/80358995/129494135-91c27b46-1b61-48d0-8145-720edfbd9028.jpg)
Chad (Shawn Spencer) and Corinne (Quintessa Gabriel)

**Comment by lynnandtonic** [comment]
Already got this one going! Woohoo!

**Comment by TheAmazingRaspberry** [comment]
Do you also happen to be working on "Paths of Love" from "Shawn and the Real Girl" (6x12)? I was going to make an issue for that but if you're already working on adding it, it's probably not necessary.

**Comment by lynnandtonic** [comment]
Yes! Should be on the site tomorrow or Tues.

**Comment by lynnandtonic** [comment]
It‘s up! https://nestflix.fun/explocion-gigantesca-de-romance/
