### ISSUE TITLE
Add Savage Seduction

### ISSUE THREAD

**Issue by TheAmazingRaspberry** [lynnandtonic/nestflix.fun#192]
Title: Savage Seduction

Type (film/tv show): TV show

Film or show in which it appears: Warehouse 13

Is the parent film/show streaming anywhere? Peacock, IMDB TV

About when in the parent film/show does it appear? Season 5, Episode 4, "Savage Seduction"

Actual footage of the film/show can be seen (yes/no)? Yes

Cast (Note: All of the cast members listed are not technically the real cast, as they were sucked into the show. It makes sense in context)
Hortencia Hernandez as Doña Fausta
Myka Bering as Maribel
Kelly Hernandez as Carmen
Pete Lattimer as Armando
Artie Nielsen as Colonel Rafael

Link to Warehouse 13 wiki: https://warehouse13.fandom.com/wiki/Savage_Seduction

Show is most likely cancelled in 2014

![Savage Seduction](https://user-images.githubusercontent.com/80358995/129494350-365d303e-ef30-4b43-81c6-70d7955a2d20.png)
Left to right: Armando, Doña Fausta, Carmen, Alicia

**Comment by lynnandtonic** [comment]
It’s up! https://nestflix.fun/seduccion-salvaje/

Thank you, @TheAmazingRaspberry!
