### ISSUE TITLE
Add Crime Lab S.F.

### ISSUE THREAD

**Issue by TheAmazingRaspberry** [lynnandtonic/nestflix.fun#193]
Title: Crime Lab S.F.

Type (film/tv show): TV show

Film or show in which it appears: Monk

Is the parent film/show streaming anywhere? Peacock, Amazon Prime

About when in the parent film/show does it appear? Season 2, Episode 12, "Mr. Monk and the TV Star"

Actual footage of the film/show can be seen (yes/no)? Yes

Cast:
Brad Terry

Link to Monk wiki: https://monk.fandom.com/wiki/Mr._Monk_and_the_TV_Star

**Comment by lynnandtonic** [comment]
Thank you! https://nestflix.fun/crime-lab-sf/
