### ISSUE TITLE
Add Treasure Chest

### ISSUE THREAD

**Issue by TheAmazingRaspberry** [lynnandtonic/nestflix.fun#194]
Title: Treasure Chest

Type (film/tv show): TV show

Film or show in which it appears: Monk

Is the parent film/show streaming anywhere? Amazon Prime, Peacock

About when in the parent film/show does it appear? Season 3, Episode 8, "Mr. Monk and the Game Show"

Actual footage of the film/show can be seen (yes/no)? Yes

Cast:
Roddy Lankman (host)
Lizzie Talvo (Lankman's assistant)

Producer: Dwight Ellison

Known contestants: Val Birch, Adrian Monk

Link to Monk wiki: https://monk.fandom.com/wiki/Mr._Monk_and_the_Game_Show

I'm not sure if game shows are allowed

**Comment by lynnandtonic** [comment]
Thank you!! https://nestflix.fun/treasure-chest/
