### ISSUE TITLE
Add WHAT DO KIDS KNOW from PTA's MAGNOLIA

### ISSUE THREAD

**Issue by Fvrtrppr** [lynnandtonic/nestflix.fun#200]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Fvrtrppr** [comment]
Thank you!

**Comment by lynnandtonic** [comment]
Thank you! https://nestflix.fun/what-do-kids-know/
