### ISSUE TITLE
King Lear and Jack and the Behnstalks 

### ISSUE THREAD

**Issue by Cnb5686** [lynnandtonic/nestflix.fun#207]
Please add as much of the following info as you can:

Title: King Lear and Jack and the Behnstalks

Type (film/tv show): Films

Film or show in which it appears: The Lost World Jurassic Park

Is the parent film/show streaming anywhere? HBO Max

About when in the parent film/show does it appear? 1:52:55

Actual footage of the film/show can be seen (yes/no)? No only posters

**Comment by lynnandtonic** [comment]
I’m only adding titles that show actual footage right now, so going to close this. Thank you!!
