### ISSUE TITLE
Lauren is Explorin'

### ISSUE THREAD

**Issue by ethanimation** [lynnandtonic/nestflix.fun#209]
**Is your feature request related to a problem? Please describe.**
[Watch classic episodes like Lauren is Explorin' is learning about Colors.]

**Describe the solution you'd like**
[TV-Y - 2 seasons - tv series, comedy]

**Describe alternatives you've considered**
Director: Craig McCracken
As seen in: Foster's Home for Imaginary Friends (2004-2004)

**Additional context**
![lauren is exploring](https://user-images.githubusercontent.com/88994668/129502354-5a1cdf4b-b070-4ff5-be42-723d1eef5950.png)

![lauren is exploring LOGO](https://user-images.githubusercontent.com/88994668/129502740-b8537dd5-1253-409c-82eb-2d42e09adb99.png)

**Comment by lynnandtonic** [comment]
Thank you! https://nestflix.fun/lauren-is-explorin/
