### ISSUE TITLE
Add That's So Rachel

### ISSUE THREAD

**Issue by HoneysucklePink** [lynnandtonic/nestflix.fun#210]
Please add as much of the following info as you can:

Title: That's So Rachel

Type (film/tv show): TV show

Film or show in which it appears: Glee

Is the parent film/show streaming anywhere? Yes, Netflix and Amazon Prime

About when in the parent film/show does it appear? Season 6, Episode 1

Actual footage of the film/show can be seen (yes/no)? Yes
[https://www.youtube.com/watch?v=K1p4nqja8Z0]
(https://www.youtube.com/watch?v=K1p4nqja8Z0 )

**Comment by lynnandtonic** [comment]
Thank you! https://nestflix.fun/thats-so-rachel/
