### ISSUE TITLE
Add Mr. Parker's Cul De Sac 

### ISSUE THREAD

**Issue by UltimoDragon20** [lynnandtonic/nestflix.fun#212]
Please add as much of the following info as you can:

Title: Mr. Parker's Cul De Sac

Type (film/tv show): Children's TV Show

Film or show in which it appears: DC''s Legends Of Tomorrow Episode 7 Season 5

Is the parent film/show streaming anywhere?: The CW and Netflix

About when in the parent film/show does it appear?: Season 5 Episode 7, Titled ''Mr. Parker's Cul De Sac''

Actual footage of the film/show can be seen (yes/no)?: Yes a Whole Episode Around it

**Comment by lynnandtonic** [comment]
This is a duplicate of #81 so closing this one. Thank you!
