### ISSUE TITLE
Fish Bowl 2

### ISSUE THREAD

**Issue by Xevnar994** [lynnandtonic/nestflix.fun#217]
The classic follow up to the groundbreaking original Fish Bowl motion picture.

Title: Fish Bowl 2

Type (film/tv show): Film

Film or show in which it appears: Ed, Edd n Eddy

Is the parent film/show streaming anywhere? Yes

About when in the parent film/show does it appear? Appears briefly in several episodes, the first being S1E1b - Nagged to Ed

Actual footage of the film/show can be seen (yes/no)? Yes

![Fish-Bowl-2](https://user-images.githubusercontent.com/75587301/129507292-8cb7b4df-2b7c-4277-8d1a-2a22250c5eb5.gif)

**Comment by lynnandtonic** [comment]
Thank you! https://nestflix.fun/fish-bowl-ii/
