### ISSUE TITLE
Add: Snagg! from Jellystone!

### ISSUE THREAD

**Issue by TooniFNT** [lynnandtonic/nestflix.fun#219]
Please add as much of the following info as you can:

**Title:** Snagg!

**Type (film/tv show):** Talk Show

**Film or show in which it appears:** Jellystone! (2021-present)

**Cast:** Snagglepuss

**Is the parent film/show streaming anywhere?** HBO Max

**About when in the parent film/show does it appear?** In the episode "Ice, Ice Daddy", Captain Caveman goes on the show to see if Caveman Jr. is really his son.

**Actual footage of the film/show can be seen (yes/no)?** Yes.

![vlcsnap-2021-08-15-23h30m35s607](https://user-images.githubusercontent.com/88996737/129508308-c6a9c875-50d3-4c42-b1ef-ece8d6771c04.png)
![vlcsnap-2021-08-15-23h30m53s907](https://user-images.githubusercontent.com/88996737/129508321-8b5eaa2e-dc02-4591-a2e3-c9ae49d69417.png)
![vlcsnap-2021-08-15-23h31m01s619](https://user-images.githubusercontent.com/88996737/129508332-064b3bb0-47af-48c5-9cda-0e602ae54bc7.png)
![vlcsnap-2021-08-15-23h31m32s859](https://user-images.githubusercontent.com/88996737/129508344-282c777f-1d04-456c-bc37-641b895071e9.png)
![vlcsnap-2021-08-15-23h32m26s688](https://user-images.githubusercontent.com/88996737/129508347-734777a1-6a12-4db2-a4dc-b6957789cb1b.png)

**Comment by lynnandtonic** [comment]
Thank you! https://nestflix.fun/snagg/
