### ISSUE TITLE
Blood Ocean

### ISSUE THREAD

**Issue by Xevnar994** [lynnandtonic/nestflix.fun#221]
In a world with no laws, the planets are being pillaged by space vikings, a secret revealing the identity of a serial killer, and the oil rig with a haunted crypt lies where love happened to death. Experience the once destroyed but now restored critically acclaimed blood thirsty carnage of a motion picture from the brutal minds of Dethklok.

Title: Blood Ocean

Type (film/tv show): Film

Film or show in which it appears: Metalocalypse

Is the parent film/show streaming anywhere? Yes

About when in the parent film/show does it appear? S1E19 - Dethstars

Actual footage of the film/show can be seen (yes/no)? Yes

![1457108023-Blood_Ocean_by_tsutar](https://user-images.githubusercontent.com/75587301/129509476-fce6b0b9-fd89-4e6e-a39f-dcb90125d9a5.jpg)
![tumblr_nbf5j2Vb6P1tq1h0fo4_500](https://user-images.githubusercontent.com/75587301/129509485-54d90679-9da5-4982-8b91-282cca094896.gif)

**Comment by lynnandtonic** [comment]
Thank you! https://nestflix.fun/blood-ocean/
