### ISSUE TITLE
Add: You Beat Your Wife

### ISSUE THREAD

**Issue by TooniFNT** [lynnandtonic/nestflix.fun#227]
Please add as much of the following info as you can:

**Title:** You Beat Your Wife

**Type (film/tv show):** Game Show

**Film or show in which it appears:** Looney Tunes (1930-1969)

**Is the parent film/show streaming anywhere?** HBO Max

**About when in the parent film/show does it appear?** In the middle of the short "Wideo Wabbit", Bugs Bunny tricks Elmer Fudd by disguising himself as Groucho Marx and doing a parody of his show _You Bet Your Life_.

**Actual footage of the film/show can be seen (yes/no)?** Yes.

**Comment by lynnandtonic** [comment]
Thank you so much for this submission, @TooniFNT!

I took a look at this one and since it’s mostly a brief gag Bugs is doing on Elmer and not an actual show, I don’t think I’m going to add it right now.
