### ISSUE TITLE
Add: Bambi 2002 from SNL

### ISSUE THREAD

**Issue by TooniFNT** [lynnandtonic/nestflix.fun#229]
Please add as much of the following info as you can:

**Title:** Bambi 2002

**Type (film/tv show):** Animated / Action

**Film or show in which it appears:** Saturday Night Live (1975-present)

**Is the parent film/show streaming anywhere?**  Peacock

**About when in the parent film/show does it appear?** A "Saturday TV Funhouse" sketch depicts this movie.

**Actual footage of the film/show can be seen (yes/no)?** Yes.

**Comment by HarleysTwin** [comment]
I specifically asked, and movies from clip shows like _SNL_ aren't eligible for submission.
