### ISSUE TITLE
Add: Brain Busters from SNL

### ISSUE THREAD

**Issue by TooniFNT** [lynnandtonic/nestflix.fun#230]
Please add as much of the following info as you can:

**Title:** Brain Busters

**Type (film/tv show):** Game Show

**Film or show in which it appears:** Saturday Night Live (1975-present)

**Is the parent film/show streaming anywhere?**  Peacock

**About when in the parent film/show does it appear?** A sketch from the Bernie Mac episode (4/5/2003) depicts the show. On Peacock, it's right after the first ad break.

**Actual footage of the film/show can be seen (yes/no)?** Yes.

**Comment by HarleysTwin** [comment]
I specifically asked, and movies from clip shows like _SNL_ aren't eligible for submission.

**Comment by lynnandtonic** [comment]
Thank you for the suggestion, @TooniFNT! Right now I don’t have plans on adding shows from comedy sketch shows like SNL. Maybe someday though! Closing this for now.
