### ISSUE TITLE
Add: Bumbie, the Dearest Dear

### ISSUE THREAD

**Issue by TooniFNT** [lynnandtonic/nestflix.fun#231]
Please add as much of the following info as you can:

**Title:** Bumbie, the Dearest Deer

**Type (film/tv show):** Animated

**Film or show in which it appears:** Animaniacs (1993-1998)

**Is the parent film/show streaming anywhere?**  Hulu

**About when in the parent film/show does it appear?** The short "Bumbie's Mom" has Slappy and Skippy going to see this movie.

**Actual footage of the film/show can be seen (yes/no)?** Yes.

**Comment by lynnandtonic** [comment]
Thank you! https://nestflix.fun/bumbie-the-dearest-deer/
