### ISSUE TITLE
Add Passions from Buffy

### ISSUE THREAD

**Issue by Association32** [lynnandtonic/nestflix.fun#239]
Please add as much of the following info as you can:

Title: Passions

Type (film/tv show): TV show

Film or show in which it appears: Buffy the Vampire Slayer

Is the parent film/show streaming anywhere? Not that I know of

About when in the parent film/show does it appear? It was introduced in the episode Something blue

Actual footage of the film/show can be seen (yes/no)? no

Link to imdb
https://m.imdb.com/title/tt0192917/movieconnections/?ref_=tt_trv_cnn

**Comment by lynnandtonic** [comment]
Closing this since Passions is real! Thank you!
