### ISSUE TITLE
Add Killer Nuns

### ISSUE THREAD

**Issue by chazlarson** [lynnandtonic/nestflix.fun#242]
Please add as much of the following info as you can:

Title:
Killer Nuns

Type (film/tv show):
film

Film or show in which it appears:
The Comeback Trail (2020)

Is the parent film/show streaming anywhere?
No

About when in the parent film/show does it appear?
Mid-credits [about 1:38:40], trailer for "Killer Nuns" is shown.

Actual footage of the film/show can be seen (yes/no)?
yes

**Comment by lynnandtonic** [comment]
Thank you! https://nestflix.fun/killer-nuns/
