### ISSUE TITLE
Add Springtime for Hitler: A Gay Romp With Adolf and Eva at Berchtesgaden

### ISSUE THREAD

**Issue by RutherfordIP** [lynnandtonic/nestflix.fun#243]
Please add as much of the following info as you can:

Title: Springtime for Hitler: A Gay Romp With Adolf and Eva at Berchtesgaden

Type (film/tv show): Stage Musical

Film or show in which it appears: The Producers

Is the parent film/show streaming anywhere? Not for free, but available on many platforms to rent

About when in the parent film/show does it appear? Near the end

Actual footage of the film/show can be seen (yes/no)? Yes

**Comment by lynnandtonic** [comment]
I don’t plan on adding stage plays or musicals to the site, sorry! Thank you @RutherfordIP! 💚

**Comment by RutherfordIP** [comment]
Thank you! <3
