### ISSUE TITLE
Add Santa Cruz from 28 Days

### ISSUE THREAD

**Issue by artlung** [lynnandtonic/nestflix.fun#245]
Please add as much of the following info as you can:

Title: Santa Cruz

Type (film/tv show): tv show / soap opera

Film or show in which it appears: 28 Days (2000)

Is the parent film/show streaming anywhere? hulu, amazon

About when in the parent film/show does it appear? Mentioned throughout - I believe it’s early on when she gets to rehab and meets the baseball player

Actual footage of the film/show can be seen (yes/no)? yes.

**Comment by lynnandtonic** [comment]
It’s up! https://nestflix.fun/santa-cruz/

Thank you, @artlung!!
