### ISSUE TITLE
Ask Mr. Lizard from Jim Henson's Dinosaurs

### ISSUE THREAD

**Issue by LetterKyew** [lynnandtonic/nestflix.fun#246]
Please add as much of the following info as you can:

Title: Ask Mr. Lizard 

Type (film/tv show): TV show

Film or show in which it appears:  Jim Henson's Dinosaurs

Is the parent film/show streaming anywhere? DISNEY+

About when in the parent film/show does it appear? Episode 201, 215 and 413.

Actual footage of the film/show can be seen (yes/no)?
Yes. The running joke is that the little dinosaur child Timmy always dies and Mr Lizard tells the crew "We're gonna need another Timmy"

**Comment by lynnandtonic** [comment]
Thank you! https://nestflix.fun/ask-mister-lizard/
