### ISSUE TITLE
Please add Shrek 2’s content!

### ISSUE THREAD

**Issue by AMD69** [lynnandtonic/nestflix.fun#247]
Please add the following classics:

Titles: “Far Far Away Royal Ball Blowout”, “Knights”

Type (film/tv show): Red Carpet, Reality show

Film or show in which it appears: Both on Shrek 2

Is the parent film/show streaming anywhere? Netflix

About when in the parent film/show does it appear? During the ending of the film

Actual footage of the film/show can be seen (yes/no)? Yes

**Comment by lynnandtonic** [comment]
Thank you, @AMD69! I added Knights to the site: https://nestflix.fun/knights/

I decided not to add Far Far Away Royal Ball Blowout since it‘s more of an event pre-show like the Oscars.
