### ISSUE TITLE
Countdown (IT Crowd)

### ISSUE THREAD

**Issue by scottkellum** [lynnandtonic/nestflix.fun#248]
Please add as much of the following info as you can:

Title: Countdown

Type (film/tv show): TV Show

Film or show in which it appears: IT Crowd

Is the parent film/show streaming anywhere? Netflix

About when in the parent film/show does it appear? Series 4, episode 2 “The Final Countdown”

Actual footage of the film/show can be seen (yes/no)? Yes

Information here: https://theitcrowd.fandom.com/wiki/The_Final_Countdown

**Comment by kyl416** [comment]
Countdown is real UK game show and the episode featured the actual host and some regular panalists playing themselves, it wasn't something made up for the IT Crowd.

**Comment by lynnandtonic** [comment]
Bummer it’s real! Thanks, y’all.
