### ISSUE TITLE
Add Live with Murray Franklin

### ISSUE THREAD

**Issue by AMD69** [lynnandtonic/nestflix.fun#249]
Please add as much of the following info as you can:

Title: Live! With Murray Franklin

Type (film/tv show): Film

Film or show in which it appears: Joker (2019)

Is the parent film/show streaming anywhere? HBO Max

About when in the parent film/show does it appear? All the movie

Actual footage of the film/show can be seen (yes/no)? Yup

**Comment by lynnandtonic** [comment]
Thank you, @AMD69! It’s on the site now: https://nestflix.fun/live-with-murray-franklin/
