### ISSUE TITLE
Add Today In Fashion

### ISSUE THREAD

**Issue by AMD69** [lynnandtonic/nestflix.fun#253]
Please add as much of the following info as you can:

Title: Today In Fashion

Type (film/tv show): tv reality

Film or show in which it appears: Mars Attacks!

Is the parent film/show streaming anywhere? HBO MAX 

About when in the parent film/show does it appear? First 20 mins

Actual footage of the film/show can be seen (yes/no)? Yep

**Comment by lynnandtonic** [comment]
Thank you!! https://nestflix.fun/today-in-fashion/
