### ISSUE TITLE
Add Too Many Cooks

### ISSUE THREAD

**Issue by MarNicGit** [lynnandtonic/nestflix.fun#255]
**Title:** Too Many Cooks

**Type (film/tv show):** TV Show

**Film or show in which it appears:** Adult Swim?

**Is the parent film/show streaming anywhere?** N/A

**About when in the parent film/show does it appear?** N/A

**Actual footage of the film/show can be seen (yes/no)?** Yes, entire intro plus 7 seconds of the show can be seen on Youtube: https://www.youtube.com/watch?v=QrGrOK8oZG8

**Comment by lynnandtonic** [comment]
Unfortunately I think this is more a standalone comedy sketch than an in-universe show. I hadn’t watched it in a long time though, so thanks for the reminder!

Thanks for submitting! 💚
