### ISSUE TITLE
Kakie the Cake Monster from Hotel Transylvania 2

### ISSUE THREAD

**Issue by mommilonglegs8** [lynnandtonic/nestflix.fun#256]
Please add as much of the following info as you can:

Title: Kakie the Cake Monster

Type (film/tv show): TV Show

Film or show in which it appears: Hotel Transylvania 2

Is the parent film/show streaming anywhere? Yes, Hulu

About when in the parent film/show does it appear? About 24 Min into the movie

Actual footage of the film/show can be seen (yes/no)? Yes

**Comment by lynnandtonic** [comment]
Thank you! https://nestflix.fun/kakie-the-cake-monster/
