### ISSUE TITLE
 Popular Slut Club 

### ISSUE THREAD

**Issue by ethanimation** [lynnandtonic/nestflix.fun#257]
Please add as much of the following info as you can:

Title:  Popular Slut Club 

Type (film/tv show): tv show

Film or show in which it appears: Futurama Season 6 Episode 21 Yo Leela Leela 

Actual footage of the film/show can be seen (yes)

![psc logo futurama](https://user-images.githubusercontent.com/88994668/129626830-83d1fa97-9327-4027-bb1f-6f3a08bae584.png)

**Comment by ethanimation** [comment]
![Popular Slut Club 2](https://user-images.githubusercontent.com/88994668/130534649-e5ff84b5-3215-48ee-9bf8-12aac8d3cb25.png)

**Comment by lynnandtonic** [comment]
It‘s live! Thank you!! https://nestflix.fun/popular-slut-club/
