### ISSUE TITLE
Add Sand Pirates of the Sahara

### ISSUE THREAD

**Issue by PhilMeyerSucks** [lynnandtonic/nestflix.fun#258]
Title:
Sand Pirates of the Sahara

Type (film/tv show): 
Film

Film or show in which it appears: 
The Majestic

Is the parent film/show streaming anywhere? 
For rent on Amazon, VUDU, Google Play, Redbox and DirecTV

About when in the parent film/show does it appear?
Approximately 1:33:00

Actual footage of the film/show can be seen (yes/no)?
Yes
![SPotS_Title](https://user-images.githubusercontent.com/89033012/129632679-0784f4a3-9fa3-4571-bd8d-9efaf13fd064.png)

![SPotS_Screeenshot4](https://user-images.githubusercontent.com/89033012/129602297-df37d744-3065-4be3-bdcd-d679f2096929.png)
![SPotS_Screeenshot2](https://user-images.githubusercontent.com/89033012/129602303-1a6127b1-38be-4cb8-9502-c8f425fa5df9.png)
![SPotS_Screeenshot1](https://user-images.githubusercontent.com/89033012/129602304-183942a6-f34b-4adc-b772-c4d7de339204.png)
![SPotS_Screeenshot3](https://user-images.githubusercontent.com/89033012/129602306-f23c8866-9221-4333-8fa2-cf5a2f177203.png)
![SPotS_Screeenshot5](https://user-images.githubusercontent.com/89033012/129602309-f57b3b47-b665-4ca7-ae0f-1b500f200853.png)

**Comment by lynnandtonic** [comment]
It’s up! https://nestflix.fun/sand-pirates-of-the-sahara/

Thank you for all the info! 💚
