### ISSUE TITLE
Add Saving the Last Soldier from “Hello, Me!” (Screenshots added)

### ISSUE THREAD

**Issue by HarleysTwin** [lynnandtonic/nestflix.fun#261]
Please add as much of the following info as you can:

Title: Saving the Last Soldier

Type (film/tv show): film - war drama (foreign: Korean)

Film or show in which it appears: Hello, Me!

Is the parent film/show streaming anywhere? Yes - Netflix

About when in the parent film/show does it appear? about 20 minutes into the first episode

Actual footage of the film/show can be seen (yes/no)? Yes

Cast: Anthony

**Comment by HarleysTwin** [comment]
![Saving the Last Soldier 1](https://user-images.githubusercontent.com/88982629/180015380-bf656ad0-b964-49a0-951d-477ad84c98c2.jpg)
![Saving the Last Soldier 2](https://user-images.githubusercontent.com/88982629/180015383-66dcba51-7f53-4c73-b16e-5afb9c7ec4e9.jpg)
![Saving the Last Soldier 3](https://user-images.githubusercontent.com/88982629/180015387-ea12f0b5-e0b0-4f16-b385-ce3ecc14ffd2.jpg)
![Saving the Last Soldier 4](https://user-images.githubusercontent.com/88982629/180015388-4e7732c0-cb19-4ca4-9a01-229fcffe3964.jpg)
![Saving the Last Soldier 5](https://user-images.githubusercontent.com/88982629/180015389-27fe86f0-6949-4027-9dc7-3fdabfb7717c.jpg)
![Saving the Last Soldier 6](https://user-images.githubusercontent.com/88982629/180015392-9368997e-821b-4791-9378-71776cc16d39.jpg)
![Saving the Last Soldier 7](https://user-images.githubusercontent.com/88982629/180015393-bfccbdb3-3e17-4a11-838a-d9ba7a92c5a5.jpg)
![Saving the Last Soldier 8](https://user-images.githubusercontent.com/88982629/180015397-aea728a8-7531-468d-9ea2-4d29e24ad400.jpg)
![Saving the Last Soldier 9](https://user-images.githubusercontent.com/88982629/180015398-68d7b28c-f425-458f-bd89-53df9484dd2c.jpg)
![Saving the Last Soldier 10](https://user-images.githubusercontent.com/88982629/180015401-89521cc3-a965-4983-a7f7-3712b8bf630e.jpg)
![Saving the Last Soldier 11](https://user-images.githubusercontent.com/88982629/180015403-7e0ace30-faaf-4273-8f74-d0f42858f411.jpg)

**Comment by lynnandtonic** [comment]
@HarleysTwin Do they mention the title somewhere in dialogue? Or did you translate the sandwich board from the set? Just wanted to confirm the title. Thanks!

**Comment by HarleysTwin** [comment]
@lynnandtonic Several episodes later, Anthony yells to his handlers about how, if he wasn’t as great as he was, he wouldn’t have been able to get into character for the film, and that’s when he says the title.

**Comment by lynnandtonic** [comment]
@HarleysTwin Ah perfect, thank you!

**Comment by lynnandtonic** [comment]
Thanks again! https://nestflix.fun/saving-the-last-soldier/
