### ISSUE TITLE
Add The Crying Detective

### ISSUE THREAD

**Issue by HarleysTwin** [lynnandtonic/nestflix.fun#265]
Please add as much of the following info as you can:

Title: The Crying Detective

Type (film/tv show): Film - detective noir

Film or show in which it appears: Frankenstein's Monster's Monster, Frankenstein

Is the parent film/show streaming anywhere? Yes - Netflix

About when in the parent film/show does it appear? about 22:15 - 22:40

Actual footage of the film/show can be seen (yes/no)? Yes

Cast: David Harbour Jr.

Quote: Why are you avoiding talking about your mother?

**Comment by lynnandtonic** [comment]
Thank you! https://nestflix.fun/the-crying-detective/
