### ISSUE TITLE
Add Lil Ark Angel “Cats Don’t Dance” (Screenshots and Title Screen Added)

### ISSUE THREAD

**Issue by HarleysTwin** [lynnandtonic/nestflix.fun#266]
Please add as much of the following info as you can:

Title: Lil Ark Angel

Type (film/tv show): Film - Golden Age musical

Film or show in which it appears: Cats Don't Dance

Is the parent film/show streaming anywhere? Yes - Amazon Prime

About when in the parent film/show does it appear? probably about the first third of the film

Actual footage of the film/show can be seen (yes/no)? Yes.  Here is the musical number "Little Boat on the Sea": https://www.youtube.com/watch?v=bShn4m6I49k

Cast: Darla Dimple

Director:  Flanagan

Production Company: Mammoth Pictures

Quote: I built a little boat as cute as it can be, and I put all the animals two-by-two in my little boat on the sea.

**Comment by HarleysTwin** [comment]
![Lil Ark Angel 1](https://user-images.githubusercontent.com/88982629/182438802-f21d3e12-b594-44a2-90a6-ffb14e4fc539.jpg)
![Lil Ark Angel 2](https://user-images.githubusercontent.com/88982629/182438804-bd5c01f2-bab1-4d41-b513-0188570cef20.jpg)
![Lil Ark Angel 3](https://user-images.githubusercontent.com/88982629/182438805-1d6406b6-047e-4fa2-bbd9-9b80d50e5b58.jpg)
![Lil Ark Angel 4](https://user-images.githubusercontent.com/88982629/182438807-86391eb4-7ed3-4102-8ba2-669afe298bc3.jpg)
![Lil Ark Angel 5](https://user-images.githubusercontent.com/88982629/182438809-8ddb68a3-3489-424d-8a24-1f574ce37891.jpg)
![Lil Ark Angel 6](https://user-images.githubusercontent.com/88982629/182438811-2d101d94-5abc-480a-bfec-290aa7c55cd2.jpg)
![Lil Ark Angel 7](https://user-images.githubusercontent.com/88982629/182438812-f022639e-abf3-4662-b1d4-7fd9989bfb24.jpg)
![Lil Ark Angel 8](https://user-images.githubusercontent.com/88982629/182438815-8c64a6fc-bca2-4e7e-bb79-722919895569.jpg)
![Lil Ark Angel 9](https://user-images.githubusercontent.com/88982629/182438816-c70fbd1f-f2c9-4d6b-a9a1-2d3f1b73ad49.jpg)
![Lil Ark Angel 10](https://user-images.githubusercontent.com/88982629/182438818-2eb3fcf8-462f-4bee-a9e5-c51a7c7825b3.jpg)
![Lil Ark Angel 11](https://user-images.githubusercontent.com/88982629/182438821-f91d996e-8a3e-4b9a-86cd-a76b43f497a5.jpg)
![Lil Ark Angel 12](https://user-images.githubusercontent.com/88982629/182438822-9ea51132-7109-41e6-8745-c671e3bda6a9.jpg)
![Lil Ark Angel 13](https://user-images.githubusercontent.com/88982629/182438824-ab028ab8-8425-4cd6-8c4a-7c57377b1879.jpg)
![Lil Ark Angel 14](https://user-images.githubusercontent.com/88982629/182438826-ffce22fd-37fa-45b2-9553-8f7575dbbe7a.jpg)
![Lil Ark Angel 15](https://user-images.githubusercontent.com/88982629/182438827-276a198e-06c5-4891-9e1d-3494884cdd66.jpg)
![Lil Ark Angel 16](https://user-images.githubusercontent.com/88982629/182438828-cfb11ff2-7f7f-48c0-96fa-589be4a97be5.jpg)
![Lil Ark Angel 17](https://user-images.githubusercontent.com/88982629/182438830-c4877326-19a5-4099-9daf-231985847d47.jpg)
![Lil Ark Angel 18](https://user-images.githubusercontent.com/88982629/182438831-b16e7f39-ee9a-4db2-87f7-fc5e283be59a.jpg)
![Lil Ark Angel TItle](https://user-images.githubusercontent.com/88982629/182438832-78e68aaf-e554-48e4-b188-675b922d8b8c.jpg)

**Comment by lynnandtonic** [comment]
Thank you! https://nestflix.fun/lil-ark-angel/
