### ISSUE TITLE
Add Dogcopter 3

### ISSUE THREAD

**Issue by artlung** [lynnandtonic/nestflix.fun#27]
Please add as much of the following info as you can:

Title:

Type (film/tv show): film

Film or show in which it appears: Steven Universe

Is the parent film/show streaming anywhere? HBO MAX

About when in the parent film/show does it appear? S01E17

Actual footage of the film/show can be seen (yes/no)? yes

**Comment by artlung** [comment]
https://steven-universe.fandom.com/wiki/Dogcopter_3

**Comment by lynnandtonic** [comment]
It's up! https://nestflix.fun/dogcopter-3/

Thank youuuuu!
