### ISSUE TITLE
Add Kill It Before It Dies

### ISSUE THREAD

**Issue by nest-aka-swan** [lynnandtonic/nestflix.fun#274]
Please add as much of the following info as you can:

Title: Kill It Before It Dies

Type (film/tv show): film

Film or show in which it appears: Charmed

Is the parent film/show streaming anywhere? https://www.amazon.com/gp/video/detail/B0093SJGSM

About when in the parent film/show does it appear? Chick Flick (s2e18)

Actual footage of the film/show can be seen (yes/no)? yes

https://charmed.fandom.com/wiki/Kill_It_Before_It_Dies

**Comment by lynnandtonic** [comment]
It’s live! https://nestflix.fun/kill-it-before-it-dies/ Thank you!
