### ISSUE TITLE
Add It's Not My Problem!

### ISSUE THREAD

**Issue by artlung** [lynnandtonic/nestflix.fun#28]
Please add as much of the following info as you can:

Title: It's Not My Problem

Type (film/tv show): tv show

Film or show in which it appears: RoboCop (1987)

Is the parent film/show streaming anywhere? Paramount, apparently and for rent several places

About when in the parent film/show does it appear? in a few spots

Actual footage of the film/show can be seen (yes/no)? yes

https://robocop.fandom.com/wiki/It%27s_Not_My_Problem! (best known for skeevy catchphrase "I'd buy that for a dollar!")

**Comment by waxpancake** [comment]
It's on the site here. https://nestflix.fun/its-not-my-problem/

**Comment by artlung** [comment]
Thanks @waxpancake I think I must not know how to operate search. Closing.

**Comment by waxpancake** [comment]
@artlung There's an issue with apostrophes in search. I'll file it.

works:
https://nestflix.fun/search?search=not+my+problem

doesn't work:
https://nestflix.fun/search?search=it%27s+not+my+problem
