### ISSUE TITLE
Add Barbara Manatee

### ISSUE THREAD

**Issue by Lu9-ST** [lynnandtonic/nestflix.fun#283]
Please add as much of the following info as you can:

Title: Barbara Manatee

Type (film/tv show): TV Show (Soap Opera)

Film or show in which it appears: VeggieTales

Is the parent film/show streaming anywhere?
Yes

About when in the parent film/show does it appear?
King George and the Ducky

Actual footage of the film/show can be seen (yes/no)?
No (Only audio, and a plush toy)

**Comment by lynnandtonic** [comment]
Thank you! I’m only adding titles with actual footage for now, so going to close this.
