### ISSUE TITLE
Add Way Too Complicated

### ISSUE THREAD

**Issue by clebercasali** [lynnandtonic/nestflix.fun#286]
Please add as much of the following info as you can:

Title: Way Too Complicated

Type (film/tv show): TV show

Film or show in which it appears: Dinosaurs (Disney)

Is the parent film/show streaming anywhere? Disney+ I think

About when in the parent film/show does it appear? S02E04

Actual footage of the film/show can be seen (yes/no)? yes

https://www.youtube.com/watch?v=s834kh7MiSw

![waytoocomplicated](https://user-images.githubusercontent.com/13246236/129782732-185f877e-0842-481e-9cb9-41cfa1f53312.png)

**Comment by lynnandtonic** [comment]
Thank you! https://nestflix.fun/way-too-complicated/
