### ISSUE TITLE
Add Scratchtasia

### ISSUE THREAD

**Issue by ethanimation** [lynnandtonic/nestflix.fun#289]
Please add as much of the following info as you can:

Title: Scratchtasia

Type (film/tv show): Film

Film or show in which it appears: The Simpsons

Is the parent film/show streaming anywhere?
yes

About when in the parent film/show does it appear?
The Itchy and Scratchy Land

Actual footage of the film/show can be seen (yes/no)?
yes

![Scratchtasia](https://user-images.githubusercontent.com/88994668/129809970-2a460a8c-31f0-42cc-b236-301ebd810dc1.png)

**Comment by lynnandtonic** [comment]
It’s live! https://nestflix.fun/scratchtasia/

Thank you!!
