### ISSUE TITLE
Add Kidnapped by Danger: The Avery Jessup Story

### ISSUE THREAD

**Issue by artlung** [lynnandtonic/nestflix.fun#29]
Please add as much of the following info as you can:

Title: Kidnapped by Danger: The Avery Jessup Story

Type (film/tv show): tv movie

Film or show in which it appears: 30 Rock

Is the parent film/show streaming anywhere? Netflix

About when in the parent film/show does it appear? S06E14

Actual footage of the film/show can be seen (yes/no)? yes

**Comment by lynnandtonic** [comment]
It's live! https://nestflix.fun/kidnapped-by-danger-the-avery-jessup-story/

Thank you!
