### ISSUE TITLE
Add The Wondrous World of Whimsical Willy

### ISSUE THREAD

**Issue by ethanimation** [lynnandtonic/nestflix.fun#293]
Please add as much of the following info as you can:

Title: The Wondrous World of Whimsical Willy

Type (film/tv show): tv show

Film or show in which it appears: The Powerpuff Girls

Is the parent film/show streaming anywhere?
yes 

About when in the parent film/show does it appear?
Neighbor Hood

Actual footage of the film/show can be seen (yes/no)?
yes

![The_Wonderful_Whimsical_World_of_Whimsical_Willy_Theme_Song](https://user-images.githubusercontent.com/88994668/129814684-4e3e9f83-3697-4d80-8541-e233ec528088.png)
![Whimsical_Willy](https://user-images.githubusercontent.com/88994668/129814727-c6804a2d-7e82-4077-adfc-008cb0c93673.png)

https://powerpuffgirls.fandom.com/wiki/The_Wondrous_World_of_Whimsical_Willy

**Comment by lynnandtonic** [comment]
Thank you! https://nestflix.fun/the-wondrous-world-of-whimsical-willy/
