### ISSUE TITLE
Add: "Homicide: Life on Sesame Street"

### ISSUE THREAD

**Issue by TooniFNT** [lynnandtonic/nestflix.fun#294]
Please add as much of the following info as you can:

**Title:** Homicide: Life on Sesame Street

**Type (film/tv show):** TV Show / Crime Drama

**Film or show in which it appears:** Family Guy

**Is the parent film/show streaming anywhere?** Hulu.

**About when in the parent film/show does it appear?** In the episode "Mind Over Murder", during the second act, when Peter says that his favorite shows are "running together".

**Actual footage of the film/show can be seen (yes/no)?** Yes.

![vlcsnap-2021-08-17-20h16m52s822](https://user-images.githubusercontent.com/88996737/129817026-c66c22a3-1537-4b6e-a089-a58a9606abfc.png)
![vlcsnap-2021-08-17-20h16m58s343](https://user-images.githubusercontent.com/88996737/129817048-9a3f5d08-c330-453b-8849-fbb83af4d416.png)
![vlcsnap-2021-08-17-20h17m14s149](https://user-images.githubusercontent.com/88996737/129817063-69cbeea3-d450-4b59-aab9-d1d46ff5886c.png)
![vlcsnap-2021-08-17-20h17m26s068](https://user-images.githubusercontent.com/88996737/129817073-f4aee523-0313-49b0-bdeb-b757a14274ea.png)
![vlcsnap-2021-08-17-20h17m41s200](https://user-images.githubusercontent.com/88996737/129817081-7dc2f2aa-2d46-4c5e-b5cd-759a869ced2f.png)

**Comment by lynnandtonic** [comment]
This one is on the site: https://nestflix.fun/homicide-life-on-sesame-street/

Thank you!
