### ISSUE TITLE
Add Law and Order: Special Letters Unit

### ISSUE THREAD

**Issue by ethanimation** [lynnandtonic/nestflix.fun#296]
Please add as much of the following info as you can:

Title: Law and Order: Special Letters Unit

Type (film/tv show): tv show

Film or show in which it appears: Sesame Street

Is the parent film/show streaming anywhere?
yes

About when in the parent film/show does it appear?
Sesame Street Episode 4109

Actual footage of the film/show can be seen (yes/no)?
yes
![SLU_Logo JPG](https://user-images.githubusercontent.com/88994668/129819745-255ccef2-319e-4279-a26c-c535bfcc63c6.jpg)
![Speciallettersunit](https://user-images.githubusercontent.com/88994668/129819763-060fc4dc-9ef3-4ba9-a67d-e074337e7863.jpg)

**Comment by HarleysTwin** [comment]
I specifically asked, and movies from clip shows aren't eligible for submission. Since the shorts aren't connected to the _Sesame Street_ storyline, this would probably be considered that.

**Comment by lynnandtonic** [comment]
I’m considering this a sketch, so not going to include it for now. Thank you!
