### ISSUE TITLE
Add CHoPs

### ISSUE THREAD

**Issue by ethanimation** [lynnandtonic/nestflix.fun#298]
Please add as much of the following info as you can:

Title: CHoPs

Type (film/tv show): tv show

Film or show in which it appears: Planes: Fire & Rescue

Is the parent film/show streaming anywhere?
yes
About when in the parent film/show does it appear?
Planes: Fire & Rescue
Actual footage of the film/show can be seen (yes/no)?
yes

![Chops-header](https://user-images.githubusercontent.com/88994668/129831832-4adf3b5a-099e-4c55-9cbd-08e38c545d20.jpg)
![Blade_Plik5](https://user-images.githubusercontent.com/88994668/129831847-2b9e77af-fe7c-4bf3-9ba8-70a2f5ebafef.png)
![Гррррр JPG](https://user-images.githubusercontent.com/88994668/129831866-62fca4c0-5716-4e9d-a5e4-0a0d12f093f2.jpg)
![X240-fEq_Plik3](https://user-images.githubusercontent.com/88994668/129831878-f7e0fafb-171f-40ef-9783-fca459114be8.jpg)

https://disney.fandom.com/wiki/CHoPs

**Comment by lynnandtonic** [comment]
Thank you! https://nestflix.fun/chops/
