### ISSUE TITLE
Add Poppycock Palace

### ISSUE THREAD

**Issue by pranavkalrax** [lynnandtonic/nestflix.fun#299]
Please add as much of the following info as you can:

Title: Poppycock Palace

Type (film/tv show): TV Show

Film or show in which it appears: New Girl

Is the parent film/show streaming anywhere?: 
Yes, on Netflix

About when in the parent film/show does it appear?
Season 5, Episode 13 (Sam, Again)

Actual footage of the film/show can be seen (yes/no)?
Yes

**Comment by lynnandtonic** [comment]
Thank you! https://nestflix.fun/poppycock-palace/
