### ISSUE TITLE
Add "Lust Conquers All"

### ISSUE THREAD

**Issue by dbergey** [lynnandtonic/nestflix.fun#30]
Please add as much of the following info as you can:

Title: Lust Conquers All

Type (film/tv show): tv show

Film or show in which it appears: Ted Lasso

Is the parent film/show streaming anywhere? Apple TV+

About when in the parent film/show does it appear? Season 2 Episode 1

Actual footage of the film/show can be seen (yes/no)? yes

**Comment by lynnandtonic** [comment]
Thanks, @dbergey and @HarleysTwin! It’s on the site now: https://nestflix.fun/lust-conquers-all/
