### ISSUE TITLE
Add Countdown (The IT Crowd)

### ISSUE THREAD

**Issue by emstresh** [lynnandtonic/nestflix.fun#303]
Please add as much of the following info as you can:

Title: "Countdown"

Type (film/tv show): TV show (game show specifically)

Film or show in which it appears: The IT Crowd

Is the parent film/show streaming anywhere? Netflix

About when in the parent film/show does it appear? S4 E2 "The Final Countdown"

Actual footage of the film/show can be seen (yes/no)? Yes

**Comment by lynnandtonic** [comment]
I was told this is a real show in the UK! So I won’t be adding it, unfortunately. Thank you @emstresh!

**Comment by emstresh** [comment]
Oh my gosh! I had no idea, how funny.
