### ISSUE TITLE
Add "Ow, My Balls!" from Idiocracy

### ISSUE THREAD

**Issue by jimmiedave** [lynnandtonic/nestflix.fun#308]
Playing all the time on the big screen.

**Comment by lynnandtonic** [comment]
It’s on the site! https://nestflix.fun/ow-my-balls/

**Comment by jimmiedave** [comment]
Nice site, tho search needs a little help: searched for "ow, my balls!" before opening issue and it didn't come up. Maybe drop all punctuation in query. Thanks for doing the site!

**Comment by lynnandtonic** [comment]
Ah, thank you! Adding a small fix for this one and will look into that.
