### ISSUE TITLE
Add The Crows Have Eyes III: The Crowening

### ISSUE THREAD

**Issue by dbergey** [lynnandtonic/nestflix.fun#31]
Please add as much of the following info as you can:

Title: The Crows Have Eyes III: The Crowening

Type (film/tv show): film

Film or show in which it appears: Schitt's Creek

Is the parent film/show streaming anywhere? Netflix

About when in the parent film/show does it appear? Season 5 episode 1, final scene

Actual footage of the film/show can be seen (yes/no)? brief composited footage is shown on a studio display

**Comment by waxpancake** [comment]
It's in there already. https://nestflix.fun/the-crows-have-eyes-3/
