### ISSUE TITLE
Add Mirror, Father Mirror

### ISSUE THREAD

**Issue by Jefferson-House** [lynnandtonic/nestflix.fun#310]
Please add as much of the following info as you can:

Title: The Flower that Drank the Moon

Type (film/tv show): Film

Film or show in which it appears: Ghost World (2001)

Is the parent film/show streaming anywhere?
Yes (Pluto, Hulu, Amazon Prime, Vudu, among others).
About when in the parent film/show does it appear? 19:35

Actual footage of the film/show can be seen (yes/no)? Yes

**Comment by HarleysTwin** [comment]
These are screenshots from _Mirror, Father, Mirror_.  _The Flower that Drank the Moon_ is a different film.  (Also, _Ghost World_ is not streaming on Hulu.  It's streaming on Amazon Prime and Apple TV.)

Type: independant art film

A film by Roberta Allsworth

Made possible by donations from: 

- The Federation for the Advancement for Mature Women in the Arts
- The Struggling Artist Foundation
- The Why Not Me Project
- Mr. & Mrs. Theodore Allsworth
![Mirror, Father, Mirror 1](https://user-images.githubusercontent.com/88982629/180571389-6414c033-fa31-4629-91d4-a91032e51ea2.jpg)
![Mirror, Father, Mirror 2](https://user-images.githubusercontent.com/88982629/180571390-b13edfa6-f78f-40cd-9cf4-7cb151d153b7.jpg)
![Mirror, Father, Mirror 3](https://user-images.githubusercontent.com/88982629/180571391-06dbbcd1-7f75-4124-9412-66a93a6ffa59.jpg)
![Mirror, Father, Mirror 4](https://user-images.githubusercontent.com/88982629/180571393-9017131f-8fdb-40f7-9f73-e2a30a2682ac.jpg)
![Mirror, Father, Mirror 5](https://user-images.githubusercontent.com/88982629/180571394-763a53f5-06ef-4a1e-9469-b3fe2705ab56.jpg)
![Mirror, Father, Mirror 6](https://user-images.githubusercontent.com/88982629/180571395-abc87f19-fe7c-4dcb-b82e-a2b9273f7baf.jpg)

**Comment by HarleysTwin** [comment]
These are screenshots from Mirror, Father, Mirror. The Flower that Drank the Moon is a different film. (Also, Ghost World is not streaming on Hulu. It's streaming on Amazon Prime and Apple TV.)

Type: independant art film

A film by Roberta Allsworth

Made possible by donations from:

    The Federation for the Advancement for Mature Women in the Arts
    The Struggling Artist Foundation
    The Why Not Me Project
    Mr. & Mrs. Theodore Allsworth
![Mirror, Father, Mirror 1](https://user-images.githubusercontent.com/88982629/180571966-5ee94add-6d27-4d4d-930a-9cb36076526f.jpg)
![Mirror, Father, Mirror 2](https://user-images.githubusercontent.com/88982629/180571967-ba0e3e7b-9228-45a7-8f9a-b41864188868.jpg)
![Mirror, Father, Mirror 3](https://user-images.githubusercontent.com/88982629/180571972-dc6f3561-aded-4028-a05b-29b030ff126f.jpg)
![Mirror, Father, Mirror 4](https://user-images.githubusercontent.com/88982629/180571973-fdf72177-04f8-4424-bf94-015770aa7a06.jpg)
![Mirror, Father, Mirror 5](https://user-images.githubusercontent.com/88982629/180571975-a66e6a26-0b9d-4332-95c4-4d83369bef75.jpg)

**Comment by HarleysTwin** [comment]
![Mirror, Father, Mirror 6](https://user-images.githubusercontent.com/88982629/180572146-88952684-87fb-400e-bb25-a60c0180dd0b.jpg)

**Comment by lynnandtonic** [comment]
Thank you both! https://nestflix.fun/mirror-father-mirror/
