### ISSUE TITLE
Add The Rusty Venture Show

### ISSUE THREAD

**Issue by helioblast** [lynnandtonic/nestflix.fun#311]
Title:
The Rusty Venture Show

Type (film/tv show):
TV

Film or show in which it appears:
The Venture Bros.

Is the parent film/show streaming anywhere?
HBO Max.
There are also clips on the Adult Swim page: https://www.adultswim.com/videos/the-venture-bros

About when in the parent film/show does it appear?
Sporadically throughout the run. s3e11 "ORB" is probably the best source for images, @ 0:00 & 9:11.
(I have the Blu-Rays, and can do captures if needed.)

Actual footage of the film/show can be seen (yes/no)?
Yes

Summary:
The animated adventures of boy adventurer Rusty Venture and Team Venture.

Pull Quote:
"Brought to you by: smoking!"

Cast:
Rusty Venture, Dr. Jonas Venture, Kano, Hector, H.E.L.P.eR.

Studio:
Venture-Industries

Categories:
Adventure, Travel, Animation

Number of Seasons:
(Canonically it was a short run. 2 or 3, maybe?)

Content Rating:
TV-PG

**Comment by lynnandtonic** [comment]
Thank you! https://nestflix.fun/the-rusty-venture-show/
