### ISSUE TITLE
Add Ottoman Empire from Ducktales 2017

### ISSUE THREAD

**Issue by LetterKyew** [lynnandtonic/nestflix.fun#314]
Please add as much of the following info as you can:

Title: Ottoman Empire

Type (film/tv show): TV SHow

Film or show in which it appears: Ducktales 2017

Is the parent film/show streaming anywhere? Disney+

About when in the parent film/show does it appear? Throughout the series but first appearance is S1 E3.

Actual footage of the film/show can be seen (yes/no)? Yes

https://ducktales.fandom.com/wiki/Ottoman_Empire

**Comment by lynnandtonic** [comment]
This is a duplicate of #67, so closing this one. Thank you!
