### ISSUE TITLE
Add Darkwing Duck from Ducktales 2017

### ISSUE THREAD

**Issue by LetterKyew** [lynnandtonic/nestflix.fun#315]
Please add as much of the following info as you can:

Title: Darkwing Duck

Type (film/tv show): TV Show

Film or show in which it appears: Ducktales 2017

Is the parent film/show streaming anywhere? Disney+

About when in the parent film/show does it appear? Throughout the show but the first appearance is S1 E11

Actual footage of the film/show can be seen (yes/no)? Yes.

https://ducktales.fandom.com/wiki/Darkwing_Duck_(TV_show)

**Comment by lynnandtonic** [comment]
Thank you, @LetterKyew! It’s now on the site: https://nestflix.fun/darkwing-duck/

I also added Darkwing: First Darkness https://nestflix.fun/darkwing-first-darkness/
