### ISSUE TITLE
Add Mermaid Man and Barnacle Boy From SpongeBob SquarePants

### ISSUE THREAD

**Issue by ronaldohoch** [lynnandtonic/nestflix.fun#318]
Took from wikipedia: 

> Mermaid Man and Barnacle Boy are semi-retired superheroes in the fictional city of Bikini Bottom. They are among the few humans who can breathe underwater and speak to the inhabitants of Bikini Bottom. Within the show's fictional universe, they are real superheroes. In addition to fighting crime, the duo has been extensively franchised throughout Bikini Bottom, including the television series The Adventures of Mermaid Man and Barnacle Boy,[1] a long-running comic book series, trading cards, and kids' meals at the Krusty Krab. Mermaid Man and Barnacle Boy currently reside at Shady Shoals Retirement Home. However, their two biggest fans, SpongeBob SquarePants and Patrick Star, convince them to come out of retirement in their first appearance.

Title: Mermaid Man and Barnacle Boy

Type (film/tv show): tv show

Film or show in which it appears: SpongeBob SquarePants

Is the parent film/show streaming anywhere? Netflix

About when in the parent film/show does it appear? Sorry, i don't know (https://en.wikipedia.org/wiki/Mermaid_Man_and_Barnacle_Boy)

Actual footage of the film/show can be seen (yes/no)? Yes

**Comment by lynnandtonic** [comment]
It’s on the site! https://nestflix.fun/mermaid-man-and-barnacle-boy/

Thank you!
