### ISSUE TITLE
Add Hockey High

### ISSUE THREAD

**Issue by aaronshekey** [lynnandtonic/nestflix.fun#32]
Please add as much of the following info as you can:

Title: Hockey High

Type (film/tv show): Film

Film or show in which it appears: Brigsby Bear

Is the parent film/show streaming anywhere? https://www.justwatch.com/us/movie/brigsby-bear

About when in the parent film/show does it appear? 25:00

Actual footage of the film/show can be seen (yes/no)? Yes

**Comment by lynnandtonic** [comment]
It’s up! https://nestflix.fun/hockey-high/

Thank you!

**Comment by aaronshekey** [comment]
Wow, I filed this for myself, mostly. Didn't expect you to get to it! You are INCREDIBLE. This site is INCREDIBLE.

**Comment by lynnandtonic** [comment]
Thank you so so much!
