### ISSUE TITLE
Add  See You Next Wednesday

### ISSUE THREAD

**Issue by kirkaracha** [lynnandtonic/nestflix.fun#321]
Please add as much of the following info as you can:

Title:
 See You Next Wednesday

Type (film/tv show):
Film

Film or show in which it appears:
An American Werewolf in London

Is the parent film/show streaming anywhere?
Yes

About when in the parent film/show does it appear?
Towards the end.

Actual footage of the film/show can be seen (yes/no)?
Yes.

https://www.youtube.com/watch?v=q6_w7aa9MHI

**Comment by HarleysTwin** [comment]
There may be other movies "See You Next Wednesday" has clips in.  It's a reoccurring gag that John Landis puts in so many of his movies.

**Comment by lynnandtonic** [comment]
It’s on the site! https://nestflix.fun/see-you-next-wednesday/

Not a lot of useable footage, unfortunatley!
