### ISSUE TITLE
Add Garth Marenghi's Darkplace

### ISSUE THREAD

**Issue by youennmerel** [lynnandtonic/nestflix.fun#322]
"Darkplace is presented as a lost classic: a television series produced in the 1980s, though not broadcast at the time (except in Peru). The presentation features commentary from many of the "original" cast, where characters such as Marenghi and Learner reflect on making the show." (https://en.wikipedia.org/wiki/Garth_Marenghi%27s_Darkplace)

Title:
Garth Marenghi's Darkplace

Type (film/tv show):
TV Show

Film or show in which it appears:
Garth Marenghi's Darkplace

Is the parent film/show streaming anywhere?
Channel 4 : https://www.channel4.com/programmes/garth-marenghis-darkplace

About when in the parent film/show does it appear?
Every episode

Actual footage of the film/show can be seen (yes/no)?
yes

https://www.youtube.com/watch?v=yk0qGq7P3lM

**Comment by lynnandtonic** [comment]
Thank you! https://nestflix.fun/garth-marenghis-darkplace/
