### ISSUE TITLE
Add Playback Time from  Mr. Bean's Holiday

### ISSUE THREAD

**Issue by alfasst** [lynnandtonic/nestflix.fun#324]
Please add as much of the following info as you can:

Title: Playback Time

Type (film/tv show): film

Film or show in which it appears: Mr. Bean's Holiday

Is the parent film/show streaming anywhere? Yes. Check: https://letterboxd.com/film/mr-beans-holiday/

About when in the parent film/show does it appear? Don't know exactly

Actual footage of the film/show can be seen (yes/no)? yes

**Comment by lynnandtonic** [comment]
Thank you! https://nestflix.fun/playback-time/
