### ISSUE TITLE
Add Lyman's Boys

### ISSUE THREAD

**Issue by raccoonskull** [lynnandtonic/nestflix.fun#328]
Please add as much of the following info as you can:

Title: Lyman's Boys

Type (film/tv show):
Show

Film or show in which it appears:
Episodes

You have Pucks from Episodes...but you don't have Lyman's Boys, the fictional British show that the fictional American show is based on! 

Is the parent film/show streaming anywhere?
Netflix 

About when in the parent film/show does it appear?
First couple episodes

Actual footage of the film/show can be seen (yes/no)?
Yes

**Comment by lynnandtonic** [comment]
@raccoonskull I can’t seem to find where the clips of Lyman’s Boys are shown. Would you mind finding the exact episodes? That would help a lot!

**Comment by raccoonskull** [comment]
Oh my gosh, I’m so sorry on this one. I thought it had a scene but my brain replaced my memory of the audition reading with the Lyman’s Boys actor Richard Griffiths as an actual clip. My apologies for submitting without double checking. You could use that (ep 1) or junk the submission. 

Sent from my mobile device.

On Aug 22, 2021, at 6:36 AM, Lynn Fisher ***@***.***> wrote:

﻿
@raccoonskull I can’t seem to find where the clips of Lyman’s Boys are shown. Would you mind finding the exact episodes? That would help a lot!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lynnandtonic** [comment]
Ah ok! No problem at all by the way, my brain did that with a bunch of these. 😄 Going to close this one for now, but thank you so much for submitting!

**Comment by raccoonskull** [comment]
Again, sorry! If you set up a Patreon for this project, let me know. I'd
definitely contribute!
