### ISSUE TITLE
Add 21-12 Time Attack: Directors Cut

### ISSUE THREAD

**Issue by theEpicjosh** [lynnandtonic/nestflix.fun#337]
**Title**: 21-12 Time Attack: Directors Cut

**Type (film/tv show):** Film (_director's cut_)

**Show in which it appears:** Regular Show on Cartoon Network

**Is the parent show streaming anywhere?**: Might be on Apple TV

**About when in the parent film/show does it appear?**: In Season 4 Episode 30: The Last Laserdisc Player

**Actual footage of the film/show can be seen?:** Yes. Near the end of the episode. You can also see remaining duration.

**Comment by lynnandtonic** [comment]
Thank you! https://nestflix.fun/21-12-time-attack/
