### ISSUE TITLE
The Adventure of Nathaniel and Isabel from Six Feet Under

### ISSUE THREAD

**Issue by RabbitInTheCity** [lynnandtonic/nestflix.fun#339]
Please add as much of the following info as you can:

Title: The Adventure of Nathaniel and Isabel

Type (film/tv show): tv show

Film or show in which it appears: Six Feet Under

Is the parent film/show streaming anywhere? HBO MAX, Hulu.

About when in the parent film/show does it appear? Season 3 Episode 10 (~19:00 and ~28:00)

Actual footage of the film/show can be seen (yes/no)? yes

**Comment by lynnandtonic** [comment]
Thank you! https://nestflix.fun/the-adventures-of-nathaniel-and-isabel/
