### ISSUE TITLE
Add Special Someone

### ISSUE THREAD

**Issue by aaronshekey** [lynnandtonic/nestflix.fun#34]
Title: Special Someone

Type (film/tv show): Film

Film or show in which it appears: Don Jon

Is the parent film/show streaming anywhere? https://www.justwatch.com/us/movie/don-jon

About when in the parent film/show does it appear? 18:00

Actual footage of the film/show can be seen (yes/no)? Yes

**Comment by lynnandtonic** [comment]
It‘s live! https://nestflix.fun/special-someone/

Thank you!!
