### ISSUE TITLE
Site social media info could use fixin'

### ISSUE THREAD

**Issue by rcharbon** [lynnandtonic/nestflix.fun#340]
For example, Facebook sees a bad HTTP response code and shows a 404 in your timeline when you share the home page:
https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Fnestflix.fun%2F

Happy to fix it myself if given access.

**Comment by lynnandtonic** [comment]
Thank you @rcharbon! Saw someone else mention that on Twitter but never followed up. Good catch! Should be fixed now.
