### ISSUE TITLE
Add Daddy's Boy!

### ISSUE THREAD

**Issue by HarleysTwin** [lynnandtonic/nestflix.fun#343]
Please add as much of the following info as you can:

Title: Daddy's Boy!

Type (film/tv show): Film - classic musical

Film or show in which it appears: The Unbreakable Kimmy Schmidt

Is the parent film/show streaming anywhere? Yes - Netflix

About when in the parent film/show does it appear?  The very end of episode 1x10: "Kimmy's in a Love Triangle!"

Actual footage of the film/show can be seen (yes/no)? Yes.  (It's shown being concluded and then re-introduced as part of "Turner Classic Movies.")

Presented by: Harrison von Harrison Jr.

Cast: Reginald von Bodem, James Alphonso Estep, Eugenia Mulford, Thom von Finland, Cracker the Dog, and introducing Jefferson Mays

Production Company: A Radio Picture

Release date: 1938

Fun Fact: The film ended mid-song as the crew refused to continue working on the production.

**Comment by lynnandtonic** [comment]
It’s live! https://nestflix.fun/daddys-boy/

Thank you for such good info!
