### ISSUE TITLE
Question about Titles in Sketch Shows

### ISSUE THREAD

**Issue by HarleysTwin** [lynnandtonic/nestflix.fun#344]
Do you only want submissions that are part of a narrative TV and film, or are sketch/skit shows also fair game?  Like, is it okay to find movie/TV parodies that are in shows like _Saturday Night Live_, and aren't part of a main narrative?

**Comment by lynnandtonic** [comment]
Thanks for asking! No sketch shows right now please. I’ll be updating the contribution guidelines here in a bit.

**Comment by HarleysTwin** [comment]
@lynnandtonic Does that also apply to movies?  Like, _The Kentucky Fried Movie_ is made up of different sketches, but it's a movie.
