### ISSUE TITLE
Add Music Hell from “We are Little Zombies” (Screenshots and Title Card Added)

### ISSUE THREAD

**Issue by HarleysTwin** [lynnandtonic/nestflix.fun#345]
Please add as much of the following info as you can:

Title: Music Hell

Type (film/tv show): TV show - entertainment commentary (music like MTV shows)

Film or show in which it appears: We Are Little Zombies

Is the parent film/show streaming anywhere? Yes - Amazon Prime

About when in the parent film/show does it appear? probably about halfway

Actual footage of the film/show can be seen (yes/no)? Yes - You can see a little bit of it in the trailer.  It leads into the band, Little Zombies', music video. https://youtu.be/obstTJVi3cE?t=74

**Comment by HarleysTwin** [comment]
![Music Hell 1](https://user-images.githubusercontent.com/88982629/180573752-288e4784-0ed0-497e-ab57-8ee905108f18.jpg)
![Music Hell 2](https://user-images.githubusercontent.com/88982629/180573754-7b46eb44-adb5-455f-9d4c-27a76bf1c435.jpg)
![Music Hell Title Card](https://user-images.githubusercontent.com/88982629/180573755-0a2b89cd-d643-449d-8385-127a0710471a.jpg)

**Comment by HarleysTwin** [comment]
![Music Hell 1](https://user-images.githubusercontent.com/88982629/180573935-c60b9b09-2db7-42ed-af75-b6d48d4df872.jpg)
![Music Hell 2](https://user-images.githubusercontent.com/88982629/180573938-a78cb895-fb2b-4b37-8079-5870b6d41bdd.jpg)
![Music Hell Title Card](https://user-images.githubusercontent.com/88982629/180573940-35597a35-6512-4579-8a2c-36b71753a8f9.jpg)

**Comment by HarleysTwin** [comment]
Oops.  Missed one.
![Music Hell](https://user-images.githubusercontent.com/88982629/180574282-e8908649-f83b-4e21-b335-0002752158b3.jpg)

**Comment by lynnandtonic** [comment]
Thank you!! https://nestflix.fun/music-hell/
