### ISSUE TITLE
Add The Gout Lovers from “Mystic Pop-Up Bar” (Screenshots and Poster Added)

### ISSUE THREAD

**Issue by HarleysTwin** [lynnandtonic/nestflix.fun#347]
Please add as much of the following info as you can:

Title: The Gout Lovers

Type (film/tv show): Film - romantic drama (foreign - Korean)

Film or show in which it appears: Mystic Pop-Up Bar

Is the parent film/show streaming anywhere? Yes - Netflix

About when in the parent film/show does it appear? starting midway through episode 1x06

Actual footage of the film/show can be seen (yes/no)? Yes - starting at 33:30 until 35:53

Tagline: Why does love have to hurt the closer we get?

Synopsis (written by me): Two young lovers are forced to face the crossroads of their relationship, as the thing that brought them together is the very thing that’s keeping them apart: their severe gout.

***ETA: Reddit says the cast is: Yoon Park and Ha Si-eun.

**Comment by HarleysTwin** [comment]
![The Gout Lovers 1](https://user-images.githubusercontent.com/88982629/179855614-42c860ce-b761-46e1-9b8b-7eff2617cc85.jpg)
![The Gout Lovers 2](https://user-images.githubusercontent.com/88982629/179855616-2569b70b-3a6f-4774-a026-cda8297fcfd6.jpg)
![The Gout Lovers 3](https://user-images.githubusercontent.com/88982629/179855617-9f9e60aa-6ee9-4e22-be23-758976e2487d.jpg)
![The Gout Lovers 4](https://user-images.githubusercontent.com/88982629/179855618-d1ef09eb-af8b-4fc0-b75e-8b3449a92dde.jpg)
![The Gout Lovers 5](https://user-images.githubusercontent.com/88982629/179855620-d5580b1d-9aff-469c-80ae-380a8cefd9fb.jpg)
![The Gout Lovers 6](https://user-images.githubusercontent.com/88982629/179855622-8d6f0bf9-18f1-4ba5-bf52-55da01fbebb5.jpg)
![The Gout Lovers 7](https://user-images.githubusercontent.com/88982629/179855624-333a81f2-4759-47f7-a8a2-d38981f186d0.jpg)
![The Gout Lovers 8](https://user-images.githubusercontent.com/88982629/179855625-03256bbf-635d-41c8-80c2-10d5bc7f7bcf.jpg)
![The Gout Lovers 9](https://user-images.githubusercontent.com/88982629/179855629-130f9435-009c-4f1d-b33d-677b486c776b.jpg)
![The Gout Lovers 10](https://user-images.githubusercontent.com/88982629/179855631-df48ef25-4f69-4741-b8ea-c8c347e02fe1.jpg)
![The Gout Lovers 11](https://user-images.githubusercontent.com/88982629/179855633-6df28fb6-9515-4693-a042-0c73c7c7cca8.jpg)
![The Gout Lovers 12](https://user-images.githubusercontent.com/88982629/179855635-280dfcf4-4657-41d4-8dc4-004b8d306f0a.jpg)
![The Gout Lovers 13](https://user-images.githubusercontent.com/88982629/179855636-bde71052-dba8-448a-b752-3ea7e0a62ed7.jpg)
![The Gout Lovers 15](https://user-images.githubusercontent.com/88982629/179855639-9bd235bb-4800-411e-aa99-f158b1a16f28.jpg)
![The Gout Lovers 16](https://user-images.githubusercontent.com/88982629/179855640-ee4e4a40-fa33-4167-9de5-3d5ddc7c1783.jpg)
![The Gout Lovers Poster](https://user-images.githubusercontent.com/88982629/179855643-09c5df08-74ac-43c7-aec9-611bc6452f07.jpg)

**Comment by lynnandtonic** [comment]
Thank you so much! The screenshots helped a ton! https://nestflix.fun/gout-lovers/
