### ISSUE TITLE
Add Olympus: The Gods' House from “Reality Z”

### ISSUE THREAD

**Issue by HarleysTwin** [lynnandtonic/nestflix.fun#348]
Please add as much of the following info as you can:

Title: Olympus: The Gods' House

Type (film/tv show): TV show - reality (foreign - Brazilian)

Film or show in which it appears: Reality Z

Is the parent film/show streaming anywhere? Yes - Netflix

About when in the parent film/show does it appear? Peppered throughout the first episode starting within the first five minutes up until about 18:00.

Actual footage of the film/show can be seen (yes/no)? Yes

Synopsis (written by me): Similar to the hit reality show, _Big Brother_, seven mortals must live together as Greek gods competing to see who gets to gain Zeus' (and the audience's) approval to ultimately stay on Mount Olympus.  

Director: Brandão

Cast: Divina McCall (host), Jessica (Aphrodite), Marcos (Apollo), Augusto (Ares), Veronica (Athena), Cleide (Demeter), Madonna (Dionysus), TK (Hermes), and Brandão as the Voice of Zeus

**Comment by HarleysTwin** [comment]
![Olympus The Gods House 1](https://user-images.githubusercontent.com/88982629/180070261-97effe40-5678-4d67-b5ee-6c5e9a2eafb3.jpg)
![Olympus The Gods House 2](https://user-images.githubusercontent.com/88982629/180070265-cc282d69-b03d-4e6d-8a6a-d62febaada02.jpg)
![Olympus The Gods House 3](https://user-images.githubusercontent.com/88982629/180070270-694b4fcf-de1a-410f-87c8-154df6f6d03d.jpg)
![Olympus The Gods House 4](https://user-images.githubusercontent.com/88982629/180070271-320aff89-8ee9-4dec-a516-5cf217d2ae8b.jpg)
![Olympus The Gods House 5](https://user-images.githubusercontent.com/88982629/180070272-2fbcbb52-f648-4e3f-bdf6-729e322867e2.jpg)
![Olympus The Gods House 6](https://user-images.githubusercontent.com/88982629/180070275-27c76140-1615-4ad5-84a5-06e966bd63d0.jpg)
![Olympus The Gods House 7](https://user-images.githubusercontent.com/88982629/180070276-b2c55f03-50d5-4f7a-83a7-0a8bea907f9c.jpg)
![Olympus The Gods House 8](https://user-images.githubusercontent.com/88982629/180070280-560051ee-d9d1-4d64-82ba-247f20344bf4.jpg)
![Olympus The Gods House 9](https://user-images.githubusercontent.com/88982629/180070282-5353f2a2-c930-4ea0-bb51-7c8e63a64af1.jpg)
![Olympus The Gods House 10](https://user-images.githubusercontent.com/88982629/180070284-7c4a0e60-46e8-4e11-b3c6-54ec6116b714.jpg)
![Olympus The Gods House 11](https://user-images.githubusercontent.com/88982629/180070285-b94652d2-e830-4d47-9e27-3cc527b94337.jpg)
![Olympus The Gods House 12](https://user-images.githubusercontent.com/88982629/180070287-66ce93ec-1239-4455-a67a-184c54b9d98b.jpg)
![Olympus The Gods House 13](https://user-images.githubusercontent.com/88982629/180070289-6ebb1b85-4cb4-4b7f-b444-2c517e47f960.jpg)
![Olympus The Gods House 14](https://user-images.githubusercontent.com/88982629/180070290-94758438-6796-420c-b69d-c302efbd99e2.jpg)
![Olympus The Gods House 15](https://user-images.githubusercontent.com/88982629/180070293-7d61b02b-3f84-449b-88b1-1e13917b7345.jpg)
![Olympus The Gods House 16](https://user-images.githubusercontent.com/88982629/180070295-828d65a3-f8b8-44d2-b0d5-62040979eebf.jpg)
![Olympus The Gods House 17](https://user-images.githubusercontent.com/88982629/180070296-58d4caab-76ab-417a-ad1e-4861b5ceacc9.jpg)
![Olympus The Gods House 18](https://user-images.githubusercontent.com/88982629/180070298-2ce51235-f40a-4765-a221-2510aa041144.jpg)
![Olympus The Gods House 19](https://user-images.githubusercontent.com/88982629/180070300-a464115a-a902-4b4c-abc2-ccb100a45355.jpg)
![Olympus The Gods House 20](https://user-images.githubusercontent.com/88982629/180070301-851ff47a-c645-412e-83fd-779089338c6b.jpg)

**Comment by HarleysTwin** [comment]
To make up for the photo that has the time bar on it.
![Olympus The Gods House](https://user-images.githubusercontent.com/88982629/180072513-15efc089-d417-46aa-811a-b68df9c8dd70.jpg)

**Comment by HarleysTwin** [comment]
Oops.  I did it twice.
![Olympus The Gods House](https://user-images.githubusercontent.com/88982629/180072916-5ed39c37-7a54-4aef-be3b-6b2d0eea2efb.png)

**Comment by lynnandtonic** [comment]
Thank you so much! https://nestflix.fun/olimpo-a-casa-dos-deuses/
