### ISSUE TITLE
Apostrophes don't work in search

### ISSUE THREAD

**Issue by waxpancake** [lynnandtonic/nestflix.fun#35]
**Describe the bug**
Searching for titles with apostrophes doesn't return the matching search results.

Example: Try searching for "It's Not My Problem".

Works:
https://nestflix.fun/search?search=not+my+problem

Doesn't work:
https://nestflix.fun/search?search=it%27s+not+my+problem

**Comment by lynnandtonic** [comment]
@waxpancake Ah good catch. Straight vs. curly I imagine. Looking into it!

**Comment by lynnandtonic** [comment]
I think should be good now! Thanks, @waxpancake!
