### ISSUE TITLE
Add American Dreamz

### ISSUE THREAD

**Issue by LetterKyew** [lynnandtonic/nestflix.fun#355]
Please add as much of the following info as you can:

Title: American Dreamz

Type (film/tv show): reality TV show 

Film or show in which it appears: American Dreamz (movie)

Is the parent film/show streaming anywhere? Don't know.

About when in the parent film/show does it appear? All throughout.

Actual footage of the film/show can be seen (yes/no)? Yes.
https://m.imdb.com/title/tt0465142/

**Comment by lynnandtonic** [comment]
Thank you! https://nestflix.fun/american-dreamz/
