### ISSUE TITLE
Add Up Late with Miss Piggy

### ISSUE THREAD

**Issue by monoverde** [lynnandtonic/nestflix.fun#356]
Please add as much of the following info as you can:

Title: Up Late with Miss Piggy - 

Type: tv show -  

ABC's The Muppets (2015)

Is the parent film/show streaming anywhere? Disney Plus

The series follows the characters behind the scenes who work on Miss Piggy's late night talk show.

About when in the parent film/show does it appear? Various throughout

Actual footage of the film/show can be seen (yes/no)?  yes.

**Comment by lynnandtonic** [comment]
Thank you! https://nestflix.fun/up-late-with-miss-piggy/
