### ISSUE TITLE
Question about Sketch Movies

### ISSUE THREAD

**Issue by HarleysTwin** [lynnandtonic/nestflix.fun#358]
So I know you don't want to use sketches from non-lineral TV shows like _Saturday Night Live_.  Would the same apply to a movie that isn't narrative driven?  Like the trailers in _The Kentucky Fried Movie_ or _Amazon Women on the Moon_/?  They're movies, but they're made up of skits.  Would it count because it's self contained, or does it fall under the 'no skit show' category?

**Comment by lynnandtonic** [comment]
I haven’t excluded them completely, but yeah similar situation. I might come around to them at the end, but my list is really long so I might not.
