### ISSUE TITLE
Add: Tales of the Old Testament

### ISSUE THREAD

**Issue by TooniFNT** [lynnandtonic/nestflix.fun#359]
Please add as much of the following info as you can:

**Title:** Tales of the Old Testament

**Type (film/tv show):** Film

**Film or show in which it appears:** The Simpsons (1989-present)

**Is the parent film/show streaming anywhere?** Disney+

**About when in the parent film/show does it appear?** In the episode "Homer and Ned's Hail Mary Pass", around 00:11:42. 

**Actual footage of the film/show can be seen (yes/no)?** Yes.

**Comment by lynnandtonic** [comment]
Thank you! https://nestflix.fun/tales-of-the-old-testament/
