### ISSUE TITLE
Add Batgirl from “Batman: The Brave and the Bold” (Screenshots and Title Card Added)

### ISSUE THREAD

**Issue by HarleysTwin** [lynnandtonic/nestflix.fun#362]
Please add as much of the following info as you can:

Title: Batgirl

Type (film/tv show): TV show - CGI cartoon superhero action

Film or show in which it appears: Batman: The Brave and the Bold

Is the parent film/show streaming anywhere? Yes - Amazon Prime & HBO Max

About when in the parent film/show does it appear? I believe near the end in the series finale, ep. 3x13 - "Mitefall!"

Actual footage of the film/show can be seen (yes/no)? Yes.  Batmite is watching it.

Tagline: It's a Caped Crusader like you've never seen before.  And this time, he's a girl!

Production Company: Warner Bros. Animation

**Comment by lynnandtonic** [comment]
Thank you so much! https://nestflix.fun/batgirl/
