### ISSUE TITLE
Add [Reality Bites]

### ISSUE THREAD

**Issue by Bes1208** [lynnandtonic/nestflix.fun#364]
Please add as much of the following info as you can:

Title: Reality Bites

Type (film/tv show): show

Film or show in which it appears: Reality Bites

Is the parent film/show streaming anywhere? 

About when in the parent film/show does it appear? Toward the end when Ben Stillers character shows Winona Ryder’s character the new show from her footage. 

Actual footage of the film/show can be seen (yes/no)? Yes through the whole film.

**Comment by lynnandtonic** [comment]
Thank you! https://nestflix.fun/reality-bites/
