### ISSUE TITLE
Add The French Mistake from “Blazing Saddles”

### ISSUE THREAD

**Issue by HarleysTwin** [lynnandtonic/nestflix.fun#365]
Please add as much of the following info as you can:

Title: The French Mistake

Type (film/tv show): Film - classic musical

Film or show in which it appears: Blazing Saddles

Is the parent film/show streaming anywhere? Yes - Hulu & Showtime

About when in the parent film/show does it appear? About 3/4ths in.  During a meta moment, while filming a song and dance number, the cast of _Blazing Saddles_ breaks onto their set.

Actual footage of the film/show can be seen (yes/no)? Yes, though intercut with a director rehearsal. - https://www.youtube.com/watch?v=JMK6lzmSk2o

**Comment by lynnandtonic** [comment]
I don't think I'm going to add this one right now since it's just the one scene being shot. Thank you!
