### ISSUE TITLE
Add Sandy Passage from “Documentary Now!”

### ISSUE THREAD

**Issue by HarleysTwin** [lynnandtonic/nestflix.fun#366]
Please add as much of the following info as you can:

Title: Sandy Passage

Type (film/tv show): Film - documentary

Film or show in which it appears: Documentary Now!

Is the parent film/show streaming anywhere? Yes - Netflix

About when in the parent film/show does it appear? It's the majority of episode 1x01.

Actual footage of the film/show can be seen (yes/no)? Yes - It's the majority of the footage.

Documentarians: Larry Fein, Abraham "Alfred" Fein

Documentary participants: Vivienne "Big Vivvy" van Kimpton, Vivienne "Little Vivvy" van Kimpton, David ???, Barry ???

Production Company: A Fein Brothers' Film

Copyright 1975, Kurwa Films, Inc.  (It also says Salus Films at the beginning of the film, which I think may be the distributor, but I'm not sure.)

**Comment by lynnandtonic** [comment]
Not going to add Documentary Now titles at the moment. Thank you!
