### ISSUE TITLE
Add Roscoe

### ISSUE THREAD

**Issue by olavgm** [lynnandtonic/nestflix.fun#368]
Please add as much of the following info as you can:

Title:
Roscoe.

Type (film/tv show):
TV show.

Film or show in which it appears:
Mythic Quest.

Is the parent film/show streaming anywhere? 
Apple TV+

About when in the parent film/show does it appear?
Season 1, episode 8, around 20 minutes in.

Actual footage of the film/show can be seen (yes/no)?
Yes.

**Comment by lynnandtonic** [comment]
Thank you!! https://nestflix.fun/roscoe/
