### ISSUE TITLE
Add The Hunt for El Chingon from “Documentary Now!”

### ISSUE THREAD

**Issue by HarleysTwin** [lynnandtonic/nestflix.fun#369]
Please add as much of the following info as you can:

Title: The Hunt for El Chingon

Type (film/tv show): Web series - documentary

Film or show in which it appears: Documentary Now!

Is the parent film/show streaming anywhere? Yes - Netflix

About when in the parent film/show does it appear? It is the majority of episode 1x02.

Actual footage of the film/show can be seen (yes/no)? Yes.

Documentarians: Jameson Friend, John Sachs, Kyle Riley, Trevor Kenney, Bryce Bowen, Ty Dolla $ign, Lars Klegg, Denver McIver

Documentary participants: Manuel Bautista, Jill Koch, Alfonso Diaz, El Chingon

Production Company: DRONEZ 

Company Motto: 'Ballz to the wallz!'

**Comment by lynnandtonic** [comment]
Not going to add Documentary Now titles at the moment. Thank you!
