### ISSUE TITLE
Add Kunuk the Hunter from “Documentary Now!”

### ISSUE THREAD

**Issue by HarleysTwin** [lynnandtonic/nestflix.fun#371]
Please add as much of the following info as you can:

Title: Kunuk the Hunter

Type (film/tv show): Film - documentary

Film or show in which it appears: Documentary Now!

Is the parent film/show streaming anywhere? Yes - Netflix

About when in the parent film/show does it appear? Many of the black and white sections from the first third of episode 1x03, and a tiny bit before the end credits.

Actual footage of the film/show can be seen (yes/no)? Yes.

Producer: William H. Sebastian
,
Director: William H. Sebastian

Documentary participants: Kanuk, William H. Sebastian

Production companies: Imagelogique Pictures, Soeuers Rêvent Motion Picture Company

Release date: 1922

Fun Fact: Considered the first documentary.

**Comment by lynnandtonic** [comment]
Not going to add Documentary Now titles at the moment. Thank you!
