### ISSUE TITLE
Add Passing Train from “Documentary Now!”

### ISSUE THREAD

**Issue by HarleysTwin** [lynnandtonic/nestflix.fun#372]
Please add as much of the following info as you can:

Title: Passing Train

Type (film/tv show): Film - documentary

Film or show in which it appears: Documentary Now!

Is the parent film/show streaming anywhere? Yes - Netflix

About when in the parent film/show does it appear? From 3:30 - 3:39 in episode 1x03.

Actual footage of the film/show can be seen (yes/no)? Yes

Release date: 1919

**Comment by lynnandtonic** [comment]
Since Documentary Now is a mockumentary show and not technically a show-within-a-show, I’m not going to add titles from it for now. Thank you for the submission though!
