### ISSUE TITLE
Add The Bigweld Show from Robots (2005)

### ISSUE THREAD

**Issue by ethanimation** [lynnandtonic/nestflix.fun#373]
Please add as much of the following info as you can:

Title: The Bigweld Show

Type (film/tv show): tv show

Film or show in which it appears: Robots (2005)

Is the parent film/show streaming anywhere?
yes

About when in the parent film/show does it appear?
 Robots (2005) film

Actual footage of the film/show can be seen (yes/no)?
yes

**Comment by lynnandtonic** [comment]
Thank you! https://nestflix.fun/the-bigweld-show/
