### ISSUE TITLE
Add Kunuk Uncovered from “Documentary Now!”

### ISSUE THREAD

**Issue by HarleysTwin** [lynnandtonic/nestflix.fun#374]
Please add as much of the following info as you can:

Title: Kunuk Uncovered

Type (film/tv show): Film - documentary

Film or show in which it appears: Documentary Now!

Is the parent film/show streaming anywhere? Yes - Netflix

About when in the parent film/show does it appear? It is the majority of 1x03 (though many of the black and white sections during the first third of the documentary and a tiny bit at the end come from the (fake) documentary _Kunuk the Hunter_).

Actual footage of the film/show can be seen (yes/no)? Yes.

Documentary participants: Meredith Sebastian, Barnabas Scott, Aglatki Qamaniq, Marie Claudette, Alexander Krauss, William H. Sebastian (archival), Pipilok <credited as 'Kunuk'> (archival), Chacal (archival), Nuka (archival)

Release date: 1985

**Comment by lynnandtonic** [comment]
Not going to add Documentary Now titles at the moment. Thank you!
