### ISSUE TITLE
Add Kickpuncher III: The Final Kickening

### ISSUE THREAD

**Issue by sepehrm** [lynnandtonic/nestflix.fun#377]
Please add as much of the following info as you can:

Title: Kickpuncher III: The Final Kickening

Type: Film

Film or show in which it appears: Community TV Show

Is the parent film/show streaming anywhere? Netflix

About when in the parent film/show does it appear? Season Two

Actual footage of the film/show can be seen (yes/no)? No, a DVD is mentioned.

**Comment by HarleysTwin** [comment]
@sepehrm The criteria for submissions states "Must show actual footage (not just mentioned in dialogue or seen in a poster)."  Something that's just mentioned doesn't qualify.

**Comment by sepehrm** [comment]
Fair enough, thanks.
