### ISSUE TITLE
The Platypus and his girlfriend from Phineas & Ferb

### ISSUE THREAD

**Issue by Bagrecito** [lynnandtonic/nestflix.fun#379]
Please add as much of the following info as you can:

Title: The Platypus and his girlfriend

Type (film/tv show):TV show

Film or show in which it appears: Phineas & Ferb. Season 2, chapter 33

Is the parent film/show streaming anywhere? Disney Plus

About when in the parent film/show does it appear? At the end of chapter

Actual footage of the film/show can be seen (yes/no)? Yes

**Comment by lynnandtonic** [comment]
Thank you! https://nestflix.fun/the-platypus-and-his-girlfriend/
