### ISSUE TITLE
Caged Heat

### ISSUE THREAD

**Issue by pepeguama** [lynnandtonic/nestflix.fun#382]
Please add as much of the following info as you can:

Title: Caged Heat

Type (film/tv show): TV Show

Film or show in which it appears: All Hail the King (Marvel Short)

Is the parent film/show streaming anywhere? Yes

About when in the parent film/show does it appear? 6:10

Actual footage of the film/show can be seen (yes/no)? Yes

**Comment by lynnandtonic** [comment]
It‘s live! Thank you! https://nestflix.fun/caged-heat/
