### ISSUE TITLE
Add Zebras in America

### ISSUE THREAD

**Issue by gravygravel** [lynnandtonic/nestflix.fun#389]
Please add as much of the following info as you can:

Title: Zebras in America

Type (film/tv show): Film

Film or show in which it /appears: Freddie Got Fingered

Is the parent film/show streaming anywhere? I hope not

About when in the parent film/show does it appear? In the denouement 

Actual footage of the film/show can be seen (yes/no)? Yes

https://www.youtube.com/watch?v=PFEyFlRljss

**Comment by lynnandtonic** [comment]
Thank you! https://nestflix.fun/zebras-in-america/
