### ISSUE TITLE
Add Coffin Flop

### ISSUE THREAD

**Issue by pronoiac** [lynnandtonic/nestflix.fun#39]
Please add as much of the following info as you can:

Title: Coffin Flop

Type (film/tv show): TV show

Film or show in which it appears: I Think You Should Leave

Is the parent film/show streaming anywhere? Yes, on Netflix

About when in the parent film/show does it appear? Season 2, episode 1, first 5 minutes

Actual footage of the film/show can be seen (yes/no)? Yes

**Comment by lynnandtonic** [comment]
Ok I’ve waffled back and forth on this a whole bunch, but I don’t think I’m going to add this one for now. I might come back to this (and other sketch shows) later on.

Thank you!
