### ISSUE TITLE
Add To Serve and Protect

### ISSUE THREAD

**Issue by ancestral** [lynnandtonic/nestflix.fun#393]
Please add as much of the following info as you can:

Title: To Serve and Protect

Type (film/tv show): film

Film or show in which it appears: In & Out

Is the parent film/show streaming anywhere?
HBO/Prime Video

About when in the parent film/show does it appear?
Near the beginning of the movie, during the Academy Awards ceremony

Actual footage of the film/show can be seen (yes/no)?
yes

https://youtu.be/2QGIVOUsyLU

**Comment by lynnandtonic** [comment]
Thank you, @ancestral! https://nestflix.fun/to-serve-and-protect/
