### ISSUE TITLE
Add Bunny and Kitty

### ISSUE THREAD

**Issue by benbober** [lynnandtonic/nestflix.fun#394]
Please add as much of the following info as you can:

Title: Bunny and Kitty

Type (film/tv show): Tv show

Film or show in which it appears: Unbreakable Kimmy Schmidt

Is the parent film/show streaming anywhere? Netflix

About when in the parent film/show does it appear? S2 ep 4 (28'00)

Actual footage of the film/show can be seen (yes/no)? Yes

**Comment by lynnandtonic** [comment]
It’s live! https://nestflix.fun/bunny-and-kitty/

Thank you! 🐰🐱
