### ISSUE TITLE
Add Baby Fights

### ISSUE THREAD

**Issue by Shrinks99** [lynnandtonic/nestflix.fun#40]
Title: Baby Fights

Type (film/tv show): TV Show

Film or show in which it appears: Gravity Falls

Is the parent film/show streaming anywhere?: Yes!  Disney Plus

About when in the parent film/show does it appear?: Gravity Falls S01E16 @ 4:51

Actual footage of the film/show can be seen (yes/no)?: Yes... Though it's on a Television.  Should be able to isolate and make it look nice with a good screen capture and a little bit of colour correction though.
[
Wiki page](https://gravityfalls.fandom.com/wiki/Baby_Fights)

**Comment by lynnandtonic** [comment]
It’s live! https://nestflix.fun/baby-fights/

Thank you! 💃
