### ISSUE TITLE
Add Punch Teacher

### ISSUE THREAD

**Issue by DLu** [lynnandtonic/nestflix.fun#400]
Title: Punch Teacher

Type (film/tv show): tv show

Film or show in which it appears: The Muppets (2011)

Is the parent film/show streaming anywhere? Disney Plus

About when in the parent film/show does it appear? 41 minutes

Actual footage of the film/show can be seen (yes/no)? yes

**Comment by DLu** [comment]
![PunchTeacher1](https://user-images.githubusercontent.com/1016143/160306765-15bdbd40-92bb-400c-a424-bc756ca59082.png)
![PunchTeacher2](https://user-images.githubusercontent.com/1016143/160306766-7fc47df3-1636-4126-85ee-0875dcab512f.png)
![PunchTeacher3](https://user-images.githubusercontent.com/1016143/160306767-d5e81762-c725-4781-8ddf-dd61bdc8d4a9.png)
![PunchTeacher4](https://user-images.githubusercontent.com/1016143/160306768-ba805bca-c19b-498a-8424-d0229af01ac7.png)
![PunchTeacher5](https://user-images.githubusercontent.com/1016143/160306769-7cf2cd36-86cb-4249-b125-b7467e69b1be.png)

**Comment by lynnandtonic** [comment]
Thank you! https://nestflix.fun/punch-teacher/
