### ISSUE TITLE
Add Porkin' Across America

### ISSUE THREAD

**Issue by AdmiralAkbar1** [lynnandtonic/nestflix.fun#405]
Please add as much of the following info as you can:

Title: Porkin' Across America

Type (film/tv show): Food/lifestyle reality miniseries

Produced By: Onion Digital Studios 

Is the parent film/show streaming anywhere? https://www.youtube.com/watch?v=PwQns6vGfj4

About when in the parent film/show does it appear? It's fully available on its own

Actual footage of the film/show can be seen (yes/no)? Yes

Cast: Jim Haggerty, Tracy Gill

Not sure if you'd count this because it's by a comedy group (The Onion), but it's essentially an in-universe spinoff of one of their other parody shows (Today Now!). Your call.

**Comment by lynnandtonic** [comment]
This feels aligned but is a real show! So not going to add it to Nestflix. Thank you though!
