### ISSUE TITLE
Add Asbestos in Obstetrics

### ISSUE THREAD

**Issue by Dabeavis** [lynnandtonic/nestflix.fun#407]
Please add as much of the following info as you can:

Title: Asbestos in Obstetrics

Type (film/tv show): Drama TV Movie

Film or show in which it appears: Beavis & Butthead

Is the parent film/show streaming anywhere? Paramount+

About when in the parent film/show does it appear? Blackout! (S4,E11)

Actual footage of the film/show can be seen (yes/no)? Yes

**Comment by lynnandtonic** [comment]
Thank you! https://nestflix.fun/asbestos-in-obstetrics/
