### ISSUE TITLE
Add Ben from The Simpsons

### ISSUE THREAD

**Issue by LetterKyew** [lynnandtonic/nestflix.fun#412]
Please add as much of the following info as you can:

Title: Ben

Type (film/tv show): Daytime talk show.

Film or show in which it appears: The Simpsons Season 6 "Homer Badman"

Is the parent film/show streaming anywhere? Disney+

About when in the parent film/show does it appear? Season 6 episode 9 "Homer Badman", 13:16

Actual footage of the film/show can be seen (yes/no)? Yes

**Comment by lynnandtonic** [comment]
Thank you! https://nestflix.fun/ben/
