### ISSUE TITLE
Add Puppet Pals the Movie in 3-D

### ISSUE THREAD

**Issue by ethanimation** [lynnandtonic/nestflix.fun#418]
Please add as much of the following info as you can:

Title: Movie Puppet Pals the Movie in 3-D

Type (film/tv show): film

Film or show in which it appears: The Powerpuff Girls

Is the parent film/show streaming anywhere? HBO Max

About when in the parent film/show does it appear? yes

Actual footage of the film/show can be seen (yes/no)? yes

**Comment by lynnandtonic** [comment]
Thank you!! https://nestflix.fun/movie-puppet-pals-the-movie/
