### ISSUE TITLE
Add Knightboat: The Crime Solving Boat

### ISSUE THREAD

**Issue by Maximegalon** [lynnandtonic/nestflix.fun#42]
Please add as much of the following info as you can:

Title: Knightboat: The Crime Solving Boat

Type (film/tv show): TV

Film or show in which it appears: The Simpsons

Is the parent film/show streaming anywhere? Yes, Disney+

About when in the parent film/show does it appear? Within the first 5 minutes

Actual footage of the film/show can be seen (yes/no)? yes

Other info: https://www.youtube.com/watch?v=uoV1-fsFCmw

**Comment by lynnandtonic** [comment]
Thank you, @Maximegalon! https://nestflix.fun/knightboat-the-crime-solving-boat/
