### ISSUE TITLE
Add The Splattering from Locke & Key

### ISSUE THREAD

**Issue by jrr** [lynnandtonic/nestflix.fun#425]
Title: The Splatting

Type (film/tv show): Film

Film or show in which it appears: Locke & Key

Is the parent film/show streaming anywhere? [Netflix](https://www.netflix.com/title/80241239)

About when in the parent film/show does it appear? Season 2, episode 1, 31:15

Actual footage of the film/show can be seen (yes/no)?

I don't think the entirety of _The Splattering_ exists inside the containing show, but a much cleaner edit of it exists in an official promo for the TV show:

https://www.youtube.com/watch?v=etreLzo-i0s

**Comment by lynnandtonic** [comment]
Thank you! Finally got to this 😅 

https://nestflix.fun/the-splattering/
