### ISSUE TITLE
Add [pretty little liars]

### ISSUE THREAD

**Issue by andjelaqq** [lynnandtonic/nestflix.fun#433]
Please add as much of the following info as you can:

Title:

Type (film/tv show):

Film or show in which it appears:

Is the parent film/show streaming anywhere?

About when in the parent film/show does it appear?

Actual footage of the film/show can be seen (yes/no)?

**Comment by HarleysTwin** [comment]
Pretty Little Liars is an actual TV show, and, therefore, doesn't apply here.
