### ISSUE TITLE
Add Astronaut Dolphin Detective from Mr. Pickles

### ISSUE THREAD

**Issue by jonahharris** [lynnandtonic/nestflix.fun#437]
Please add as much of the following info as you can:

Title: Astronaut Dolphin Detective

Type (film/tv show): TV Show

Film or show in which it appears: Mr. Pickles

Is the parent film/show streaming anywhere? HBO Max

About when in the parent film/show does it appear? Several Episodes (Pilot, The Cheeseman, A.D.D.)

Actual footage of the film/show can be seen (yes/no)? Yes

**Comment by lynnandtonic** [comment]
Thank you! https://nestflix.fun/astronaut-dolphin-detective/
