### ISSUE TITLE
Add Terminal Beauty 3

### ISSUE THREAD

**Issue by HarleysTwin** [lynnandtonic/nestflix.fun#439]
Please add as much of the following info as you can:

Title: Terminal Beauty 3

Type (film/tv show): film - action/detective

Film or show in which it appears: The Boys

Is the parent film/show streaming anywhere? Yes - Amazon Prime

About when in the parent film/show does it appear? Ep. 1x05 - "Good for the Soul."  You can see the scenes from 24:10 - 24:33, 24:37 - 24:39 (though seen through a TV screen).

Actual footage of the film/show can be seen (yes/no)? Yes

Cast: Popclaw, Billy Zane

DVD back cover description: 'Popclaw shines as a razor-sharp private detective, unraveling a web of lies in the biggest case of her life.  Billy Zane plays a smooth-talking con man with too many secrets and a dark, mysterious past.  When these two find themselves caught up in a dangerous game of cat-and-mouse, all rules go out the window...'

**Comment by lynnandtonic** [comment]
Thank you! https://nestflix.fun/terminal-beauty-3/
