### ISSUE TITLE
Add Super in America

### ISSUE THREAD

**Issue by HarleysTwin** [lynnandtonic/nestflix.fun#440]
Please add as much of the following info as you can:

Title: Super in America

Type (film/tv show): reality TV show

Film or show in which it appears: The Boys

Is the parent film/show streaming anywhere? Yes - Amazon Prime

About when in the parent film/show does it appear? Throughout ep. 1x06; "The Innocents."  Timestamps: 0:15 - 0:52, 4:24- 5:53 (peppered with behind the scenes footage), 12:30 - 14:30 (peppered with behind the scenes footage), 34:57 - 35:29, 37:54 - 39:33 (peppered with behind the scenes footage).

Actual footage of the film/show can be seen (yes/no)? Yes

Production Company: Vought Studios

**Comment by lynnandtonic** [comment]
Thank you! https://nestflix.fun/super-in-america/
