### ISSUE TITLE
Add The Mesmerizer

### ISSUE THREAD

**Issue by HarleysTwin** [lynnandtonic/nestflix.fun#441]
Please add as much of the following info as you can:

Title: The Mesmerizer

Type (film/tv show): police procedural drama

Film or show in which it appears: The Boys

Is the parent film/show streaming anywhere? Yes - Amazon Prime

About when in the parent film/show does it appear? Ep. 1x06: "The Innocents." -> 25:08 - 25:28

Actual footage of the film/show can be seen (yes/no)? Yes

Cast: Mesmer as Lt. Howser

Catchphrase: "There are no secrets from me."

Factoid: "The Mesmerizer" was a critic's choice TV procedural that ran for three seasons in the 1990's.

**Comment by lynnandtonic** [comment]
Thanks again! https://nestflix.fun/the-mesmerizer/
