### ISSUE TITLE
Add A Closer Look with Chris Hansen from “The Boys”

### ISSUE THREAD

**Issue by HarleysTwin** [lynnandtonic/nestflix.fun#447]
Please add as much of the following info as you can:

Title: A Closer Look with Chris Hansen

Type (film/tv show): TV show - true crime documentary

Film or show in which it appears: The Boys

Is the parent film/show streaming anywhere? Yes - Amazon Prime

About when in the parent film/show does it appear? Episode 2x01 "The Big Ride"; Timestamps: 18:47 - 19:11,19:17 - 19:23,19:36 - 19:43

Actual footage of the film/show can be seen (yes/no)? Yes

Host: Chris Hansen

**Comment by lynnandtonic** [comment]
I'm not going to add this one right now. Thank you!
