### ISSUE TITLE
Add Take My Hand

### ISSUE THREAD

**Issue by Maximegalon** [lynnandtonic/nestflix.fun#45]
Please add as much of the following info as you can:

Title: Take my Hand

Type (film/tv show): Film

Film or show in which it appears:30 Rock

Is the parent film/show streaming anywhere? yes, netflix

About when in the parent film/show does it appear? 8:38, 12:34

Actual footage of the film/show can be seen (yes/no)? yes (the making of it)

As seen easily - https://www.dailymotion.com/video/x6i4mu8

**Comment by lynnandtonic** [comment]
It's live! https://nestflix.fun/take-my-hand/

Thank you!

**Comment by Maximegalon** [comment]
Thanks for much for doing all this!
