### ISSUE TITLE
Add The Crowned Queen from “Hotel del Luna” (Screenshots and Poster Added)

### ISSUE THREAD

**Issue by HarleysTwin** [lynnandtonic/nestflix.fun#452]
Please add as much of the following info as you can:

Title: The Crowned Queen

Type (film/tv show): TV show - historical drama (Korean)

Film or show in which it appears: Hotel del Luna

Is the parent film/show streaming anywhere? Yes - Netflix

About when in the parent film/show does it appear? Ep. 1x06: "Episode 6"

Actual footage of the film/show can be seen (yes/no)? Yes; Time stamps: 30:48 - 31:47, 49:04 - 50:06, 50:51 - 51:33 (Second half of last clip intersperced with reactions of person watching it.)

Synopsis: A queen hires a kisaeng who looks similar to take her place in the palace in order to stay safe. 

Starring: Yu O as King Yi Hyeon

Production Company: tvM

Fun Fact: Yu O was cast to take over the role of Yi Hyeon when the original actor, Bang Tae-u, died of cardiac arrest during a workout before filming began.  This would have been Bang's first leading role.

**Comment by HarleysTwin** [comment]
![The Crowned Queen 1](https://user-images.githubusercontent.com/88982629/180023822-726e9b36-844c-4700-96eb-b039a094f494.jpg)
![The Crowned Queen 2](https://user-images.githubusercontent.com/88982629/180023823-b4e4ae75-0f3a-4c93-aafe-93ffeee84c6d.jpg)
![The Crowned Queen 3](https://user-images.githubusercontent.com/88982629/180023826-08b790d3-2c18-4d3e-9831-d048185eddd4.jpg)
![The Crowned Queen 4](https://user-images.githubusercontent.com/88982629/180023827-8d7a0ab9-314f-4be8-aa37-b0ca02f47f55.jpg)
![The Crowned Queen 5](https://user-images.githubusercontent.com/88982629/180023829-bf0e4731-0b7d-4941-9c8f-22f840502e48.jpg)
![The Crowned Queen 6](https://user-images.githubusercontent.com/88982629/180023830-2f8eee17-a7be-42b7-a10f-f13b0c411164.jpg)
![The Crowned Queen 7](https://user-images.githubusercontent.com/88982629/180023833-7a23f76c-cfd9-4f56-b5d7-ad468f5f5b54.jpg)
![The Crowned Queen 8](https://user-images.githubusercontent.com/88982629/180023835-cea79f8c-c7d6-4e5f-9e63-963bba416a54.jpg)
![The Crowned Queen 9](https://user-images.githubusercontent.com/88982629/180023836-0303f145-1fb4-435e-bf9b-7a70c293fe56.jpg)
![The Crowned Queen 10](https://user-images.githubusercontent.com/88982629/180023838-2d196d54-b45a-4f70-9eab-2704850b2119.jpg)
![The Crowned Queen 11](https://user-images.githubusercontent.com/88982629/180023840-1ebdb0ea-a808-4508-927a-85cddbcc37ba.jpg)
![The Crowned Queen 12](https://user-images.githubusercontent.com/88982629/180023841-66223521-3cf8-4dbe-9d60-468de406379a.jpg)
![The Crowned Queen 13](https://user-images.githubusercontent.com/88982629/180023842-393a6cb0-d904-4c68-b15c-4c24cd2b18c8.jpg)
![The Crowned Queen 14](https://user-images.githubusercontent.com/88982629/180023844-d750b24d-e462-48ee-a7d2-7eaa75893580.jpg)
![The Crowned Queen 15](https://user-images.githubusercontent.com/88982629/180023846-fd1424e4-f0c5-4cd7-95e7-45c32f5cc2a6.jpg)
![The Crowned Queen Poster](https://user-images.githubusercontent.com/88982629/180023847-a50e0adf-d4e2-4fa7-8664-91f2a239b472.jpg)

**Comment by HarleysTwin** [comment]
![The Crowned Queen 1](https://user-images.githubusercontent.com/88982629/180027617-d56cfdf1-fe9f-4b8c-9dba-19b36f7b2317.jpg)
![The Crowned Queen 2](https://user-images.githubusercontent.com/88982629/180027620-9a9c48ec-3a7d-4b5d-9dea-bea84e6912e4.jpg)
![The Crowned Queen 3](https://user-images.githubusercontent.com/88982629/180027627-5eaf881a-c3bc-49fa-b534-57ae5c8f0674.jpg)
![The Crowned Queen 4](https://user-images.githubusercontent.com/88982629/180027628-1d375bae-d287-41bc-b57f-9e55d5fa61d4.jpg)
![The Crowned Queen 5](https://user-images.githubusercontent.com/88982629/180027630-074a90ab-476a-4449-96ff-1f55f51fd1d4.jpg)
![The Crowned Queen 6](https://user-images.githubusercontent.com/88982629/180027632-65f97a7c-eae8-4f06-9b12-b6511bc791ed.jpg)
![The Crowned Queen 7](https://user-images.githubusercontent.com/88982629/180027633-d5df50bc-e871-4ddb-81ce-e729709b3f3d.jpg)
![The Crowned Queen 8](https://user-images.githubusercontent.com/88982629/180027635-29182e19-a0b7-4058-b9d3-3502531057b2.jpg)
![The Crowned Queen 9](https://user-images.githubusercontent.com/88982629/180027637-6ae20fc3-ef4c-4e7a-87de-4aa2caf6d2a9.jpg)
![The Crowned Queen 10](https://user-images.githubusercontent.com/88982629/180027638-4502bb50-0a90-47d9-ade6-2c272e18943c.jpg)
![The Crowned Queen 11](https://user-images.githubusercontent.com/88982629/180027640-be730531-e2d8-4c66-b85d-cfb06da8b57a.jpg)
![The Crowned Queen 12](https://user-images.githubusercontent.com/88982629/180027641-0722ebdd-ae0b-4d0f-bbe4-68e1b682201b.jpg)
![The Crowned Queen 13](https://user-images.githubusercontent.com/88982629/180027643-c8a3ab45-112e-40f5-af53-9660fde52e44.jpg)
![The Crowned Queen 14](https://user-images.githubusercontent.com/88982629/180027646-0f0d901f-3d62-430a-9194-f8b0919668a6.jpg)
![The Crowned Queen 15](https://user-images.githubusercontent.com/88982629/180027647-385e9eb5-4dbc-4f93-8104-a70e2952d8b1.jpg)
![The Crowned Queen Poster](https://user-images.githubusercontent.com/88982629/180027649-4002c4a5-a144-46a9-8a3e-543d341b8314.jpg)

**Comment by lynnandtonic** [comment]
Thanks for the screenshots! https://nestflix.fun/the-crowned-queen/
