### ISSUE TITLE
Add The Jerry Langford Show

### ISSUE THREAD

**Issue by adactio** [lynnandtonic/nestflix.fun#455]
Please add as much of the following info as you can:

Title: The Jerry Langford Show

Type (film/tv show): TV show

Film or show in which it appears: King Of Comedy

Is the parent film/show streaming anywhere?

About when in the parent film/show does it appear?

Actual footage of the film/show can be seen (yes/no)? Yes

**Comment by lynnandtonic** [comment]
Thanks, Jeremy! https://nestflix.fun/the-jerry-langford-show/
