### ISSUE TITLE
Add All Over The Girl

### ISSUE THREAD

**Issue by dstaley** [lynnandtonic/nestflix.fun#457]
Please add as much of the following info as you can:

Title: All Over The Girl

Type (film/tv show): Film

Film or show in which it appears: Marriage Story

Is the parent film/show streaming anywhere? [Netflix](https://www.netflix.com/title/80223779)

About when in the parent film/show does it appear? 2m50s

Actual footage of the film/show can be seen (yes/no)? Yes

**Comment by lynnandtonic** [comment]
Thanks @dstaley! 🤗 https://nestflix.fun/all-over-the-girl/
