### ISSUE TITLE
Add Scrooge

### ISSUE THREAD

**Issue by HarleysTwin** [lynnandtonic/nestflix.fun#460]
Please add as much of the following info as you can:

Title: Scrooge

Type (film/tv show): live TV movie

Film or show in which it appears: Scrooged

Is the parent film/show streaming anywhere? YouTube, Amazon Prime, Apple+

About when in the parent film/show does it appear? The end of the film goes to the live broadcast.

Actual footage of the film/show can be seen (yes/no)? Yes.

Production company: IBC Television 

Cast: Buddy Hackett (Scrooge), Mary Lou Retton (Tiny Tim), Jamie Farr (Jacob Marley), Pat McCormick (Ghost of Christmas Present), Solid Gold Dancers; Uncredited: Frank Cross, Claire Phillips, Grace Cooley, Calvin Cooley (They weren’t initially intended to be part of the broadcast.)

**Comment by lynnandtonic** [comment]
This one is on the site! https://nestflix.fun/scrooge/
