### ISSUE TITLE
Add The Gordon Ford Show from 'The Marvelous Mrs Maisel'

### ISSUE THREAD

**Issue by dletter** [lynnandtonic/nestflix.fun#463]
Please add as much of the following info as you can:

Title: The Gordon Ford Show

Type (film/tv show): TV Show

Film or show in which it appears:'The Marvelous Mrs Maisel'

Is the parent film/show streaming anywhere? Amazon Prime

About when in the parent film/show does it appear? Season 4, episodes 6-8

Actual footage of the film/show can be seen (yes/no)? Yes

**Comment by lynnandtonic** [comment]
Thank you! https://nestflix.fun/the-gordon-ford-show/

**Comment by dletter** [comment]
Thank you... was that a real quote from the show?  I don't recall it, but either way funny.

**Comment by lynnandtonic** [comment]
Ha yes it was!
