### ISSUE TITLE
Add Sports Shouting from "30 Rock"

### ISSUE THREAD

**Issue by freeling1010** [lynnandtonic/nestflix.fun#464]
Please add as much of the following info as you can:

Title: Sports Shouting

Type (film/tv show): TV show

Film or show in which it appears: **30 Rock**

Is the parent film/show streaming anywhere? Yes

About when in the parent film/show does it appear? S04E05

Actual footage of the film/show can be seen (yes/no)? Yes

**Comment by lynnandtonic** [comment]
Thank you! https://nestflix.fun/sports-shouting/
