### ISSUE TITLE
Add How to Ratatwang your Panda from The Amazing World of Gumball

### ISSUE THREAD

**Issue by olivertasche** [lynnandtonic/nestflix.fun#469]
Please add as much of the following info as you can:
This is not the even real film, it is some mockbuster from the bargain bin.

Title: How to Ratatwang your Panda

Type (film/tv show): Film

Film or show in which it appears: The Amazing World of Gumball (Cartoon Network)

Is the parent film/show streaming anywhere? Yes => https://www.justwatch.com/de/Serie/The-Amazing-World-of-Gumball

About when in the parent film/show does it appear? S02E05 12:08

Actual footage of the film/show can be seen (yes/no)? Yes

![DVD Case](https://i.imgur.com/aE5OqmG.png)
![Footage 1](https://i.imgur.com/Ujc6889.png)
![Footage 2](https://i.imgur.com/UJpfzWc.png)
![Footage 3](https://i.imgur.com/50RDySC.png)
![Footage 4](https://i.imgur.com/RG6QmrI.png)
![Footage 5](https://i.imgur.com/giBmqBp.png)
![Footage 6](https://i.imgur.com/8qUXM6P.png)
[Album on imgur](https://imgur.com/a/OBE6Nmf)

**Comment by lynnandtonic** [comment]
Thank you! https://nestflix.fun/how-to-ratatwang-your-panda/
