### ISSUE TITLE
Add "The Nests of Netherfield"

### ISSUE THREAD

**Issue by nsfmc** [lynnandtonic/nestflix.fun#47]
Please add as much of the following info as you can:

**Title:**

The Nests of Netherfield

**Type (film/tv show):**

TV Show

**Film or show in which it appears:**

Tuca and Bertie

**Is the parent film/show streaming anywhere?**

Netflix

**About when in the parent film/show does it appear?**

S1E3 ~15:20

**Actual footage of the film/show can be seen (yes/no)?**

yes

![2021-08-11 at 6 44 11 PM](https://user-images.githubusercontent.com/216572/129126273-3ac01dec-a40c-47cf-99f9-89067bd7d09c.png)
![2021-08-11 at 6 43 15 PM](https://user-images.githubusercontent.com/216572/129126265-98b2e0f1-75d2-4cb1-b34c-da3e290b0290.png)
![2021-08-11 at 6 44 43 PM](https://user-images.githubusercontent.com/216572/129126277-0c726f87-d5a8-4b24-8c78-a25b753bb4c5.png)
![2021-08-11 at 6 44 55 PM](https://user-images.githubusercontent.com/216572/129126287-fc052b47-bb70-42f5-9527-ff7e1058a688.png)![2021-08-11 at 6 44 53 PM](https://user-images.githubusercontent.com/216572/129126284-1319ed2b-d9e0-47f4-a55a-46cb84ac8f8e.png)

**Comment by lynnandtonic** [comment]
It's up! https://nestflix.fun/the-nests-of-netherfield/

Thank you!
