### ISSUE TITLE
Add Tonight with Katherine Newbury from Late Night

### ISSUE THREAD

**Issue by DLu** [lynnandtonic/nestflix.fun#471]
Title: Tonight with Katherine Newbury

Type (film/tv show): tv show

Film or show in which it appears: Late Night (2019)

Is the parent film/show streaming anywhere? Amazon

About when in the parent film/show does it appear? Throughout

Actual footage of the film/show can be seen (yes/no)? yes

**Comment by lynnandtonic** [comment]
Thank you! https://nestflix.fun/tonight-with-katherine-newbury/
