### ISSUE TITLE
Add Loose Limbs 5 from Evil Ed

### ISSUE THREAD

**Issue by Metostopholes** [lynnandtonic/nestflix.fun#472]
Please add as much of the following info as you can:

Title: Loose Limbs 5: The Anatomy of Fear

Type (film/tv show): Film

Film or show in which it appears: Evil Ed

Is the parent film/show streaming anywhere? https://tubitv.com/movies/475406/evil-ed

About when in the parent film/show does it appear? 27:52

Actual footage of the film/show can be seen (yes/no)? Yes

**Comment by lynnandtonic** [comment]
Thank you! https://nestflix.fun/loose-limbs-5/
