### ISSUE TITLE
Add "Water-T and the Rise of the Numbericons" from "Rick and Morty"

### ISSUE THREAD

**Issue by bergren2** [lynnandtonic/nestflix.fun#477]
Please add as much of the following info as you can:

Title: Water-T and the Rise of the Numbericons

Type (film/tv show): film

Film or show in which it appears: Rick and Morty

Is the parent film/show streaming anywhere? Yes - Hulu

About when in the parent film/show does it appear? Season 2 Episode 5 "Get Schwifty"

Actual footage of the film/show can be seen (yes/no)? Yes https://www.youtube.com/watch?v=LPDn0PC6zFE

**Comment by lynnandtonic** [comment]
Thank you! https://nestflix.fun/water-t-and-the-rise-of-the-numbericons/
