### ISSUE TITLE
judge judy the aftermath from judge judy

### ISSUE THREAD

**Issue by TLLGUY** [lynnandtonic/nestflix.fun#479]
Please add as much of the following info as you can:

Title:judge judy the aftermath

Type (film/tv show):tv show

Film or show in which it appears:judge judy

Is the parent film/show streaming anywhere? no

About when in the parent film/show does it appear? judge judy

Actual footage of the film/show can be seen (yes/no)? no

**Comment by lynnandtonic** [comment]
Hi @TLLGUY! If there's no footage of the show, I won't be adding it to Nestflix right now. Thank you though!
