### ISSUE TITLE
Add Daisy the Donkey Show from The Amazing World of Gumball

### ISSUE THREAD

**Issue by ethanimation** [lynnandtonic/nestflix.fun#484]
Please add as much of the following info as you can:

Title: Daisy the Donkey Show 

Type (film/tv show): tv show 

Film or show in which it appears: The Amazing World of Gumball  

Is the parent film/show streaming anywhere? HBO Max

About when in the parent film/show does it appear? The Amazing World of Gumball Season 5 Episode 36

Actual footage of the film/show can be seen (yes/no)? yes

**Comment by lynnandtonic** [comment]
Thank you!!
