### ISSUE TITLE
Add "A Sensible Migration"

### ISSUE THREAD

**Issue by nsfmc** [lynnandtonic/nestflix.fun#49]
Please add as much of the following info as you can:

**Title:**

A Sensible Migration

**Type (film/tv show):**

TV Show

**Film or show in which it appears:**

Tuca and Bertie

**Is the parent film/show streaming anywhere?**

yes, netflix

**About when in the parent film/show does it appear?**

S1E3 @ 16:20

**Actual footage of the film/show can be seen (yes/no)?**

yes

![Screen Shot 2021-08-11 at 6 46 28 PM](https://user-images.githubusercontent.com/216572/129126965-a835cfea-5261-4a39-aca5-e0e0f14a1b7c.png)
![Screen Shot 2021-08-11 at 6 45 55 PM](https://user-images.githubusercontent.com/216572/129126989-abc9dc17-e08a-4dee-be9f-2f407b80bb6b.png)
![Screen Shot 2021-08-11 at 6 46 02 PM](https://user-images.githubusercontent.com/216572/129127001-4a701e8d-3322-4fc7-9245-1414a4c7d5c3.png)
![Screen Shot 2021-08-11 at 6 46 06 PM](https://user-images.githubusercontent.com/216572/129127010-a47b277f-1b5b-4332-bf88-dbab91b3e7f0.png)
![Screen Shot 2021-08-11 at 6 46 07 PM](https://user-images.githubusercontent.com/216572/129127023-2939ec9d-0638-462c-bc93-e2bb6b7a6d80.png)

**Comment by lynnandtonic** [comment]
It's up! https://nestflix.fun/a-sensible-migration/

Thank you!
