### ISSUE TITLE
Add Blarney the Sea Serpent 

### ISSUE THREAD

**Issue by ethanimation** [lynnandtonic/nestflix.fun#491]
Please add as much of the following info as you can:

Title: Blarney the Sea Serpent 

Type (film/tv show): tv show

Film or show in which it appears: The Powerpuff Girls

Is the parent film/show streaming anywhere? HBO Max

About when in the parent film/show does it appear? Child Fearing

Actual footage of the film/show can be seen (yes/no)? yes

**Comment by HarleysTwin** [comment]
* Blarney the Singing Sea Serpent is the name of the character.  His show itself doesn't seem to be named.  

Here is a link to the show clip
![Blarney 1](https://user-images.githubusercontent.com/88982629/182246036-4886ce3a-dc0c-4fa2-a2ec-a83fd9035650.jpg)
![Blarney 2](https://user-images.githubusercontent.com/88982629/182246039-a2c6e030-22e4-4da8-ba84-ba728fd59ef4.jpg)
![Blarney 3](https://user-images.githubusercontent.com/88982629/182246041-78a1ce05-249a-4447-9140-ab3243a12177.jpg)
![Blarney 4](https://user-images.githubusercontent.com/88982629/182246042-dbea8c17-1ed5-4ba8-bd2b-9a68da062038.jpg)
![Blarney 5](https://user-images.githubusercontent.com/88982629/182246045-b4e6d2bd-3331-4e3e-8455-b1d220c43c16.jpg)
![Blarney 6](https://user-images.githubusercontent.com/88982629/182246046-777a7c9d-8955-4cd3-bc0f-26b52a7d9ce2.jpg)
![Blarney 7](https://user-images.githubusercontent.com/88982629/182246047-197b541b-76da-4f0f-8961-a3e698a5012d.jpg)
![Blarney 8](https://user-images.githubusercontent.com/88982629/182246048-05b12141-a635-43d5-8150-e59c32e0280e.jpg)
![Blarney 9](https://user-images.githubusercontent.com/88982629/182246050-7f7abade-a26d-47bf-be62-ba47da1ad2d5.jpg)
: https://www.youtube.com/watch?v=Fjk7HJYSnSs

**Comment by lynnandtonic** [comment]
Thank you! https://nestflix.fun/blarney-the-singing-sea-serpent/
