### ISSUE TITLE
Sacrilegio (and a slew of other fake movies)

### ISSUE THREAD

**Issue by dletter** [lynnandtonic/nestflix.fun#497]
https://www.youtube.com/watch?v=M2G9qar-yKw

I don't know if you'd do things from a music video, but, there are some gems in here that would be cool to have a page for (some go too quickly to likely do, but, some you could get a few frames of, and come up with your own idea of the plot of the movie, LOL).

**Comment by dletter** [comment]
Sacrilegio at 2:12

**Comment by lynnandtonic** [comment]
Ah these are really cool! Unfortunately doesn’t qualify for now (maybe later on I’d do music videos). Thank you!
