### ISSUE TITLE
Add Maria Bamford Is Nuts!

### ISSUE THREAD

**Issue by tonycpsu** [lynnandtonic/nestflix.fun#50]
Please add as much of the following info as you can:

Title: Maria Bamford Is Nuts!

Type (film/tv show): TV Show

Film or show in which it appears: Lady Dynamite

Is the parent film/show streaming anywhere? Netflix / MuskVision

About when in the parent film/show does it appear? Season 2, Episode 2, around 15 minutes in.

Actual footage of the film/show can be seen (yes/no)? yes

**Comment by lynnandtonic** [comment]
It's live! https://nestflix.fun/maria-bamford-is-nuts/

Thank you!
