### ISSUE TITLE
Add Bitch PM from Hacks

### ISSUE THREAD

**Issue by Maximegalon** [lynnandtonic/nestflix.fun#506]
Please add as much of the following info as you can:

Title: Bitch PM

Type: TV Show

Film or show in which it appears: Hacks 

Is the parent film/show streaming anywhere? Yes, HBO

About when in the parent film/show does it appear? Season 1, Episode 9, 17:40

Actual footage of the film/show can be seen (yes/no)? No

**Comment by lynnandtonic** [comment]
Hey @Maximegalon! I love Hacks! Unfortunately Bitch PM doesn’t qualify for Nestflix right now because they don’t show any footage. Thank you!
