### ISSUE TITLE
Add "Thunder Gun 4: Maximum Cool"

### ISSUE THREAD

**Issue by lolkthxbai** [lynnandtonic/nestflix.fun#51]
Please add as much of the following info as you can:

Title: Thunder Gun 4: Maximum Cool

Type (film/tv show): Film

Film or show in which it appears: It's Always Sunny In Philadelphia

Is the parent film/show streaming anywhere? Hulu

About when in the parent film/show does it appear? Season 14, Episode 2

Actual footage of the film/show can be seen (yes/no)? Yes

**Comment by ericArbour** [comment]
![thunder](https://user-images.githubusercontent.com/8760181/129229181-fb8c491b-c134-49fe-a873-998fcbb9d19e.jpg)

**Comment by lynnandtonic** [comment]
It’s up! https://nestflix.fun/thunder-gun-4-maximum-cool/

Thank you!
