### ISSUE TITLE
Add Million Dollar Heads or Tails from HIMYM

### ISSUE THREAD

**Issue by dletter** [lynnandtonic/nestflix.fun#512]
Please add as much of the following info as you can:

Title: Million Dollar Heads or Tails

Type (film/tv show):TV show

Film or show in which it appears: How I Met Your Mother

Is the parent film/show streaming anywhere?  Clip at https://www.youtube.com/watch?v=TDmcPUQj_G0&ab_channel=CopyrightStriked

About when in the parent film/show does it appear? Beginning of this clip

Actual footage of the film/show can be seen (yes/no)? Yes

"Marnie, flip that coin!"

**Comment by lynnandtonic** [comment]
Thank you! https://nestflix.fun/million-dollar-heads-or-tails/
