### ISSUE TITLE
Do you need a hand?

### ISSUE THREAD

**Issue by HarleysTwin** [lynnandtonic/nestflix.fun#514]
This is a sort of follow up to your last message. Would you like some help with all the submissions? I have a lot of downtime at work, and I really like cataloging things like this. (ADHD rabbit holes means I like making lists.) If you tell me what you need, I can help to the best of my ability, if you would like.

**Comment by lynnandtonic** [comment]
Timestamps and screenshots help a lot! Even just to provide me a visual of what I should be looking for. Also if you can find logos for the films/shows that would be awesome (sometimes the logo is shown separately from the footage, sometimes there isn't one at all).

There’s a lot of data included with each entry, so any contextual information is also appreciated!

Thank you so much! 😊

**Comment by HarleysTwin** [comment]
Sure, @lynnandtonic.  I can definitely help with that.  :)  For example, I just added a **bunch** of screenshots for _The Gout Lovers_ with the poster for ya.  Do you want me to keep doing that with the submissions here to help out?  Like I said, I have a lot of downtime at work.

**Comment by lynnandtonic** [comment]
Amazing, thank you! If you want to keep going that would be really great, but no pressure at all!

**Comment by HarleysTwin** [comment]
No sweat, @lynnandtonic. Should I tell you which ones here I’ve done so you know?

**Comment by lynnandtonic** [comment]
@HarleysTwin I should get notified whenever you add a comment, so no need!

**Comment by lynnandtonic** [comment]
@HarleysTwin Thanks again so much! The screenshots are super helpful ✨ If you end up looking at other issues, please skip ones for The Critic for now. I’m still working out if I’m going to add all those. Thank you!
