### ISSUE TITLE
Add Republican Space Rangers from Grand Theft Auto (Video Game)

### ISSUE THREAD

**Issue by www2000** [lynnandtonic/nestflix.fun#515]
Please add as much of the following info as you can:

Title: Republican Space Rangers	

Type (film/tv show): TV - Cartoon/animation

Film or show in which it appears: Grand Theft Auto IV, The Lost and Damned, The Ballad of Gay Tony
and Grand Theft Auto V (video game)

Is the parent film/show streaming anywhere?
Video Game

About when in the parent film/show does it appear? N/A In game Tv show you can watch

Actual footage of the film/show can be seen (yes/no)? yes

**Comment by HarleysTwin** [comment]
I believe the scope of Nestflix is in film and TV only.

**Comment by lynnandtonic** [comment]
@www2000 Yes, sorry I’m not taking video game submissions right now. Thank you though!
