### ISSUE TITLE
Add Tinseltown Diaries

### ISSUE THREAD

**Issue by 97jaz** [lynnandtonic/nestflix.fun#52]
Please add as much of the following info as you can:

Title: Tinseltown Diaries

Type (film/tv show): TV show

Film or show in which it appears: Veronica Mars, Season 2, episode 18, "I Am God"

Is the parent film/show streaming anywhere? Yep, Hulu

About when in the parent film/show does it appear? 26:53

Actual footage of the film/show can be seen (yes/no)? yes

**Comment by lynnandtonic** [comment]
It’s live! https://nestflix.fun/tinseltown-diaries/

Thank you! 🌈
