### ISSUE TITLE
Add Brazzos (2022) from "Only Murders in the Building" (Screenshots and Poster Added)

### ISSUE THREAD

**Issue by HarleysTwin** [lynnandtonic/nestflix.fun#523]
Please add as much of the following info as you can:

Title: Brazzos (2022) 

Type (film/tv show): TV series - detective drama

Film or show in which it appears: Only Murders in the Building

Is the parent film/show streaming anywhere? Yes - Hulu

About when in the parent film/show does it appear? Ep. 2x06 - "Performance Review"

Actual footage of the film/show can be seen (yes/no)? Yes
Timestamp:
- 7:12-8:10 

Cast: Naomi Jackson, Charles-Haden Savage

Tagline: This sends the investigation in a whole new direction.
![Brazzos 1](https://user-images.githubusercontent.com/88982629/182281958-aec7faed-ffed-40f1-9eeb-7c0c3e565758.jpg)
![Brazzos 2](https://user-images.githubusercontent.com/88982629/182281964-9cdc74d2-1fd1-47d7-a589-7bc783b37a98.jpg)
![Brazzos 3](https://user-images.githubusercontent.com/88982629/182281966-3face756-35fc-45d5-85b3-5d8a087a4a51.jpg)
![Brazzos 4](https://user-images.githubusercontent.com/88982629/182281968-d319ffa4-dd22-4469-a907-d4026ca6dd60.jpg)
![Brazzos 5](https://user-images.githubusercontent.com/88982629/182281971-de8cb3e4-3356-4795-b8cb-0bf48e0e601e.jpg)
![Brazzos 6](https://user-images.githubusercontent.com/88982629/182281972-ab75117b-3e06-4556-a432-a1e14413e48a.jpg)
![Brazzos 7](https://user-images.githubusercontent.com/88982629/182281973-3d31ba72-87c0-4ec5-adef-16ced2a72b78.jpg)
![Brazzos Posters](https://user-images.githubusercontent.com/88982629/182281975-3c20157a-d176-4ebd-b67d-809812b20f8d.jpg)

**Comment by dletter** [comment]
Soup!

**Comment by lynnandtonic** [comment]
Thank you so much! I ended up adding new info/shots to the original Brazzos entry. https://nestflix.fun/brazzos/
