### ISSUE TITLE
Add McBain: Let's Get Silly from "The Simpsons" (Screenshots Added)

### ISSUE THREAD

**Issue by HarleysTwin** [lynnandtonic/nestflix.fun#524]
Please add as much of the following info as you can:

Title: McBain: Let's Get Silly

Type (film/tv show): Film - standup comedy

Film or show in which it appears: The Simpsons

Is the parent film/show streaming anywhere? Yes - Disney+

About when in the parent film/show does it appear? Ep. 6x18 - "A Star is Burns"

Actual footage of the film/show can be seen (yes/no)? Yes - https://www.youtube.com/watch?v=eFJhC__qu5I

Starring: Rainer Wolfcastle

Fun Fact: The film is just McBain in front of a brick wall for an hour and half.  It cost 80 million dollars.
Quote: That's the joke.

![McBain 1](https://user-images.githubusercontent.com/88982629/182289860-388e6b35-f294-40b1-a28a-1b1f0f306827.jpg)
![McBain 2](https://user-images.githubusercontent.com/88982629/182289862-055ae136-359b-4fc6-ac29-cf054e773294.jpg)
![McBain 3](https://user-images.githubusercontent.com/88982629/182289863-414007f8-6074-4927-be14-4b45d60a441f.jpg)
![McBain 4](https://user-images.githubusercontent.com/88982629/182289865-e110b5e0-1454-4706-ac43-a1ecf565a9c7.jpg)
![McBain 5](https://user-images.githubusercontent.com/88982629/182289866-0321232a-9976-4d69-9e09-4d1255446c3a.jpg)
![McBain 6](https://user-images.githubusercontent.com/88982629/182289867-26cdcabb-c09f-4b2a-b18b-956f4a2cb237.jpg)
![McBain 7](https://user-images.githubusercontent.com/88982629/182289868-93f1bad2-1c92-4e69-8819-532b13d83d5d.jpg)
![McBain 8](https://user-images.githubusercontent.com/88982629/182289870-602c380d-21af-409d-8465-07b3483773de.jpg)

**Comment by lynnandtonic** [comment]
Thank you! https://nestflix.fun/mcbain-lets-get-silly/
