### ISSUE TITLE
Add Big Baby from "Allegoria" (Screenshots added)

### ISSUE THREAD

**Issue by HarleysTwin** [lynnandtonic/nestflix.fun#525]
Please add as much of the following info as you can:

Title: Big Baby

Type (film/tv show): film - slasher horror

Film or show in which it appears: Allegoria

Is the parent film/show streaming anywhere? Yes - Amazon Prime & Shudder

Synopsis: He was traumatized by being left in his crib while his babysitter had sex.  Twenty years later, this big baby goes on a killing spree.

About when in the parent film/show does it appear? Slightly past mid-way it's shown interspersed with reaction shots of the people watching it.  It's also shown in its entirity as a post-credits scene.

Actual footage of the film/show can be seen (yes/no)? Yes
Timestamps:
-  interspersed with audience reactions: 37:42 - 40:08
- post credits scene begins at 1:07:30

Production Company: an Eddie Park film

Quote: Who's the big baby now?!

(Sorry, I can't give screenshots.  I watched it through a reviewer screener.)

**Comment by HarleysTwin** [comment]
Managed to nap some from trailers and reviews.
![Big Baby 1](https://user-images.githubusercontent.com/88982629/185508861-b57b0b49-0170-4261-84ac-61ec1edf1b1c.jpg)
![Big Baby 2](https://user-images.githubusercontent.com/88982629/185508862-8939c242-c545-48ff-86cc-adb9f1650249.jpg)
![Big Baby 3](https://user-images.githubusercontent.com/88982629/185508863-566004fa-825d-4d46-8f79-7f49b7d673bf.jpg)
![Big Baby 4](https://user-images.githubusercontent.com/88982629/185508864-1d416608-717a-4f6a-977c-09e480543c8d.jpg)
![Big Baby 6](https://user-images.githubusercontent.com/88982629/185508865-5a1b581c-c684-4b9f-88e4-a6600cae4fd3.jpg)
![Big Baby 7](https://user-images.githubusercontent.com/88982629/185508868-5d1df343-1e13-4058-9ddd-e1cb46fd15d6.jpg)
![Big Baby 8](https://user-images.githubusercontent.com/88982629/185508871-66622db4-428c-4ed2-b682-320722d6add2.jpg)
![Big Baby 9](https://user-images.githubusercontent.com/88982629/185508873-5d057531-f9a4-4535-b944-ff16a1681ffa.jpg)
![Big Baby 10](https://user-images.githubusercontent.com/88982629/185508874-1f4cd54c-4463-48fb-ae10-52a6f76497ce.jpg)
![Big Baby 11](https://user-images.githubusercontent.com/88982629/185508876-a628d2ce-0049-40f1-b5a8-a8ce3af3f023.jpg)
![Big Baby 12](https://user-images.githubusercontent.com/88982629/185508877-aa58829e-6afe-41bc-880c-d652f8de208b.jpg)
![Big Baby 13](https://user-images.githubusercontent.com/88982629/185508878-4e76eedd-3dca-45c1-b317-d75a6e47bd16.jpg)

**Comment by HarleysTwin** [comment]
Managed to nab some from trailers and reviews.
![Big Baby 1](https://user-images.githubusercontent.com/88982629/185508967-9c9cbd82-9b50-4fa2-8fd3-ab28b509c8b4.jpg)
![Big Baby 2](https://user-images.githubusercontent.com/88982629/185508968-c212dbca-c46c-4c28-b79a-58ee9c6d3c4f.jpg)
![Big Baby 3](https://user-images.githubusercontent.com/88982629/185508970-22291ac3-f95d-438a-8796-2c48e9ad4598.jpg)
![Big Baby 6](https://user-images.githubusercontent.com/88982629/185508971-867e7cee-ddba-4c38-896d-61a623ba7c76.jpg)
![Big Baby 7](https://user-images.githubusercontent.com/88982629/185508972-25c6813e-aa8f-4bff-93c8-0f7eb13fdb5f.jpg)
![Big Baby 8](https://user-images.githubusercontent.com/88982629/185508973-51e80145-ca45-4291-88ac-c2760252ec82.jpg)
![Big Baby 9](https://user-images.githubusercontent.com/88982629/185508976-03dead93-f99f-4aab-83e3-916672b9ac23.jpg)
![Big Baby 10](https://user-images.githubusercontent.com/88982629/185508977-0e29b44a-423e-4cf3-820e-5b9aa645672a.jpg)
![Big Baby 11](https://user-images.githubusercontent.com/88982629/185508979-f8166398-3b07-4eab-8adc-223461ff9765.jpg)
![Big Baby 12](https://user-images.githubusercontent.com/88982629/185508980-b4b4900b-5944-4589-bf67-89aae1e79098.jpg)
![Big Baby 13](https://user-images.githubusercontent.com/88982629/185508982-0f71f55a-3139-406e-b7d2-3f3655c11601.jpg)

**Comment by lynnandtonic** [comment]
Thank you! https://nestflix.fun/big-baby/
