### ISSUE TITLE
Add COPS: In Springfield from The Simpsons

### ISSUE THREAD

**Issue by ethanimation** [lynnandtonic/nestflix.fun#526]
Please add as much of the following info as you can:

Title: COPS: In Springfield

Type (film/tv show): tv show

Film or show in which it appears: The Simpsons Homer's Triple Bypass

Is the parent film/show streaming anywhere? Disney+

About when in the parent film/show does it appear? 01:18

Actual footage of the film/show can be seen (yes/no)? yes 

https://www.youtube.com/watch?v=BexuOsshqjk&ab_channel=ThingsICantFindOtherwise

**Comment by lynnandtonic** [comment]
@ethanimation This one is on the site already! https://nestflix.fun/cops-in-springfield/ Thank you!
