### ISSUE TITLE
Add Colt Luger

### ISSUE THREAD

**Issue by paulschun** [lynnandtonic/nestflix.fun#53]
*Title:*

Colt Luger

*Type (film/tv show):*

tv show

*Film or show in which it appears:*

F Is For Family

*Is the parent film/show streaming anywhere?*

Yes (Netflix)

*About when in the parent film/show does it appear?*

Nearly any scene where the characters are watching TV

*Actual footage of the film/show can be seen (yes/no)?*

Yes

**Comment by lynnandtonic** [comment]
Thank you, @paulschun! https://nestflix.fun/colt-luger/
