### ISSUE TITLE
Add Mosquito from Popcorn (1991)

### ISSUE THREAD

**Issue by olivertasche** [lynnandtonic/nestflix.fun#530]
Title: Mosquito

Type (film/tv show): Film

Film or show in which it appears: Popcorn (1991)

Is the parent film/show streaming anywhere? Yes (Shudder and AMC+); https://www.justwatch.com/us/movie/popcorn-1991

About when in the parent film/show does it appear? 0:26:35

Actual footage of the film/show can be seen (yes/no)? yes

Starring
Randall Todd
Alison Holt

Introducing
Cubby Scott ad "Corky"

Quotes:
Send the Air Force, Mr. President. Don't forget the Army, Navy, and the Coast Guard.
We need every plane, tank, and battleship you've got, Mr. President.
This is one hell of a bug.

- Nothing fazes it. We'll have to drop the A-bomb.
- No, Jim, that's what started all this trouble in the first place.

Screenshots:
![mosquito_2](https://user-images.githubusercontent.com/80119678/183198093-3f63eb42-a762-4555-903c-5a51d0c916d7.png)
![mosquito_3](https://user-images.githubusercontent.com/80119678/183198103-95b353ae-e75b-4916-a56a-4f9ed93e1bde.png)
![mosquito_4](https://user-images.githubusercontent.com/80119678/183198115-f1aaface-1c3b-49cd-89a5-2d76bd84ec8d.png)
![mosquito_5](https://user-images.githubusercontent.com/80119678/183198126-0e7e754d-9b5e-4cbc-869c-d6ee181e0f54.png)
![mosquito_6](https://user-images.githubusercontent.com/80119678/183198136-33e727db-9fca-406f-ac67-8ab9836536f8.png)
![mosquito_7](https://user-images.githubusercontent.com/80119678/183198147-0609f620-f1fc-427b-a77f-3a0d10d79f89.png)
![mosquito_8](https://user-images.githubusercontent.com/80119678/183198159-beedec02-a591-4ac0-ac30-95f6aa189f36.png)
![mosquito_9](https://user-images.githubusercontent.com/80119678/183198168-c5479801-3d70-4a9a-b8dd-0f0db8b8d352.png)
![mosquito_10](https://user-images.githubusercontent.com/80119678/183198179-9bf2a292-dddd-418b-bb55-3eae5a03205a.png)
![mosquito_11](https://user-images.githubusercontent.com/80119678/183198194-797f4f47-bb5a-4a01-ae19-650127107b46.png)
![mosquito_12](https://user-images.githubusercontent.com/80119678/183198207-50c470a4-6e34-48b0-b68c-7a0560120c41.png)
![mosquito_13](https://user-images.githubusercontent.com/80119678/183198216-157b0b13-091a-49c7-b3d8-c563e2b00148.png)
![mosquito_1](https://user-images.githubusercontent.com/80119678/183198063-a39e9d17-1bfb-4762-a7b9-394fcebacf24.png)

**Comment by lynnandtonic** [comment]
Thank you!! https://nestflix.fun/mosquito/
