### ISSUE TITLE
Add The Attack of the Amazing Electrified Man from Popcorn (1991)

### ISSUE THREAD

**Issue by olivertasche** [lynnandtonic/nestflix.fun#531]
Title: The Attack of the Amazing Electrified Man

Type (film/tv show): Film

Film or show in which it appears: Popcorn (1991)

Is the parent film/show streaming anywhere? Yes (Shudder and AMC+); https://www.justwatch.com/us/movie/popcorn-1991

About when in the parent film/show does it appear? 0:39:00

Actual footage of the film/show can be seen (yes/no)? yes

Quotes:
- Tell me what do you know about erythrocytes and leukocytes?
- Say, aren't those the red and white corpuscles in the blood?
- Very good, Vernon.
  I have created a third corpuscle the "magnecyte."
  Theoretically, it can regenerate the blood cells even after severe trauma, any trauma.
  Even electrocution.
- I get it. You want to inject me with this corpuscle to see if I can survive the chair, is that it?
- Exactly.

Screenshots:
![taotaem_1](https://user-images.githubusercontent.com/80119678/183198882-d9ed822b-bc8e-493d-84e5-c880006ed831.png)
![taotaem_2](https://user-images.githubusercontent.com/80119678/183198912-f5e0e048-ae58-4788-9528-d60d81b5da31.png)
![taotaem_3](https://user-images.githubusercontent.com/80119678/183198924-26a826fc-b592-4c18-ae9e-d00af85b574f.png)
![taotaem_4](https://user-images.githubusercontent.com/80119678/183198935-11a9b76b-0148-44d4-9337-3abedd7353b8.png)
![taotaem_5](https://user-images.githubusercontent.com/80119678/183198946-cc3ad23a-806a-4161-9885-5f0a3d7c993e.png)
![taotaem_6](https://user-images.githubusercontent.com/80119678/183198957-59626e71-4f63-4d83-a995-dde9787b8f00.png)
![taotaem_7](https://user-images.githubusercontent.com/80119678/183198968-9cf01a58-4c53-4b10-9ecf-0c736b5fefe1.png)
![taotaem_8](https://user-images.githubusercontent.com/80119678/183198978-c58a3fa6-6d5a-4e6a-8fdb-08a814928bc2.png)
![taotaem_9](https://user-images.githubusercontent.com/80119678/183198989-1f8b2df4-950c-49f4-bbeb-dc645e41d3a7.png)
![taotaem_10](https://user-images.githubusercontent.com/80119678/183198999-1bc7f650-aaea-45f2-bc33-087875426a64.png)
![taotaem_11](https://user-images.githubusercontent.com/80119678/183199012-80f4533a-b3dc-46b6-819a-06b653477068.png)
![taotaem_12](https://user-images.githubusercontent.com/80119678/183199021-0cf2aa41-518a-42b2-aa2c-85c54a3d2bd0.png)
![taotaem_13](https://user-images.githubusercontent.com/80119678/183199031-f235b392-93b8-4d64-a3f3-e44ab62326c9.png)
![taotaem_14](https://user-images.githubusercontent.com/80119678/183199043-466d3eee-10d7-4ce3-a4cb-271e3e241c74.png)
![taotaem_15](https://user-images.githubusercontent.com/80119678/183199050-9c03cd72-7972-4cb3-9e8e-9a9dfe8bd13b.png)
![taotaem_16](https://user-images.githubusercontent.com/80119678/183199066-12d24fb2-2353-483a-8f96-f70b3e0cad21.png)

**Comment by lynnandtonic** [comment]
Thank you! https://nestflix.fun/the-attack-of-the-amazing-electrified-man/
