### ISSUE TITLE
Add saul and judy from better call saul and judge judy

### ISSUE THREAD

**Issue by TLLGUY** [lynnandtonic/nestflix.fun#534]
Please add as much of the following info as you can:

Title: better call judy

Type (film/tv show): Film

**Comment by dletter** [comment]
This sounds like something you just made up?  That isn't what this site is, it's fake shows/movies from real shows & movies.

**Comment by lynnandtonic** [comment]
@TLLGUY I'm going to close this since I’m not sure it’s from a real show. If you want to provide more info I can reopen. Thanks!
