### ISSUE TITLE
Add Witchita from "Love"

### ISSUE THREAD

**Issue by dletter** [lynnandtonic/nestflix.fun#536]
Please add as much of the following info as you can:

Title: Witchita

Type (film/tv show): TV Show

Film or show in which it appears: Love

Is the parent film/show streaming anywhere? Yes, Netflix

About when in the parent film/show does it appear?
Various points

Actual footage of the film/show can be seen (yes/no)?
Yes, in many episodes (S2E6 at the beginning).
Also, here is just a fake "trailer" from the show for the "new" season of Witchita:  https://www.facebook.com/watch/?v=1295123593930927

**Comment by lynnandtonic** [comment]
Thank you! https://nestflix.fun/witchita/

**Comment by dletter** [comment]
Thank you for getting it, and Liberty Down, forgot about the movie!  :)
