### ISSUE TITLE
Add Lethal Weapon 6 (Always Sunny)

### ISSUE THREAD

**Issue by bduffany** [lynnandtonic/nestflix.fun#54]
Please add as much of the following info as you can:

Title: Lethal Weapon 6

Type (film/tv show): Film

Film or show in which it appears: Always Sunny in Philadelphia: "The gang makes Lethal Weapon 6"

Is the parent film/show streaming anywhere? Yes, Hulu

About when in the parent film/show does it appear? The episode "The gang makes Lethal Weapon 6"

Actual footage of the film/show can be seen (yes/no)? Yes

**Comment by bsproul** [comment]
Also Lethal Weapon 5 (https://itsalwayssunny.fandom.com/wiki/Lethal_Weapon_5)

Title: Lethal Weapon 5

Type (film/tv show): Film

Film or show in which it appears: Always Sunny in Philadelphia: "Dee Reynolds: Shaping America's Youth"

Is the parent film/show streaming anywhere? Yes, Hulu

About when in the parent film/show does it appear? The episode "Dee Reynolds: Shaping America's Youth"

Actual footage of the film/show can be seen (yes/no)? Yes

**Comment by lynnandtonic** [comment]
So sorry guys, but I don’t think I’m going to add these. Both of the Lethal Weapon episodes were pulled from streaming services because of the blackface and even though I could capture stills without it, I’m going to respect their wish to not have it out there.

Thank you! 💚
