### ISSUE TITLE
Add "Night Springs"

### ISSUE THREAD

**Issue by HeyItsLollie** [lynnandtonic/nestflix.fun#55]
**Title:**
Night Springs

**Type (film/tv show):**
TV Show

**Film or show in which it appears:**
Alan Wake (2010, game by Remedy)

**Is the parent film/show streaming anywhere?**
[Steam](https://store.steampowered.com/app/108710/Alan_Wake/), [GOG](https://www.gog.com/game/alan_wake), [Epic Games Store](https://www.epicgames.com/store/en-US/p/alan-wake), [Microsoft Store](https://www.microsoft.com/en-us/p/alan-wake/c493v31wxv80#activetab=pivot:overviewtab)

**About when in the parent film/show does it appear?**
Periodically throughout the game, on various in-game TVs.

**Actual footage of the film/show can be seen (yes/no)?**
Yes! [Here's a playlist](https://www.youtube.com/watch?v=nHU0d3jxck0&list=PLWfAqLqGNQiHwp8wNxF4zVLSUtU45MChp&index=1) of all the episodes that appear in-game.

**Comment by lynnandtonic** [comment]
Hi! Unfortunately I’m not going to be adding films/shows from games for now. Thank you!

**Comment by HeyItsLollie** [comment]
Bummer, hope that changes in the future! Nestflix is already a decent resource for looking up in-fiction media, and games get in on the gag from time to time too.
