### ISSUE TITLE
Add Monster Trucks, Inc. from Cars

### ISSUE THREAD

**Issue by ethanimation** [lynnandtonic/nestflix.fun#557]
Please add as much of the following info as you can:

Title: Monster Trucks, Inc. 

Type (film/tv show): film

Film or show in which it appears: Cars

Is the parent film/show streaming anywhere? Disney+

About when in the parent film/show does it appear? 1:51:34

Actual footage of the film/show can be seen (yes/no)? yes

**Comment by lynnandtonic** [comment]
See this comment https://github.com/lynnandtonic/nestflix.fun/issues/558#issuecomment-1703955546
