### ISSUE TITLE
Add A Bug's Life from Cars

### ISSUE THREAD

**Issue by ethanimation** [lynnandtonic/nestflix.fun#558]
Please add as much of the following info as you can:

Title: A Bug's Life

Type (film/tv show): film

Film or show in which it appears: Cars 

Is the parent film/show streaming anywhere? Disney+

About when in the parent film/show does it appear? 1:51:55

Actual footage of the film/show can be seen (yes/no)? yes

**Comment by lynnandtonic** [comment]
Since these ones from Cars are in the credits and super small resolution, I don't think I'm going to add them right now. Thank you!
