### ISSUE TITLE
Add Ello Gov'nor from Regular Show

### ISSUE THREAD

**Issue by ethanimation** [lynnandtonic/nestflix.fun#568]
Please add as much of the following info as you can:

Title: Ello Gov'nor 

Type (film/tv show): film

Film or show in which it appears: Regular Show - Season 2 - Episode 1: Ello Gov'nor

Is the parent film/show streaming anywhere? HBO Max

About when in the parent film/show does it appear? 01:06

Actual footage of the film/show can be seen (yes/no)? yes

**Comment by lynnandtonic** [comment]
Thank you! https://nestflix.fun/ello-govnor/
