### ISSUE TITLE
Add The Corpse Danced at Midnight from "Murder, She Wrote" (Screenshots and Poster Added)

### ISSUE THREAD

**Issue by HarleysTwin** [lynnandtonic/nestflix.fun#569]
Please add as much of the following info as you can:

Title: "The Corpse Danced at Midnight"

Type (film/tv show): film: 80's thriller

Film or show in which it appears: Murder, She Wrote

Is the parent film/show streaming anywhere? Yes - Peacock

About when in the parent film/show does it appear? Ep. 1x05 - "Hooray for Homicide"

Actual footage of the film/show can be seen (yes/no)? Yes
Timestamp: 27:20 - 27:57

Synopsis: Based on the 1984 bestselling murder-mystery by J. B. Fletcher

Producer: Ross Haley (originally Jerry Lydecker with Lydecker Productions)
Director: Ross Haley
Writer: Allan Gebhart
Cast: Eve Crystal, Scott Bennett

"Fun" Fact <FYI - This is spoiler territory for the episode.>: The "gore and sex-filled" film was never finished <like 'Daddy's Boy' from "Unbreakable Kimmy Schmidt"> due to the murder of original producer, Jerry Lydecker, by the film's leading lady, Eve Crystal, and the subsequent cover-up by director, Ross Haley.

**Comment by HarleysTwin** [comment]
![The Corpse Danced at Midnight 1](https://user-images.githubusercontent.com/88982629/188680061-39320791-09b7-474a-8987-55cef632178e.jpg)
![The Corpse Danced at Midnight 2](https://user-images.githubusercontent.com/88982629/188680064-2cdb694d-c108-464d-9398-5e81a30b67a2.jpg)
![The Corpse Danced at Midnight 3](https://user-images.githubusercontent.com/88982629/188680065-21fc00a2-42d5-4a5f-8843-64927842687b.jpg)
![The Corpse Danced at Midnight 4](https://user-images.githubusercontent.com/88982629/188680066-43710ae1-fde1-4c41-82ca-ce0fc004e41d.jpg)
![The Corpse Danced at Midnight 5](https://user-images.githubusercontent.com/88982629/188680067-c8e6148c-9ffd-4b37-98d0-c885589a6809.jpg)
![The Corpse Danced at Midnight 6](https://user-images.githubusercontent.com/88982629/188680069-bf20b2d1-27f6-4b60-8037-e245c6b7f33c.jpg)
![The Corpse Danced at Midnight 7](https://user-images.githubusercontent.com/88982629/188680071-7bd7d86e-ae47-4df1-a1cf-1dd38708bcfd.jpg)
![The Corpse Danced at Midnight 8](https://user-images.githubusercontent.com/88982629/188680072-117f966a-3c6e-4e2b-b76c-82134636f32f.jpg)
![The Corpse Danced at Midnight 9](https://user-images.githubusercontent.com/88982629/188680073-cb32b58f-4ba3-4cf3-be73-d6c05878086e.jpg)
![The Corpse Danced at Midnight Poster](https://user-images.githubusercontent.com/88982629/188680074-d7a62443-3cd1-4c30-8008-0edbd1472d37.jpg)

**Comment by lynnandtonic** [comment]
Thank you! https://nestflix.fun/the-corpse-danced-at-midnight/
