### ISSUE TITLE
Add "It's Patsy"

### ISSUE THREAD

**Issue by logic** [lynnandtonic/nestflix.fun#57]
Please add as much of the following info as you can:

Title:It's Patsy

Type (film/tv show): tv show

Film or show in which it appears: Jessica Jones

Is the parent film/show streaming anywhere? Netflix

About when in the parent film/show does it appear? References show up in season 1, episode 7 has a shot of the poster from the show, episode 11 has a shot of the title card.

Actual footage of the film/show can be seen (yes/no)? no (unless you count the title card? I don't think any other actual "show" footage makes an appearance)

Random references:

* https://en.wikipedia.org/wiki/Patsy_Walker#In_other_media
* https://marvel-cinematic-universe-guide.fandom.com/wiki/It%27s_Patsy

**Comment by lynnandtonic** [comment]
Unfortunately since there isn’t any footage I won’t be adding this right now. Thank you for your suggestion!
