### ISSUE TITLE
Add Thunderbolt from "101 Dalmatians" (Screenshots added)

### ISSUE THREAD

**Issue by HarleysTwin** [lynnandtonic/nestflix.fun#573]
Please add as much of the following info as you can:

Title: Thunderbolt (though the title is never officially said.  The sequel short is called _The Further Adventures of Thunderbolt_, implying the title of this show might be along the lines of _The Adventures of Thunderbolt_.)

Type (film/tv show): TV show - classic western

Film or show in which it appears: 101 Dalmatians

Is the parent film/show streaming anywhere? Yes - Amazon Prime & Disney+

About when in the parent film/show does it appear? In the first 1/4, I believe.  

Actual footage of the film/show can be seen (yes/no)? yes - Here's a link: https://www.youtube.com/watch?v=1Cc3_yZesxo

Starring: Thunderbolt

Sponsor: Kanine Krunchies
![Thunderbolt 1](https://user-images.githubusercontent.com/88982629/189206927-dac7e2d7-4691-4d60-9f84-2883c4561e33.jpg)
![Thunderbolt 3](https://user-images.githubusercontent.com/88982629/189206933-516c52e8-eb3d-4d95-af65-6220bfd9ff49.jpg)
![Thunderbolt 5](https://user-images.githubusercontent.com/88982629/189206934-2ff00f0b-eeea-4267-adf5-8be0411e2fdd.jpg)
![Thunderbolt 6](https://user-images.githubusercontent.com/88982629/189206937-ad35e72a-618a-45d9-8b4b-a9db5727b1f8.jpg)
![Thunderbolt 8](https://user-images.githubusercontent.com/88982629/189206939-e5353f8d-558d-4bb5-98a6-306855a35130.jpg)
![Thunderbolt 9](https://user-images.githubusercontent.com/88982629/189206941-c2cb286e-6c57-4acb-9851-c21d7fe37f25.jpg)
![Thunderbolt 10](https://user-images.githubusercontent.com/88982629/189206943-e9c37565-d3db-4b7f-bfa7-cd3656e6f0b1.jpg)
![Thunderbolt 11](https://user-images.githubusercontent.com/88982629/189206946-c029869b-81d2-4f8c-a2c4-44d542c56a91.jpg)
![Thunderbolt 13](https://user-images.githubusercontent.com/88982629/189206948-8139ff1f-d650-44d6-ba00-d18bc5084596.jpg)
![Thunderbolt 14](https://user-images.githubusercontent.com/88982629/189206952-a5e29795-746e-4971-9850-445350933df1.jpg)
![Thunderbolt 15](https://user-images.githubusercontent.com/88982629/189206954-26ca7076-17b6-4a87-aa2b-c0f52d076266.jpg)
![Thunderbolt 16](https://user-images.githubusercontent.com/88982629/189206955-07992afe-7c29-440f-a0a8-e0d80a74952d.jpg)
![Thunderbolt 17](https://user-images.githubusercontent.com/88982629/189206956-8d15bb97-aa77-471d-94ae-159a22055572.jpg)
![Thunderbolt 18](https://user-images.githubusercontent.com/88982629/189206960-872e2c87-6685-4996-8b87-457f4a0800a2.jpg)
![Thunderbolt 20](https://user-images.githubusercontent.com/88982629/189206964-4234a714-718e-4366-ae1c-c6306189415f.jpg)
![Thunderbolt 21](https://user-images.githubusercontent.com/88982629/189206967-353f9d1e-6700-44a0-85b3-0752b628f8c0.jpg)
![Thunderbolt 22](https://user-images.githubusercontent.com/88982629/189206969-5202bd47-a578-40d1-a8d7-762c98aa7eaf.jpg)
![Thunderbolt 23](https://user-images.githubusercontent.com/88982629/189206970-2890442c-3d8e-4059-9008-4f1a02d6ea6b.jpg)
![Thunderbolt 24](https://user-images.githubusercontent.com/88982629/189206971-31f275b1-2b24-42f2-b349-227dc3e225e2.jpg)
![Thunderbolt 25](https://user-images.githubusercontent.com/88982629/189206973-0618ae26-0399-41ab-b7eb-7185934c5ebf.jpg)

**Comment by lynnandtonic** [comment]
Hey this one is already on the site! https://nestflix.fun/the-thunderbolt-adventure-hour/
