### ISSUE TITLE
Add Prince of Chaos from "The Callback Queen" (Screenshots and Poster Added)

### ISSUE THREAD

**Issue by HarleysTwin** [lynnandtonic/nestflix.fun#575]
Please add as much of the following info as you can:

Title: Prince of Chaos

Type (film/tv show): film - epic fantasy 

Film or show in which it appears: The Callback Queen

Is the parent film/show streaming anywhere? Yes - Amazon Prime

About when in the parent film/show does it appear? There's a screening at the end.

Actual footage of the film/show can be seen (yes/no)? Yes
Timestamp: 1:23:16 to end

Synopsis: Based on the _Prince of Chaos_ novels by legendary author Horatio King

Starring: Kate Loughlin as Princess Grace

Studio: BFI Film

Quote: Become the nightmare that haunts their dreams.  Become the death-bringer of prophesy.  Become the prince of chaos!

![Prince of Chaos 1](https://user-images.githubusercontent.com/88982629/189231191-6870f4ac-bbe1-4d9d-87c3-7539de6c9ce9.jpg)
![Prince of Chaos 2](https://user-images.githubusercontent.com/88982629/189231194-bc3eb022-bd4a-4912-92de-b03dd0f7c271.jpg)
![Prince of Chaos 3](https://user-images.githubusercontent.com/88982629/189231197-7f46c9a7-779d-4f3e-95f0-15609aee3582.jpg)
![Prince of Chaos 3 5](https://user-images.githubusercontent.com/88982629/189231195-f4505c28-83a9-475c-a88b-64331a4991cd.jpg)
![Prince of Chaos 4](https://user-images.githubusercontent.com/88982629/189231198-f54da077-66a1-4df2-99ae-4adbf40ea448.jpg)
![Prince of Chaos 5](https://user-images.githubusercontent.com/88982629/189231202-4a45c9c0-d254-4fc3-a16c-94f45a9430d8.jpg)
![Prince of Chaos 5 5](https://user-images.githubusercontent.com/88982629/189231199-cb0fd2ec-8997-4f74-a6dd-8325fb5d8b55.jpg)
![Prince of Chaos 7](https://user-images.githubusercontent.com/88982629/189231204-db33fdce-d6cd-4e70-ad82-c3c63e46ddaf.jpg)
![Prince of Chaos 8](https://user-images.githubusercontent.com/88982629/189231205-99169941-1fb9-41ea-838f-c349122016ce.jpg)
![Prince of Chaos Poster](https://user-images.githubusercontent.com/88982629/189231206-c41e1295-af6b-4a11-b810-94ad36d04b04.jpg)

**Comment by lynnandtonic** [comment]
THank you! https://nestflix.fun/prince-of-chaos/
