### ISSUE TITLE
Add Lucid Dreaming from "The Callback Queen" (Screenshots and Title Card Added)

### ISSUE THREAD

**Issue by HarleysTwin** [lynnandtonic/nestflix.fun#576]
Please add as much of the following info as you can:

Title: Lucid Dreaming

Type (film/tv show): Film - amateur romance

Film or show in which it appears: The Callback Queen

Is the parent film/show streaming anywhere? Yes: Amazon Prime

About when in the parent film/show does it appear? Near the end

Actual footage of the film/show can be seen (yes/no)? Yes
Timestamp: 1:16:35 - 1:17:27

Quote: I dream, I dream, I dream of you.

Starring: Kate Loughlin, Lucy Wilkinson

A Daithi Carroll Film
Studio: Deborah Whitton Film Academy

![Lucid Dreaming 1](https://user-images.githubusercontent.com/88982629/189235284-35389993-3a92-4cec-87fd-c8ff35a47aee.jpg)
![Lucid Dreaming 2](https://user-images.githubusercontent.com/88982629/189235285-392cdd4a-563e-4fc8-94c5-f422af5a45a6.jpg)
![Lucid Dreaming 3](https://user-images.githubusercontent.com/88982629/189235286-68b64f6c-e743-416b-9302-75d7472f49b7.jpg)
![Lucid Dreaming 4](https://user-images.githubusercontent.com/88982629/189235287-5b0d0173-a150-418c-9e2b-19c5f6f8620c.jpg)
![Lucid Dreaming 5](https://user-images.githubusercontent.com/88982629/189235289-8b6a23c9-6411-41f6-8d2e-7c706ca0b6ed.jpg)
![Lucid Dreaming 6](https://user-images.githubusercontent.com/88982629/189235292-9b3afe88-7286-4b21-9fe9-70437cac7351.jpg)
![Lucid Dreaming 7](https://user-images.githubusercontent.com/88982629/189235294-9b247e00-bb3c-4220-811d-4c288a66d38e.jpg)
![Lucid Dreaming Title](https://user-images.githubusercontent.com/88982629/189235295-64d4be9b-2dd3-48e1-812c-261d0a5b2872.jpg)

**Comment by lynnandtonic** [comment]
Thank you! https://nestflix.fun/lucid-dreaming/
