### ISSUE TITLE
Add Gina Tracker, FBI

### ISSUE THREAD

**Issue by ieatfood** [lynnandtonic/nestflix.fun#58]
Please add as much of the following info as you can:

Title: Gina Tracker, FBI

Type (film/tv show): Crime Show

Film or show in which it appears: Central Park, Season 2 Episode 1 ([Apple TV+ link](https://tv.apple.com/us/episode/central-dark/umc.cmc.3n9rqp0k7hw231v87h614ndii))

Is the parent film/show streaming anywhere? Apple TV 

About when in the parent film/show does it appear? 5:36, 8:00, 24:28

Actual footage of the film/show can be seen (yes/no)? yes

![gina tracker, fbi](https://user-images.githubusercontent.com/1124321/129180534-b989dc42-8e8b-4efa-b49e-c4838d1f2726.png)

**Comment by lynnandtonic** [comment]
Thank you!! https://nestflix.fun/gina-tracker-fbi/
