### ISSUE TITLE
Add Spy Wars from Spy X Family

### ISSUE THREAD

**Issue by Pacsonic** [lynnandtonic/nestflix.fun#594]
Please add as much of the following info as you can:

Title: Spy Wars

Type (film/tv show): TV Show

Film or show in which it appears: Spy X Family

Is the parent film/show streaming anywhere? Crunchyroll

About when in the parent film/show does it appear? Spy X Family Season 1 Episodes 1, 5, and 8

Actual footage of the film/show can be seen (yes/no)? Yes

Sample Images:
![Spy Wars](https://user-images.githubusercontent.com/76449480/200134703-5c43fae5-026a-430e-9d8c-d4e16e5d5ad9.png)
![Spy x Family - 08 - Large 09](https://user-images.githubusercontent.com/76449480/200134704-fb0ad1f1-2740-48e2-8017-0f7835141874.jpg)
![Spy Wars 2](https://user-images.githubusercontent.com/76449480/200134705-1c0163bd-8391-43a0-a3d4-8e2c4e23f727.png)
![Spy Wars 3](https://user-images.githubusercontent.com/76449480/200134707-f1164e14-bff9-4676-b162-3fe845e604c7.png)

**Comment by lynnandtonic** [comment]
Thank you @Pacsonic! https://nestflix.fun/spy-wars/
