### ISSUE TITLE
Add Super Robo Mecha Force Five from Teenage Mutant Ninja Turtles (2012)

### ISSUE THREAD

**Issue by Pacsonic** [lynnandtonic/nestflix.fun#595]
Please add as much of the following info as you can:

Title: Super Robo Mecha Force Five

Type (film/tv show): TV Show

Film or show in which it appears: Teenage Mutant Ninja Turtles (2012)

Is the parent film/show streaming anywhere? Paramount+ and PlutoTV

About when in the parent film/show does it appear? Season 2 Episodes 4, 6, 8, 10, 15, 18, 20, 21, and 24.

Actual footage of the film/show can be seen (yes/no)? Yes

**Comment by lynnandtonic** [comment]
Thank you!! https://nestflix.fun/super-robo-mecha-force-five/
