### ISSUE TITLE
Add The Goof Who Sat By the Door: The Thomas Washington Story from "Atlanta" (Screenshots and Title Screen added)

### ISSUE THREAD

**Issue by HarleysTwin** [lynnandtonic/nestflix.fun#598]
Please add as much of the following info as you can:

Title: The Goof Who Sat By the Door: The Thomas Washington Story

Type (film/tv show): film - documentary

Film or show in which it appears: Atlanta

Synopsis: A detailed account of the rise and fall of Thomas Washington, an unassuming Black animator from Atlanta, Georgia, who, in 1992, was accidentially appointed as CEO of The Walt Disney Company, and his quest to use the opportunity to create "the Blackest movie of all time:" _A Goofy Movie_.*

Is the parent film/show streaming anywhere? yes - Hulu

About when in the parent film/show does it appear? Ep. 4x08 - "The Goof Who Sat By the Door"  It consists of the entire episode.

Actual footage of the film/show can be seen (yes/no)? yes

Director: Devonte Jackson

Production studio: B.A.N. (Black American Network)

Documentary focus: Thomas Washington

Featuring: Evelyn Jackson (Thomas' mother), Phillip Washington (Thomas' cousin), Mark Dillard (S. C. A. D. professor), Jenna Wortham (journalist), Leonard Trussell (former Disney executive), Joel Zempel (former Disney Company board member), Gary Welch (former Disney animator), Frank Rolls (director), Anna Speilman (Thomas' wife), Maxwell Washington (Thomas' son), Chris Spinx (former Disney animator), Brian McKnight (singer), & Sinbad (comedian)

Fun Fact: The title of the documentary is based on _The Spook Who Sat By the Door_, the novel (and later film adaptation) by Sam Greenlee about the first Black CIA officer.

*_At the request of B.A.N.'s lawyers, we asknowledge that though the story you're about to see has been fact-checked to the best of our ability, certain details persented may not be endorsed by The Walt Disney Company._

![Goof_Title Screen](https://user-images.githubusercontent.com/88982629/201405218-5e384c4d-f27f-4b01-b0da-0fbd93ddfd64.jpg)
![Goof_1](https://user-images.githubusercontent.com/88982629/201381484-0a1c19ea-dc79-4e50-ae1a-b1a5f4ab7495.jpg)
![Goof_2](https://user-images.githubusercontent.com/88982629/201381486-5438410f-30c3-4391-8206-24c8696468f7.jpg)
![Goof_3](https://user-images.githubusercontent.com/88982629/201381487-c44a757f-28fe-4cf7-91a6-c274da1b8262.jpg)
![Goof_4](https://user-images.githubusercontent.com/88982629/201381490-37c2ddf8-7323-439d-812e-9262cf561f88.jpg)
![Goof_5](https://user-images.githubusercontent.com/88982629/201381493-4ae18cb4-2393-4634-a094-d2340cac8128.jpg)
![Goof_6](https://user-images.githubusercontent.com/88982629/201381495-f2faedbf-b39e-4610-a24e-33ac74f7b339.jpg)
![Goof_7](https://user-images.githubusercontent.com/88982629/201381498-5988e694-1f21-41fe-a68a-4d3f8470c4b8.jpg)
![Goof_9](https://user-images.githubusercontent.com/88982629/201381506-e7d2fb30-0757-4f84-99da-62c96fc032c8.jpg)
![Goof_10](https://user-images.githubusercontent.com/88982629/201381507-f6bfdea0-bc46-42b9-8418-e25c7521e341.jpg)
![Goof_12](https://user-images.githubusercontent.com/88982629/201381849-63dc6d31-5be1-4af4-9e72-73cc8938eea1.jpg)

**Comment by HarleysTwin** [comment]
![Goof_11](https://user-images.githubusercontent.com/88982629/201381843-0e2c4cf4-6331-49ad-b927-04a37798aa7b.jpg)
![Goof_12](https://user-images.githubusercontent.com/88982629/201381849-63dc6d31-5be1-4af4-9e72-73cc8938eea1.jpg)
![Goof_13](https://user-images.githubusercontent.com/88982629/201381850-2bcfd49a-6867-446a-a871-d42be0dddafd.jpg)
![Goof_14](https://user-images.githubusercontent.com/88982629/201381854-1677c20a-e4eb-4d37-8c58-85e0655a8489.jpg)
![Goof_15](https://user-images.githubusercontent.com/88982629/201381857-284f6714-7de4-48cf-9530-5a16fc75b9fd.jpg)
![Goof_16](https://user-images.githubusercontent.com/88982629/201381859-e45e2659-80de-4372-9665-20e951fdb741.jpg)
![Goof_17](https://user-images.githubusercontent.com/88982629/201381862-a24bed47-e1ef-40e2-a2fb-8073a06a313a.jpg)
![Goof_18](https://user-images.githubusercontent.com/88982629/201381868-de4357e5-4840-41cd-97e7-50efa27365bf.jpg)
![Goof_19](https://user-images.githubusercontent.com/88982629/201381870-3e6f1f42-d79a-4d9c-9be5-50722079cff6.jpg)
![Goof_20](https://user-images.githubusercontent.com/88982629/201381874-fe576c89-fb1f-4d60-a648-989971fd9791.jpg)

**Comment by HarleysTwin** [comment]
![Goof_21](https://user-images.githubusercontent.com/88982629/201382007-e9179482-bc3c-4876-aefd-78fbe463cf57.jpg)
![Goof_22](https://user-images.githubusercontent.com/88982629/201382012-f63bfe1d-8872-452f-8d36-d7471d62e900.jpg)
![Goof_23](https://user-images.githubusercontent.com/88982629/201382014-ff4a4121-d2d0-4bf8-bafe-8abb2664252d.jpg)
![Goof_24](https://user-images.githubusercontent.com/88982629/201382015-178e539b-439b-4a6e-8fe0-8418961a5748.jpg)
![Goof_25](https://user-images.githubusercontent.com/88982629/201382019-38114d61-a04e-4a55-8290-87736395ad59.jpg)
![Goof_26](https://user-images.githubusercontent.com/88982629/201382020-7976cee1-a59e-49a8-92e0-3763c5a25757.jpg)
![Goof_27](https://user-images.githubusercontent.com/88982629/201382022-a71f43b7-16e1-4af2-a9cb-946e77002124.jpg)
![Goof_28](https://user-images.githubusercontent.com/88982629/201382023-a54b33c6-5ae6-4db5-9ab9-29c1b6ed7b61.jpg)
![Goof_29](https://user-images.githubusercontent.com/88982629/201382027-58626c33-b031-4986-bf33-c3ff325e82c6.jpg)
![Goof_30](https://user-images.githubusercontent.com/88982629/201382028-ac2f2ef8-989a-4d98-9c9f-85482ffba993.jpg)

**Comment by HarleysTwin** [comment]
![Goof_31](https://user-images.githubusercontent.com/88982629/201382385-791df53a-c40a-41e1-954f-80d3bfc50ad3.jpg)
![Goof_32](https://user-images.githubusercontent.com/88982629/201382386-fbdfac16-b829-4415-a4b7-dd21620d429b.jpg)
![Goof_33](https://user-images.githubusercontent.com/88982629/201382390-fce59071-b9f6-4884-ad82-7887e72ef91c.jpg)
![Goof_34](https://user-images.githubusercontent.com/88982629/201382392-d2da4d64-2291-4973-a568-d98e1f1700bf.jpg)
![Goof_35](https://user-images.githubusercontent.com/88982629/201382395-eca1f390-4e43-4f00-856a-6c0796a53ecb.jpg)
![Goof_36](https://user-images.githubusercontent.com/88982629/201382397-cd0861bf-79a2-41d6-afcf-65aa4275b870.jpg)
![Goof_37](https://user-images.githubusercontent.com/88982629/201382400-dcdb3d95-c400-4fe8-bdf7-78f0b77328a1.jpg)
![Goof_38](https://user-images.githubusercontent.com/88982629/201382403-d62ef2d4-1f53-4373-80a5-47e7d7641fdc.jpg)
![Goof_39](https://user-images.githubusercontent.com/88982629/201382404-f6ba8ca5-68f3-43fb-ad0c-eff99fc8be52.jpg)
![Goof_40](https://user-images.githubusercontent.com/88982629/201382407-70e9206a-8e05-44fa-9dc4-10cf7f0b079e.jpg)

**Comment by HarleysTwin** [comment]
![Goof_41](https://user-images.githubusercontent.com/88982629/201384860-5e9cc1e7-bc57-4c0f-8e16-bc57b9bcd679.jpg)
![Goof_42](https://user-images.githubusercontent.com/88982629/201384864-2f2097a2-ad58-4a17-a8a5-f3e099cbca4e.jpg)
![Goof_43](https://user-images.githubusercontent.com/88982629/201384866-dcb83814-bf2b-4e5f-be44-7f0be2380735.jpg)
![Goof_44](https://user-images.githubusercontent.com/88982629/201384868-b17b00c6-ed2c-4655-9ce4-402a1fe7ec86.jpg)
![Goof_45](https://user-images.githubusercontent.com/88982629/201384869-9925e2c8-ce4f-4a88-b63f-ce5c4fdb9bf9.jpg)
![Goof_46](https://user-images.githubusercontent.com/88982629/201384870-c6ea2ef5-7d2a-4965-b68a-e9830d4aae75.jpg)
![Goof_47](https://user-images.githubusercontent.com/88982629/201384873-78acd4dc-d77c-4f1c-8887-c9d99fff9354.jpg)
![Goof_48](https://user-images.githubusercontent.com/88982629/201384876-bd687d56-7182-4901-a2a5-9aa82d4e00cf.jpg)
![Goof_49](https://user-images.githubusercontent.com/88982629/201384878-0eb82ca5-a1b0-4643-b38a-dc1f81da41fe.jpg)
![Goof_50](https://user-images.githubusercontent.com/88982629/201384881-3fb6d01a-3501-4520-b41b-6fd24bcf75c4.jpg)

**Comment by HarleysTwin** [comment]
![Goof_51](https://user-images.githubusercontent.com/88982629/201388435-b00035d8-b718-47f8-a062-cea2e177d151.jpg)
![Goof_52](https://user-images.githubusercontent.com/88982629/201388437-cd9706db-a8e7-473f-91f5-3cccbd469b49.jpg)
![Goof_53](https://user-images.githubusercontent.com/88982629/201388438-4381ebef-6cbe-4240-9218-96943a13155b.jpg)
![Goof_54](https://user-images.githubusercontent.com/88982629/201388442-7d3b3761-5a49-499d-b9fb-86ad9c28df04.jpg)
![Goof_55](https://user-images.githubusercontent.com/88982629/201388443-8eb0dd9b-0c75-44a8-a837-01294d7e392a.jpg)
![Goof_56](https://user-images.githubusercontent.com/88982629/201388444-1bdf4dd3-08eb-4841-8775-04bced0cd81a.jpg)
![Goof_57](https://user-images.githubusercontent.com/88982629/201388445-8f044e37-f531-49fe-8e56-4337fd252a59.jpg)
![Goof_58](https://user-images.githubusercontent.com/88982629/201388447-65236df3-2c25-4684-bfea-e83483e9e70a.jpg)
![Goof_59](https://user-images.githubusercontent.com/88982629/201388450-60b58eca-e0b9-4e31-a67c-f76ab9c4f261.jpg)
![Goof_60](https://user-images.githubusercontent.com/88982629/201388451-8328ebcf-3516-467d-8f10-508ec1cf2f29.jpg)

**Comment by HarleysTwin** [comment]
![Goof_62](https://user-images.githubusercontent.com/88982629/201405178-6e8f3f9e-2613-474c-9647-95faedb35e0e.jpg)
![Goof_63](https://user-images.githubusercontent.com/88982629/201405187-bd38d77b-0540-43ed-b5b8-8bb11cf23b79.jpg)
![Goof_64](https://user-images.githubusercontent.com/88982629/201405192-49c5d2c4-1bdd-4800-9d77-c17daac77e11.jpg)
![Goof_65](https://user-images.githubusercontent.com/88982629/201405195-793bb38c-7224-4c8f-a039-354d2c4dd932.jpg)
![Goof_66](https://user-images.githubusercontent.com/88982629/201405199-8facd9f1-f4be-4b8f-a0a0-15598b9012c5.jpg)
![Goof_67](https://user-images.githubusercontent.com/88982629/201405203-ae41274b-6de8-4d9c-ac4e-f8abdb403228.jpg)
![Goof_68](https://user-images.githubusercontent.com/88982629/201405207-47380cb1-4d9c-4f93-960f-83901d2a4960.jpg)
![Goof_69](https://user-images.githubusercontent.com/88982629/201405210-23ec805f-a4cf-4505-a3fb-c39a3c95f840.jpg)
![Goof_70](https://user-images.githubusercontent.com/88982629/201405213-63e336b2-cd28-43de-8059-853e03c40e4f.jpg)
![Goof_Title Screen](https://user-images.githubusercontent.com/88982629/201405218-5e384c4d-f27f-4b01-b0da-0fbd93ddfd64.jpg)

**Comment by HarleysTwin** [comment]
![Goof_64](https://user-images.githubusercontent.com/88982629/201436748-0bb8830f-6372-4478-a397-d04890ec71e7.jpg)
![Goof_65](https://user-images.githubusercontent.com/88982629/201436749-f4709346-9ca5-4ff9-ae1f-4fb739d4691f.jpg)
![Goof_66](https://user-images.githubusercontent.com/88982629/201436750-2306d1dd-83b5-45ec-a7c4-5ff558bbe230.jpg)
![Goof_Title Screen](https://user-images.githubusercontent.com/88982629/201405218-5e384c4d-f27f-4b01-b0da-0fbd93ddfd64.jpg)

(I avoided putting anything that had _A Goofy Movie_ for fear of the Disney lawyers.)

**Comment by lynnandtonic** [comment]
Thank you!!
