### ISSUE TITLE
Add the Rural Juror

### ISSUE THREAD

**Issue by jnolis** [lynnandtonic/nestflix.fun#60]
Title: the Rural Juror

Type (film/tv show): film

Film or show in which it appears: 30 rock

Is the parent film/show streaming anywhere? Netflix

About when in the parent film/show does it appear? Season 1 episode 10 and others 

Actual footage of the film/show can be seen (yes/no)? Yes

**Comment by lynnandtonic** [comment]
It’s on the site! https://nestflix.fun/the-rural-juror/
