### ISSUE TITLE
Add Step Right Up! (2022) from "Reboot" (Screenshots added)

### ISSUE THREAD

**Issue by HarleysTwin** [lynnandtonic/nestflix.fun#603]
Please add as much of the following info as you can:

Title: Step Right Up!

Type (film/tv show): TV show - family sitcom

Film or show in which it appears: Reboot

Is the parent film/show streaming anywhere? Yes - Hulu

About when in the parent film/show does it appear? Ep. 1x02 - "New Girl"

Actual footage of the film/show can be seen (yes/no)? Yes
Timestamp:
* 24:29 - 24:38
* 27:31 - 27:50
* 28:10 - 28:41

Cast: Reed Sterling, Bree Marie Jensen, Clay Barber, Zack Jackson, & Timberly Fox

Created by Hannah Gelman & Gordon Gelman
Studio: The Walt Disney Company (through Hulu)

![Step Right Up 1](https://user-images.githubusercontent.com/88982629/202837545-9604aab6-5465-43de-984a-a337d7a2908a.jpg)
![Step Right Up 2](https://user-images.githubusercontent.com/88982629/202837546-473e7949-a0cf-44cb-9877-f896536f6f59.jpg)
![Step Right Up 3](https://user-images.githubusercontent.com/88982629/202837548-8a146d0a-ef7a-4ade-ba7f-fe925ef2c789.jpg)
![Step Right Up 4](https://user-images.githubusercontent.com/88982629/202837549-43665264-7ed9-4db7-9f0a-8acb55d7d821.jpg)
![Step Right Up 5](https://user-images.githubusercontent.com/88982629/202837550-96e3613c-e7d0-4c0e-a868-a33120196da9.jpg)
![Step Right Up 6](https://user-images.githubusercontent.com/88982629/202837551-4d157894-739e-4f7a-85ee-1b70c9137da4.jpg)
![Step Right Up 7](https://user-images.githubusercontent.com/88982629/202837552-d69672bb-1e53-4191-81ad-8943f872dd5a.jpg)

**Comment by HarleysTwin** [comment]
About when in the parent film/show does it appear? Ep. 1x07 - "Baskets"

Actual footage of the film/show can be seen (yes/no)? Yes
Timestamp:
* 3:13 - 3:16 / 3:19 - 3:22 / 8:41 - 8:43 <- same scene 
* 8:53 - 8:55
* 9:04 - 9:07 / 9:22 - 9:24 / 22:02 - 22:07 / 23:06 - 23:09 <- same scene
* 10:28 - 10:33 (Has a mic boom in the shot.)

![Step Right Up 1](https://user-images.githubusercontent.com/88982629/202872204-8dd5b538-838c-4f86-bcf5-2c2940aa611b.jpg)
![Step Right Up 2 5](https://user-images.githubusercontent.com/88982629/202872205-0b683ef4-eb51-416c-aca8-8fe77710bf1d.jpg)
![Step Right Up 2](https://user-images.githubusercontent.com/88982629/202872206-1c07c87a-25f1-44ff-9892-c6c58d29efcb.jpg)
![Step Right Up 3](https://user-images.githubusercontent.com/88982629/202872207-524a6927-3c9f-4bb6-96cf-a2d629475dcf.jpg)

**Comment by HarleysTwin** [comment]
About when in the parent film/show does it appear? Ep. 1x08 - "Who's the Boss"

Actual footage of the film/show can be seen (yes/no)? Yes
Timestamp: 
* 23:42 - 23:44
![Step Right Up 1](https://user-images.githubusercontent.com/88982629/202872689-6a9091a1-afc1-408c-83a5-b1a51f7d1e6f.jpg)

**Comment by lynnandtonic** [comment]
Since this one doesn't ever get to broadcast I'm going to include it with the original series (https://github.com/lynnandtonic/nestflix.fun/issues/602). If Reboot gets a season 2 I might make a separate entry for it. 

Thank you!!
