### ISSUE TITLE
Add The Granite Family from Aqua Something You Know Whatever

### ISSUE THREAD

**Issue by ethanimation** [lynnandtonic/nestflix.fun#606]
Please add as much of the following info as you can:

Title: The Granite Family 

Type (film/tv show): tv show

Film or show in which it appears: Aqua Something You Know Whatever Season 9 Episode 5 The Granite Family

Is the parent film/show streaming anywhere? HBO Max

About when in the parent film/show does it appear? 00:01

Actual footage of the film/show can be seen (yes/no)? yes

**Comment by lynnandtonic** [comment]
Thank you! https://nestflix.fun/the-granite-family/
