### ISSUE TITLE
Add "Jacqueline"

### ISSUE THREAD

**Issue by vsnever** [lynnandtonic/nestflix.fun#61]
Title: Jacqueline

Type (film/tv show): film

Film or show in which it appears: Darling (1965), https://www.imdb.com/title/tt0059084/

Is the parent film/show streaming anywhere? The Criterion Channel, https://www.criterionchannel.com

About when in the parent film/show does it appear? ~37 min

Actual footage of the film/show can be seen (yes/no)? yes

![Jacqueline](https://user-images.githubusercontent.com/22627041/129201365-13dd5754-35a6-462c-9484-e521dffc18a2.png)

**Comment by lynnandtonic** [comment]
Thank you @vsnever! https://nestflix.fun/jacqueline/
