### ISSUE TITLE
Add Donut Factory Holiday from Regular Show

### ISSUE THREAD

**Issue by ethanimation** [lynnandtonic/nestflix.fun#617]
Please add as much of the following info as you can:

Title: Donut Factory Holiday 

Type (film/tv show): film

Film or show in which it appears: Regular Show - Season 7 - Episode 20 : Donut Factory Holiday

Is the parent film/show streaming anywhere? HBO Max

About when in the parent film/show does it appear? 00:10

Actual footage of the film/show can be seen (yes/no)? yes

**Comment by lynnandtonic** [comment]
Thank you! https://nestflix.fun/donut-factory-holiday/
