### ISSUE TITLE
Add La Saucisse ( The Sausage)

### ISSUE THREAD

**Issue by Sirlulu69** [lynnandtonic/nestflix.fun#62]
Title: La Saucisse ( The Sausage)

Type (film/tv show): Comedy

Film or show in which it appears: Césars Ceremony 2018

Is the parent film/show streaming anywhere? No

About when in the parent film/show does it appear? No

Actual footage of the film/show can be seen (yes/no)? Yes 

Trailer of La Saucisse : 

dailymotion.com/video/x6fjjkk

youtube.com/watch?v=zSuSnr7UWh0

**Comment by lynnandtonic** [comment]
So this was a sketch on an awards show? (I can’t access those videos because of region)

**Comment by lynnandtonic** [comment]
I’m not going to add this one right now! Sorry and thank you!
