### ISSUE TITLE
Add Father Ben from Father Ted (has screenshots)

### ISSUE THREAD

**Issue by danorak** [lynnandtonic/nestflix.fun#622]
Please add as much of the following info as you can:

Title: Father Ben

Type (film/tv show):
TV show
Film or show in which it appears: Father Ted

Is the parent film/show streaming anywhere?
All 4 (UK)
About when in the parent film/show does it appear? S2E6 (The Plague), at start of episode

Actual footage of the film/show can be seen (yes/no)? Yes

**Comment by HarleysTwin** [comment]
Type (film/tv show): TV show - sitcom

![Father Ben 1](https://user-images.githubusercontent.com/88982629/215554949-c3fcabbb-48bd-47ea-ab4f-129c759db248.jpg)
![Father Ben 2](https://user-images.githubusercontent.com/88982629/215554953-a4686fde-b8da-4d13-8495-91b861a76f7e.jpg)
![Father Ben 3](https://user-images.githubusercontent.com/88982629/215554957-b64cf2a1-c78c-4bbf-b202-8083f18a1659.jpg)
![Father Ben 4](https://user-images.githubusercontent.com/88982629/215554959-ba101c3e-c341-4144-836c-969dfca228ea.jpg)

**Comment by lynnandtonic** [comment]
Thank you! https://nestflix.fun/father-ben/
