### ISSUE TITLE
Add Jerry from "Seinfeld" (Screenshots and Title Screen Added)

### ISSUE THREAD

**Issue by HarleysTwin** [lynnandtonic/nestflix.fun#623]
Please add as much of the following info as you can:

Title: Jerry

Type (film/tv show): TV show - comedy sitcom

Film or show in which it appears: Seinfeld

Is the parent film/show streaming anywhere? Yes - Netflix

About when in the parent film/show does it appear? Eps. 4x22 "The Pilot, Part 1" & "The Pilot, Part 2" (both are combined on Netflix)

Actual footage of the film/show can be seen (yes/no)? Yes
Timestamps:
* 36:12 - 37:07
* 38:12 - 39:23

Show pitch: It's a show about nothing.

Starring: Jerry Seinfeld, Michael Barth, Sandi Robbins, & Tom Pepper

Created by Jerry Seinfeld & George Costanza
Production company: NBC

![Jerry Title](https://user-images.githubusercontent.com/88982629/215572930-0d0eb733-f592-490e-ad10-d361169bad93.jpg)
![Jerry 1](https://user-images.githubusercontent.com/88982629/215572939-7d5d508c-b412-44a6-abb6-53c979515661.jpg)
![Jerry 1 2](https://user-images.githubusercontent.com/88982629/215572934-2aae2dd3-6d4a-45bc-aa63-e829f1fc3fbb.jpg)
![Jerry 1 3](https://user-images.githubusercontent.com/88982629/215572937-5d3c6ca2-4324-4531-9625-c98c4b505844.jpg)
![Jerry 1 4](https://user-images.githubusercontent.com/88982629/215574480-3a9ee376-5d3a-4919-8a5b-62a5a139a1f2.jpg)
![Jerry 2](https://user-images.githubusercontent.com/88982629/215572943-2adedac8-211c-437e-891c-1ab8c3cc8ff8.jpg)
![Jerry 3](https://user-images.githubusercontent.com/88982629/215572944-dbde2cae-5e7b-4203-bb74-348e36753271.jpg)
![Jerry 4](https://user-images.githubusercontent.com/88982629/215572945-a308df98-28b0-4280-ac1e-a128ca68a18f.jpg)
![Jerry 5](https://user-images.githubusercontent.com/88982629/215572948-7e2effd9-ea77-4920-88ce-f7c284735468.jpg)
![Jerry 6](https://user-images.githubusercontent.com/88982629/215572949-5b91acd0-4c16-4f88-b5c2-d5ade8098333.jpg)
![Jerry 7](https://user-images.githubusercontent.com/88982629/215572952-7104cfe0-b0dd-484b-8bc8-c264e723fb22.jpg)
![Jerry 8](https://user-images.githubusercontent.com/88982629/215572954-703c46ed-8d34-4b0b-9aa2-9c5a322f14ae.jpg)
![Jerry 9](https://user-images.githubusercontent.com/88982629/215572956-170cd422-fe69-4c66-93be-a1e88235b772.jpg)
![Jerry 10](https://user-images.githubusercontent.com/88982629/215572958-b2032dd8-42fe-4df8-8112-dec6df1e35a2.jpg)
![Jerry 11](https://user-images.githubusercontent.com/88982629/215572961-4dc09700-2a96-40ae-87c7-a70742a9ac3d.jpg)
![Jerry 12](https://user-images.githubusercontent.com/88982629/215572963-ece5098e-02a2-4b53-ae51-e3d2156d8677.jpg)
![Jerry 13](https://user-images.githubusercontent.com/88982629/215572965-45b16f6b-ae55-4e8e-a93f-13a8e6388302.jpg)
![Jerry 14](https://user-images.githubusercontent.com/88982629/215572967-9daa63c8-09c6-4fbe-8492-89cec393baf9.jpg)
![Jerry 15](https://user-images.githubusercontent.com/88982629/215572968-0c5c187c-ee2a-4cd2-900a-7df0bbaaacab.jpg)
![Jerry 16](https://user-images.githubusercontent.com/88982629/215572972-b5b45045-29df-4fc8-af91-67dbfd4cabfd.jpg)
![Jerry 17](https://user-images.githubusercontent.com/88982629/215572975-48f97786-edd4-4e69-9f59-73f6c77df3b4.jpg)

**Comment by lynnandtonic** [comment]
Hey! So sorry but this one is already on the site: https://nestflix.fun/jerry/

Thanks again for your help with these issues. I'm going to be jumping in again soon.
