### ISSUE TITLE
Including "Collections?"

### ISSUE THREAD

**Issue by HarleysTwin** [lynnandtonic/nestflix.fun#636]
I was wondering how film collections apply to submissions.  I know that submissions where it's just the poster is not a valid submission, but I noticed there a couple of collections listed that are made entirely of posters:
- The Cliff Beasts Collection
- The George Simmons Collection
- The Jump Street Collection
- Krillerhunter Collection
- The Lucas Lee Collection
- The Peppy Miller Collection
- The Rick Dalton Collection
- The Best of Roger Rabbit
- The Tracy Morgan Collection

So, if there's a bunch of a character's film credits in a film/show, is it okay to submit it even if all they show are a bunch of posters one after the other?

**Comment by lynnandtonic** [comment]
Yeah the general criteria for collections are: 1.) there are 4+ movies/shows to include and 2.) there is high quality artwork for each of them. If the posters are too small or in the background I likely won't include them.

For ones like Lucas Lee and Cliffbeasts, I was able to find the posters on the web where people involved with the films shared them.

So yeah based on that criteria, feel free to submit collections! Thanks!
