### ISSUE TITLE
AVIF images not working in a few browsers

### ISSUE THREAD

**Issue by lynnandtonic** [lynnandtonic/nestflix.fun#65]
**Describe the bug**
AVIF files not showing up in Firefox Nightly because it has a setting that requires strict compliance. When that setting is turned off, images work fine [Reported from this tweet](https://twitter.com/jonrandy/status/1425809273397776386)

Also not working in:
> JPG images are loading fine in Edge (Chromium 92) but none of the AVIFs are loading on Chrome 93 on Windows or my Android phone (from Twitter)

**To Reproduce**
1. Go to Firefox Nightly / Chrome 93 on Windows
2. See no images
3. Turn off AVIF setting? Sorry not sure where this is
4. See images

**Expected behavior**
Images can be seen always

**Comment by lynnandtonic** [comment]
@sansthesis Someone reported the AVIF images not working in Firefox Nightly but I wasn’t super worried about it, but it looks like a couple other browsers are having the same issue. Would you mind taking a look?

**Comment by sansthesis** [comment]
What browsers?

**Comment by lynnandtonic** [comment]
@sansthesis Firefox Nightly and Chrome 93 on Windows; an Android phone too I guess I'm finding out browser

**Comment by lynnandtonic** [comment]
From twitter:
> Also Chrome 93 (I have Beta installed). I tried an AVIF test site - Edge 92 comes back as not AVIF compatible, but Android + Windows Chrome worked fine. I just tried Samsung Internet on a different phone and avifs worked but Chrome 93 still doesn't load them.

**Comment by dstaley** [comment]
I think it's [this bug](https://github.com/lovell/sharp/issues/2666) in sharp. Thankfully it seems like the AVIF issues are limited to non-stable versions of browsers currently, so hopefully sharp will have a new release prior to any of the affected browsers going stable.
