### ISSUE TITLE
Add Wally The Alligator from Hey Arnold

### ISSUE THREAD

**Issue by ethanimation** [lynnandtonic/nestflix.fun#654]
Please add as much of the following info as you can:

Title: Wally The Alligator

Type (film/tv show): tv show

Film or show in which it appears: Hey Arnold Season 2 Episode 6 – Ransom / Ms. Perfect

Is the parent film/show streaming anywhere? Paramount+

About when in the parent film/show does it appear? 00:47

Actual footage of the film/show can be seen (yes/no)? yes

**Comment by lynnandtonic** [comment]
Thank you!
