### ISSUE TITLE
Typo/misquote for Invitation to Love

### ISSUE THREAD

**Issue by thhpii** [lynnandtonic/nestflix.fun#655]
**Describe the bug**
The quote in Invitation to Love is incorrect. 

**To Reproduce**
1. Go to the listing for Invitation to Love (as seen in Twin Peaks) 
2. See the quote at the bottom listed as "Chetster, you little fruit loop. You’re done!"

**Expected behavior**
The correct quote is "Chester, you little Froot Loop, you’re done!" 

**Additional context**
The full quote is "Chester, you little Froot Loop, you’re done – done!" with an extra "done" at the end, but just the first "done" is probably enough to get people jazzed about this soap.

**Comment by lynnandtonic** [comment]
Thank you!
