### ISSUE TITLE
Add Joan is Awful from "Black Mirror" (Screenshots, Thumbnail, and Title Card added)

### ISSUE THREAD

**Issue by HarleysTwin** [lynnandtonic/nestflix.fun#661]
Please add as much of the following info as you can:

Title: Joan is Awful

Type (film/tv show): TV show - drama

Film or show in which it appears: Black Mirror

Is the parent film/show streaming anywhere? Yes - Netflix

About when in the parent film/show does it appear? Episode 6x01 - "Joan is Awful"

Actual footage of the film/show can be seen (yes/no)? Yes
Timestamps (interspersed with people watching it):
- 12:50 - 13:39
- 14:35 - 14:47
- 15:00 - 19:22
- 20:00 - 20:50
- 21:59 - 22:17
- 25:20 - 25:40
- 30:00 - 30:40
- 35:50 - 36:20

Starring: Salma Hayek, Himesh Patel, & Jaboukie Young-White, Camirin Farmer, Ben Marnes, & Cate Blanchett

Network: Streamberry (Streamberry CEO: Mona Javadi)

Number of seasons: 1

Note: This episode of _Black Mirror_ is crazy meta.  There's a version of _Joan is Awful_ within the show of _Joan is Awful_, and the entirity of the episode is revealed to be the real _Joan is Awful_ show.  I'm just putting the primary _Joan is Awful_ show here in order to not be too confusing.

![Joan Thumbnail](https://github.com/lynnandtonic/nestflix.fun/assets/88982629/16b534d8-b935-4595-be0f-f027ec715b3f)
![Joan Title](https://github.com/lynnandtonic/nestflix.fun/assets/88982629/436ef050-2006-4cee-85b4-d21b5e903ab5)
![Joan1](https://github.com/lynnandtonic/nestflix.fun/assets/88982629/bfa18db7-be73-4b0a-8006-31e6a7fd961d)
![Joan2](https://github.com/lynnandtonic/nestflix.fun/assets/88982629/47a33c95-9c4d-421c-bf2c-41e1be55068f)
![Joan3](https://github.com/lynnandtonic/nestflix.fun/assets/88982629/7b5dfe5f-9749-45b5-992e-cd26eed91388)
![Joan4](https://github.com/lynnandtonic/nestflix.fun/assets/88982629/c1e4c125-bf0e-4c60-a662-681eb93427ec)
![Joan5](https://github.com/lynnandtonic/nestflix.fun/assets/88982629/7370a8d2-6bb2-4314-81b2-56e6a52cc08e)
![Joan6](https://github.com/lynnandtonic/nestflix.fun/assets/88982629/0cfb1b8f-0151-4f2c-b0da-c145a3acad22)
![Joan7](https://github.com/lynnandtonic/nestflix.fun/assets/88982629/7d659805-d69b-4f69-b3e2-4905d4729fb6)
![Joan9](https://github.com/lynnandtonic/nestflix.fun/assets/88982629/2a08ea44-3506-4432-a0e1-dc9d374d0154)
![Joan11](https://github.com/lynnandtonic/nestflix.fun/assets/88982629/941e9cc9-4596-46bc-83dc-e62516fae17c)
![Joan12](https://github.com/lynnandtonic/nestflix.fun/assets/88982629/0786abd0-8f1d-4b31-a2f2-0ed718aa5497)
![Joan13](https://github.com/lynnandtonic/nestflix.fun/assets/88982629/f2cd77c7-87b1-49c8-bd34-89dd4ee649c1)
![Joan14](https://github.com/lynnandtonic/nestflix.fun/assets/88982629/03d45d0d-29d3-4f0c-bb42-79e8cebb0f92)
![Joan16](https://github.com/lynnandtonic/nestflix.fun/assets/88982629/d00bc43a-203a-4acb-85be-212f687f98ef)
![Joan17](https://github.com/lynnandtonic/nestflix.fun/assets/88982629/2538cb51-63c4-4134-ae1c-757a9163b1c2)
![Joan19](https://github.com/lynnandtonic/nestflix.fun/assets/88982629/e7ce6be7-e4fe-4570-9ea4-866444551e60)
![Joan20](https://github.com/lynnandtonic/nestflix.fun/assets/88982629/65003790-cfb6-4c7f-9220-c4cdb9014e5f)
![Joan21](https://github.com/lynnandtonic/nestflix.fun/assets/88982629/73551597-0385-460c-a3ff-17f470fd9ef4)
![Joan22](https://github.com/lynnandtonic/nestflix.fun/assets/88982629/8f60e7e8-82dd-480f-9bd2-9d0164089135)
![Joan23](https://github.com/lynnandtonic/nestflix.fun/assets/88982629/5bc36f97-0e3c-41b2-a786-220b42a92d80)
![Joan24](https://github.com/lynnandtonic/nestflix.fun/assets/88982629/b7d56eda-35a0-47cd-864b-582c1e571b03)
![Joan25](https://github.com/lynnandtonic/nestflix.fun/assets/88982629/fa3aa4c0-b381-402c-b509-8065ce99ba3a)
![Joan26](https://github.com/lynnandtonic/nestflix.fun/assets/88982629/1a6a9c61-bf9d-48ab-8a57-c19e04b31ae2)
![Joan27](https://github.com/lynnandtonic/nestflix.fun/assets/88982629/a7fd989c-4913-49c9-909b-2eaf2813be72)
![Joan28](https://github.com/lynnandtonic/nestflix.fun/assets/88982629/f88e8775-cb7b-4875-880c-c3d06c07d82e)

**Comment by lynnandtonic** [comment]
So I went back and forth on this one. I decided to use the Annie Murphy version of Joan is Awful since in "the real world" of the show, the Annie Murphy version is the television show they watch. Might do something with the Salma Hayek version, but not sure yet! 

Thank you! https://nestflix.fun/joan-is-awful/
