### ISSUE TITLE
Add Loch Henry: Truth Will Out from "Black Mirror" (Screenshots, Thumbnail, and Title Card added)

### ISSUE THREAD

**Issue by HarleysTwin** [lynnandtonic/nestflix.fun#662]
Please add as much of the following info as you can:

Title: Loch Henry: Truth Will Out 

Type (film/tv show): film - documentary (true crime)

Film or show in which it appears: Black Mirror

Is the parent film/show streaming anywhere? Yes - Netflix

About when in the parent film/show does it appear? Ep. 6x02 - "Loch Henry"

Actual footage of the film/show can be seen (yes/no)? Yes
Timestamp:
- 47:50 - 50:00

Production Companies: Historik Productions & Streamberry (from the award winning producers of _The Callow Years_)

Production: Davis McCardle, Kate Cezar, Clara Ryce, & Ted Bellingham

Streamberry Synopsis: A sleepy lochside town is rocked by a string of horrific murders.  Decades later, the former holiday destination has never recovered.

Tagline: They tried to tell a story.  But the truth they found was too close to home.

Awards: BAFTA Television Awards - Best Factual Series

In memory of Pia.

![Henry Thumbnail](https://github.com/lynnandtonic/nestflix.fun/assets/88982629/4ab80119-2083-4b5d-9f9c-398a46ed91d8)
![Henry Title](https://github.com/lynnandtonic/nestflix.fun/assets/88982629/f02b30d7-5bf5-4c8c-9fa7-8d7c96b12762)
![Henry1](https://github.com/lynnandtonic/nestflix.fun/assets/88982629/daffe606-1e85-4c37-a6c0-f73d2b1cec63)
![Henry2](https://github.com/lynnandtonic/nestflix.fun/assets/88982629/79fb1782-4e45-4cb3-b18b-d644150c3920)
![Henry3](https://github.com/lynnandtonic/nestflix.fun/assets/88982629/c8153838-047f-46d3-9ce7-915506322857)
![Henry4](https://github.com/lynnandtonic/nestflix.fun/assets/88982629/b5d20cc9-2671-469d-8675-350cf092ec9c)
![Henry6](https://github.com/lynnandtonic/nestflix.fun/assets/88982629/339a74ab-eb2d-4d26-86ae-b4e0fe6fd239)
![Henry7](https://github.com/lynnandtonic/nestflix.fun/assets/88982629/862e35b4-2692-4b64-8293-2be2ef174265)
![Henry8](https://github.com/lynnandtonic/nestflix.fun/assets/88982629/8623f196-e05f-46f0-8fa6-b11810e6a368)
![Henry10](https://github.com/lynnandtonic/nestflix.fun/assets/88982629/b30c4405-c872-4d01-8168-db8ffdb7c81d)
![Henry11](https://github.com/lynnandtonic/nestflix.fun/assets/88982629/1a98a981-07f7-4dd5-b9cf-ba7bf4a70533)
![Henry12](https://github.com/lynnandtonic/nestflix.fun/assets/88982629/2083b11f-e05f-4157-b34a-95ed2d40c622)
![Henry14](https://github.com/lynnandtonic/nestflix.fun/assets/88982629/679ac995-ee48-49f5-870c-4cb11e7e3e53)
![Henry15](https://github.com/lynnandtonic/nestflix.fun/assets/88982629/e3f6ae78-99da-43f6-877b-b706a2676480)
![Henry16](https://github.com/lynnandtonic/nestflix.fun/assets/88982629/72b811fc-0cc5-4066-a4d3-b2fcf5f3fbb1)
![Henry17](https://github.com/lynnandtonic/nestflix.fun/assets/88982629/66b0cccc-c825-40dd-85c7-b4b4bfe6f2fc)
![Henry18](https://github.com/lynnandtonic/nestflix.fun/assets/88982629/7dfbe2e2-108a-4582-8017-b6a5a9058a62)
![Henry21](https://github.com/lynnandtonic/nestflix.fun/assets/88982629/148a328b-5e63-47ff-8053-3cba31f60ac8)
![Henry22](https://github.com/lynnandtonic/nestflix.fun/assets/88982629/4dc6be30-5b45-46de-8842-5bf1105134a2)
![Henry23](https://github.com/lynnandtonic/nestflix.fun/assets/88982629/1ee914c3-bad7-4bb9-8091-f1e70044c68f)
![Henry24](https://github.com/lynnandtonic/nestflix.fun/assets/88982629/8c54f323-f974-4ddf-9c01-13275bdc014e)
![Henry25](https://github.com/lynnandtonic/nestflix.fun/assets/88982629/289fcea8-fbdb-4bce-bad2-a980c60cc2c2)
![Henry27](https://github.com/lynnandtonic/nestflix.fun/assets/88982629/1d0adf41-e9f0-4e95-ab9c-a67c1e5c72db)
![Henry28](https://github.com/lynnandtonic/nestflix.fun/assets/88982629/eff5eebb-6c43-48ec-a191-f5d602a01bdd)
![Henry30](https://github.com/lynnandtonic/nestflix.fun/assets/88982629/b3b162ef-91fc-450f-a620-1c4698d09952)
![Henry32](https://github.com/lynnandtonic/nestflix.fun/assets/88982629/082c85b6-50ae-4286-9499-a9276fdfeadd)
![Henry33](https://github.com/lynnandtonic/nestflix.fun/assets/88982629/381fcc21-0ae6-4e06-b1c5-1adc9f8ad51d)
![Henry34](https://github.com/lynnandtonic/nestflix.fun/assets/88982629/1c3cfc54-04ee-4c1b-8d0b-c2516e30d9c5)
![Henry35](https://github.com/lynnandtonic/nestflix.fun/assets/88982629/9e7e188a-abf9-40df-b011-7eb1e5fd4d9c)
![Henry36](https://github.com/lynnandtonic/nestflix.fun/assets/88982629/de451b54-c0cd-4fd4-bd35-275843d8fb16)
![Henry37](https://github.com/lynnandtonic/nestflix.fun/assets/88982629/aff7a7a3-da67-4a84-9ccf-71f8bdfdb73d)
![Henry38](https://github.com/lynnandtonic/nestflix.fun/assets/88982629/3645b73b-2fe7-4a13-a999-368008bc81d8)
![Henry39](https://github.com/lynnandtonic/nestflix.fun/assets/88982629/f37c8c6a-5f91-43da-9b8c-ea58ead4631f)
![Henry40](https://github.com/lynnandtonic/nestflix.fun/assets/88982629/fddd6f30-11ad-404e-917a-333dbc66287e)
![Henry41](https://github.com/lynnandtonic/nestflix.fun/assets/88982629/c99a1ab7-bed9-45b9-bba8-33f3e8b2b812)
![Henry42](https://github.com/lynnandtonic/nestflix.fun/assets/88982629/7d7d009b-6847-46b4-9f5c-9a163812c9a7)

**Comment by lynnandtonic** [comment]
Thank you! https://nestflix.fun/loch-henry/
