### ISSUE TITLE
The Goof Who Sat By the Door title formatting error

### ISSUE THREAD

**Issue by HarleysTwin** [lynnandtonic/nestflix.fun#667]
**Describe the bug**
On the profile for _The Goof Who Sat By The Door: The Thomas Washington Story_ the formatting of the title is all jumbled and smashed together so that the letters and spacing are either overlapping or too far apart.

**To Reproduce**
1. Click on the thumbnail.
2. Go to the profile.

**Screenshots**
![Goof](https://github.com/lynnandtonic/nestflix.fun/assets/88982629/a27748bb-3a03-45ac-bd1d-ba23ec3cc263)

**Comment by lynnandtonic** [comment]
Thank you! This should be fixed in a few minutes.
