### ISSUE TITLE
Add Ottoman Empire

### ISSUE THREAD

**Issue by moocow1452** [lynnandtonic/nestflix.fun#67]
Please add as much of the following info as you can:

Title: Ottoman Empire

Type (film/tv show): Reality

Film or show in which it appears: DuckTales (2017)

Is the parent film/show streaming anywhere? Disney+

About when in the parent film/show does it appear? Various Episodes (https://ducktales.fandom.com/wiki/Ottoman_Empire)

Actual footage of the film/show can be seen (yes/no)? Yes

**Comment by lynnandtonic** [comment]
Thanks, @moocow1452! It’s on the site now: https://nestflix.fun/ottoman-empire/
