### ISSUE TITLE
Add Flaming Globes of Sigmund

### ISSUE THREAD

**Issue by ericArbour** [lynnandtonic/nestflix.fun#68]
Please add as much of the following info as you can:

Title: Flaming Globes of Sigmund

Type (film/tv show): film

Film or show in which it appears: Seinfeld

Is the parent film/show streaming anywhere? No.

About when in the parent film/show does it appear? Season 2, Episode 8, The Heart Attack

Actual footage of the film/show can be seen (yes/no)? Yes.
![flaming](https://user-images.githubusercontent.com/8760181/129213569-a44f7ee9-74bb-4a4b-a616-15888a4dceb8.jpg)

**Comment by lynnandtonic** [comment]
Thank you, @ericArbour! It’s on the site now: https://nestflix.fun/flaming-globes-of-sigmund/
