### ISSUE TITLE
Add Girl Cop from "Only Murders in the Building" (Screenshots and Title Screen Added)

### ISSUE THREAD

**Issue by HarleysTwin** [lynnandtonic/nestflix.fun#683]
Please add as much of the following info as you can:

Title: Girl Cop

Type (film/tv show): TV show (comedy) - "Buddy Cop"

Film or show in which it appears: Only Murders in the Building

Is the parent film/show streaming anywhere? Yes - Hulu

About when in the parent film/show does it appear? Ep. 3x02 - "The Beat Goes On"

Actual footage of the film/show can be seen (yes/no)? Yes
Timestamps:
- 4:35 - 4:53
- 4:55 - 5:02

Cast: Ben Glenroy

Quotes: 
- "The drug bust is tonight.  What if I'm not back in time for homecoming?"
- "If my sergeant finds out, he'll take my badge _and_ my learner's permit."

(Sorry for the change in size for the pictures.  Magic eraser did it.)

![GirlCop Title](https://github.com/lynnandtonic/nestflix.fun/assets/88982629/089d4bee-cd38-49d4-8435-2e3f05bc46bc)
![GirlCop1](https://github.com/lynnandtonic/nestflix.fun/assets/88982629/4e6221c1-2a0b-4cd8-b310-6f19e04d896b)
![GirlCop2](https://github.com/lynnandtonic/nestflix.fun/assets/88982629/8877e0ce-8719-49b1-a4fd-535fad23cff6)
![GirlCop3](https://github.com/lynnandtonic/nestflix.fun/assets/88982629/4eaf162c-6b26-40fd-ab5a-0f0ba6c52d87)
![GirlCop4](https://github.com/lynnandtonic/nestflix.fun/assets/88982629/058a5cc1-aa6a-4121-98c5-09355df9edb3)
![GirlCop5](https://github.com/lynnandtonic/nestflix.fun/assets/88982629/da8e339f-1781-4e47-bbda-673f6a772f1d)
![GirlCop6](https://github.com/lynnandtonic/nestflix.fun/assets/88982629/eca36182-505a-49ee-aebd-c18643bf41f5)
![GIrlCop7](https://github.com/lynnandtonic/nestflix.fun/assets/88982629/fe10c583-5d0c-4ecf-a346-67de945584bb)
![GirlCop8](https://github.com/lynnandtonic/nestflix.fun/assets/88982629/182367cd-254d-4dd9-ac25-ea1d57db01b2)

**Comment by lynnandtonic** [comment]
Thank you! https://nestflix.fun/girl-cop/
