### ISSUE TITLE
Add Big Shot

### ISSUE THREAD

**Issue by jorgenah** [lynnandtonic/nestflix.fun#71]
Please add as much of the following info as you can:

Title: Big Shot

Type (film/tv show): Both

Film or show in which it appears: Cowboy Bebop

Is the parent film/show streaming anywhere?

About when in the parent film/show does it appear? Multiple times

Actual footage of the film/show can be seen (yes/no)? Yes

https://cowboybebop.fandom.com/wiki/Big_Shot#articleComments

**Comment by jorgenah** [comment]
Cowboy bebop is available on Adult Swim.
There are 7 episodes of Big Shot:
1. Abduhl Hakim (In session/episode 2 "Stray Dog Strut")
2. Fay Valentine (In session/episode 3 "Honky Tonk Women")
3. Grencia Mars Elijah Guo Eckener (In session/episode 12 "Jupiter Jazz (Part 1)")
4. Chessmaster Hex (In session/episode 14 "Bohemian Rhapsody")
5. Domino Walker (In session/episode 17 "Mushroom Samba")
6. Ted Bower (In session/episode 22 "Cowboy Funk")
7. Dr. Londes (In session/episode 23 "Brain Scratch")

**Comment by jorgenah** [comment]
<img width="968" alt="intro 2" src="https://user-images.githubusercontent.com/1213040/129627790-0410b2e3-f955-436a-8b24-24dd6e8423da.png">
<img width="970" alt="intro 1" src="https://user-images.githubusercontent.com/1213040/129627806-d4460b53-0886-4934-9d44-ca065c62a97f.png">
<img width="970" alt="1-Session2-1" src="https://user-images.githubusercontent.com/1213040/129627900-cf61756c-f843-4126-aa70-77b8c4d0d6c5.png">
<img width="971" alt="1-session2-2" src="https://user-images.githubusercontent.com/1213040/129627912-e25916f8-5e2d-4b07-864c-ecb238fb5376.png">
<img width="1068" alt="2-session3-1" src="https://user-images.githubusercontent.com/1213040/129627980-bfe43c6c-933f-470f-a9c5-48e657f74c3b.png">
<img width="1066" alt="2-session3-2" src="https://user-images.githubusercontent.com/1213040/129627993-9a2365c4-7b35-4558-a2f2-2d1ff6078b2f.png">
<img width="1071" alt="3-session12-1" src="https://user-images.githubusercontent.com/1213040/129628074-863903b6-018c-4287-931d-550ef51e08cc.png">
<img width="1068" alt="3-session12-2" src="https://user-images.githubusercontent.com/1213040/129628086-900208b3-c0dc-4699-abdd-bcbf3514a341.png">
<img width="1067" alt="3-session12-3" src="https://user-images.githubusercontent.com/1213040/129628091-4dde5942-6c72-44d5-8ebc-db795219c50f.png">
<img width="1065" alt="4-session14-1" src="https://user-images.githubusercontent.com/1213040/129628166-ea107c0e-ec3b-4804-9eac-1f4f7fd9797d.png">
<img width="1067" alt="4-session14-2" src="https://user-images.githubusercontent.com/1213040/129628179-561d14ed-249c-4de9-a536-111cda4d6784.png">
<img width="1065" alt="4-session14-3" src="https://user-images.githubusercontent.com/1213040/129628184-8d615cb6-1f95-4adc-8efe-e851ebb9e922.png">
<img width="1074" alt="5-session17-1" src="https://user-images.githubusercontent.com/1213040/129628213-dda7bbb4-851c-4602-a4e4-47c63e0e3220.png">
<img width="1066" alt="6-session22-1" src="https://user-images.githubusercontent.com/1213040/129628287-c5f59f7c-263d-4fd8-9f70-eb37922a22d9.png">
<img width="1065" alt="6-session22-2" src="https://user-images.githubusercontent.com/1213040/129628297-6be199a3-2f4e-4cb5-876c-8673cc2324c3.png">
<img width="1067" alt="6-session22-3" src="https://user-images.githubusercontent.com/1213040/129628301-64c5f330-58b8-4ac6-9bda-9d5488700376.png">
<img width="1072" alt="7-session23-1" src="https://user-images.githubusercontent.com/1213040/129628366-dc8f3009-7429-4dc2-a13a-390ee8c85a44.png">
<img width="1065" alt="7-session23-2" src="https://user-images.githubusercontent.com/1213040/129628387-f7057eed-2f17-470d-850c-9877cf82b3f2.png">
<img width="1068" alt="7-session23-3" src="https://user-images.githubusercontent.com/1213040/129628455-9c19038f-05fc-44dd-bdd9-789c5198d171.png">

**Comment by lynnandtonic** [comment]
Thank you SO much, @jorgenah! Appreciate you including so many good images. 🙌 https://nestflix.fun/big-shot/
