### ISSUE TITLE
Add "The Scooby-Doo Murder Files"

### ISSUE THREAD

**Issue by captainnintendo** [lynnandtonic/nestflix.fun#72]
Please add as much of the following info as you can:

Title: The Scooby-Doo Murder Files

Type (film/tv show): TV show

Film or show in which it appears: Family Guy (1999-2003, 2005-)

Is the parent film/show streaming anywhere? Hulu/Disney+ Star (outside the US)

About when in the parent film/show does it appear? Season 1, Episode 2; "I Never Met the Dead Man"

Actual footage of the film/show can be seen (yes/no)? Yes

**Comment by lynnandtonic** [comment]
Hey, @captainnintendo! This one _technically_ does qualify, but the characters are the same and it feels basically like an episode of Scooby Doo, so I don’t think I’m going to add it right now. Thanks so much for your suggestion!
