### ISSUE TITLE
Add "The Sickening" from Master of None

### ISSUE THREAD

**Issue by tshreve24** [lynnandtonic/nestflix.fun#73]
Title: "The Sickening" (2015)

Type (film/tv show): disaster film

Film or show in which it appears: Master of None (2015-2021)

Is the parent film/show streaming anywhere? Netflix

About when in the parent film/show does it appear? Season 1

Actual footage of the film/show can be seen (yes/no)? Yes

"The Sickening, it's happening! Holy fucking shit!"

Cast: Colin Salmon

**Comment by lynnandtonic** [comment]
@tshreve24 Hey! I went through a few episodes and I couldn’t find any footage of the film. The closest seems to be in S1E5 where they film a scene in front of a green screen. Do you know of any other clips they might show?

**Comment by lynnandtonic** [comment]
Going to close this since I don't think there's useable footage. Thank you!!
