### ISSUE TITLE
SCTV

### ISSUE THREAD

**Issue by adamjrice** [lynnandtonic/nestflix.fun#75]
Please add as much of the following info as you can:

Title: [various]

SCTV is a special case because the show's framing conceit was that it was shows from the Melonville TV station, many of which are detailed here: http://www.sctvguide.ca/programs/index.htm

Type (film/tv show): tv show

There were also SCTV "movies" that were complete episodes: The Last Polka, 3-D Steak from the Heart, etc.

Film or show in which it appears: SCTV

Is the parent film/show streaming anywhere? Netflix, Disney+

About when in the parent film/show does it appear? Throughout

Actual footage of the film/show can be seen (yes/no)? Yes

**Comment by dletter** [comment]
This is probably an "edge case", as much as SCTV shows would be amusing to add, Nestflix explicitly does not do fake show from "sketch" shows like SNL or Mad TV, and SCTV probably falls into that category.

**Comment by lynnandtonic** [comment]
Ok I thought about this one a whole bunch, but I don't think I'm going to add these right now. I might revisit sketch-style shows later on. Thank you!
