### ISSUE TITLE
Add The Mooby Fun-Time Hour

### ISSUE THREAD

**Issue by ivkowalenko** [lynnandtonic/nestflix.fun#76]
Please add as much of the following info as you can:

Title: "The Mooby Fun-Time Hour"

Type (film/tv show): TV Show

Film or show in which it appears: _Dogma_ (1999)

Is the parent film/show streaming anywhere? No, and here's why: https://twitter.com/ThatKevinSmith/status/1167561410315837440

About when in the parent film/show does it appear? 47m53s

Actual footage of the film/show can be seen (yes/no)? No

![vlcsnap-2021-08-12-10h48m32s817](https://user-images.githubusercontent.com/687277/129227687-26deb57e-ce2f-4714-86ac-9d34e88f3414.png)

**Comment by lynnandtonic** [comment]
Hi! Unfortunately right now I’m only adding shows/films with footage that can be seen onscreen. Thank you! (I do love Dogma so much)
