### ISSUE TITLE
Add A Very Mooby Christmas

### ISSUE THREAD

**Issue by ivkowalenko** [lynnandtonic/nestflix.fun#77]
Please add as much of the following info as you can:

Title: _A Very Mooby Christmas_

Type (film/tv show): Film

Film or show in which it appears: _Dogma_ (1999)

Is the parent film/show streaming anywhere? No, [and here's why](https://twitter.com/ThatKevinSmith/status/1167561410315837440)

About when in the parent film/show does it appear? 48m03s

Actual footage of the film/show can be seen (yes/no)? No

![Dogma - A Very Mooby Christmas](https://user-images.githubusercontent.com/687277/129228221-db313cda-0850-4330-8628-ad0d644415c1.png)

**Comment by lynnandtonic** [comment]
Same thing here, unfortunately. No footage! 😢
