### ISSUE TITLE
Add Tiger Fist

### ISSUE THREAD

**Issue by ivkowalenko** [lynnandtonic/nestflix.fun#79]
Please add as much of the following info as you can:

Title: Tiger Fist

Type (film/tv show): TV Show

Film or show in which it appears: _Gravity Falls_

Is the parent film/show streaming anywhere? [Disney+](https://www.disneyplus.com/series/gravity-falls/HZxayxzMJqed)

About when in the parent film/show does it appear? Season 1, Episode 4, ~15sec

Actual footage of the film/show can be seen (yes/no)? Yes

![Gravity Falls - Tiger Fist Title Card](https://user-images.githubusercontent.com/687277/129230531-2e696a94-2eb1-40e2-86f7-7987c4ea8f89.png)
![Gravity Falls - Tiger Fist 01](https://user-images.githubusercontent.com/687277/129230552-d63f81fd-17f2-46ce-aaf5-e6b3605c31d0.png)
![Gravity Falls - Tiger Fist 02](https://user-images.githubusercontent.com/687277/129230565-7273c564-a11b-4a0d-adcb-43123621c18f.png)
![Gravity Falls - Tiger Fist 03](https://user-images.githubusercontent.com/687277/129230583-094e46b1-3c26-4607-80f0-44b078325b08.png)
![Gravity Falls - Tiger Fist 04](https://user-images.githubusercontent.com/687277/129230599-99981444-ce90-42a4-89d4-d8a90297154d.png)
![Gravity Falls - Tiger Fist Will Return After These Messages](https://user-images.githubusercontent.com/687277/129230622-64c1c982-3565-44fc-9abd-e048d593da0d.png)

**Comment by lynnandtonic** [comment]
It’s live! https://nestflix.fun/tiger-fist/

Thank you!
