### ISSUE TITLE
Clickable "As seen in" titles

### ISSUE THREAD

**Issue by BoFiS** [lynnandtonic/nestflix.fun#80]
On each show's page, where it lists the parent show it was from, that show name should be clickable, and initiate a search for that show with all the other nested shows from that show.

**Comment by waxpancake** [comment]
I'd love to see clickable tags too!

**Comment by lynnandtonic** [comment]
@BoFiS Great idea! This should be working now for the parent show/movie. 

@waxpancake I also love your idea! That one requires a bit of moving things around, so I made a separate issue: https://github.com/lynnandtonic/nestflix.fun/issues/115
