### ISSUE TITLE
Add Mister Parker's Cul-De-Sac

### ISSUE THREAD

**Issue by ivkowalenko** [lynnandtonic/nestflix.fun#81]
Please add as much of the following info as you can:

Title: Mister Parker's Cul-De-Sac

Type (film/tv show): TV Show

Film or show in which it appears: _Legends of Tomorrow_, Season 5, Episode 6 "Mister Parker's Cul-De-Sac"

Is the parent film/show streaming anywhere? [Netflix](https://www.netflix.com/search?q=Legends%20of%20Tomorrow&jbv=80066080), [The CW](https://www.cwtv.com/shows/dcs-legends-of-tomorrow/) (most recent season only)

About when in the parent film/show does it appear? Throughout

Actual footage of the film/show can be seen (yes/no)? Yes, there were also shorts from the show that had been released on YouTube at one point.

**Comment by lynnandtonic** [comment]
It’s live! https://nestflix.fun/mister-parkers-cul-de-sac/

Thank you!!
