### ISSUE TITLE
Add Detective Beebo

### ISSUE THREAD

**Issue by ivkowalenko** [lynnandtonic/nestflix.fun#82]
Please add as much of the following info as you can:

Title: Detective Beebo

Type (film/tv show): Film

Film or show in which it appears: _Legends of Tomorrow_, Season 5, Episode 1 "Meet The Legends"

Is the parent film/show streaming anywhere? [Netflix](https://www.netflix.com/search?q=Legends%20of%20Tomorrow&jbv=80066080)

About when in the parent film/show does it appear? Offhand, I'm not 100% positive

Actual footage of the film/show can be seen (yes/no)? No, only mentioned in a news ticker.

**Comment by lynnandtonic** [comment]
Thank you so much for submitting! But right now I’m only adding titles that show actual footage.
