### ISSUE TITLE
Add American Duos

### ISSUE THREAD

**Issue by scottkellum** [lynnandtonic/nestflix.fun#83]
Please add as much of the following info as you can:

Title: American Duos

Type (film/tv show): TV Show

Film or show in which it appears: Psych

Is the parent film/show streaming anywhere? Amazon Prime/Peacock

About when in the parent film/show does it appear?: Season 2, Episode 1

Actual footage of the film/show can be seen (yes/no)? YES

Note: Tim Curry is one of the show’s hosts and is incredible
More info here: https://psychusa.fandom.com/wiki/American_Duos

**Comment by lynnandtonic** [comment]
It's up! https://nestflix.fun/american-duos/

Thank you!!
