### ISSUE TITLE
Add Capital Beat

### ISSUE THREAD

**Issue by ivkowalenko** [lynnandtonic/nestflix.fun#84]
Please add as much of the following info as you can:

Title: Capital Beat

Type (film/tv show): TV Show

Film or show in which it appears: _The West Wing_

* Season 1, Episode 1 "Pilot"
* Season 2, Episode 4 "In This White House"
* Season 2, Episode 13 "Bartlet's Third State of the Union"
* Season 3, Episode 9 "Bartlet for America"

Is the parent film/show streaming anywhere? HBO Max

About when in the parent film/show does it appear? I don't have HBO Max, so I can't break this one down.

Actual footage of the film/show can be seen (yes/no)? Yes, both on TV screens in the show, and from a behind-the-scenes perspective as the show is being recorded.

**Comment by lynnandtonic** [comment]
Thank you, @ivkowalenko! https://nestflix.fun/capital-beat/
