### ISSUE TITLE
Add [The Purple Rose of Cairo]

### ISSUE THREAD

**Issue by vargasvargas** [lynnandtonic/nestflix.fun#85]
Please add as much of the following info as you can:

Title: The Purple Rose of Cairo

Type (film/tv show): Film

Film or show in which it appears: The Purple Rose of Cairo

Is the parent film/show streaming anywhere?

About when in the parent film/show does it appear?

Actual footage of the film/show can be seen (yes/no)? yes

**Comment by lynnandtonic** [comment]
Already on the site! https://nestflix.fun/the-purple-rose-of-cairo/
