### ISSUE TITLE
Add YouTube video

### ISSUE THREAD

**Issue by mmoser-markl** [lynnandtonic/nestflix.fun#86]
It will be great to show a video on YouTube of the show/film parody. It's almost impossible not to find it there. If not then show the thumbnail instead.

**Comment by marcoskirsch** [comment]
I’d assume that you could add the video ID and a start second in order to show the clip.

**Comment by lynnandtonic** [comment]
Hey @mmoser-markl!

I totally agree it would be awesome, but I don’t currently want to link to or embed content that’s maintained by other people. Sometimes YouTube videos get removed (especially with copyrighted material like this) and I’d rather avoid having to keep tabs on that. Thank you for your suggestion though! I really appreciate it.
