### ISSUE TITLE
Add Joelho-Alto Prejuizo Moral

### ISSUE THREAD

**Issue by xmichelo** [lynnandtonic/nestflix.fun#90]
Please add as much of the following info as you can:

Title: Joelho-Alto Prejuizo Moral (Portugese Gremlins)

Type (film/tv show): film

Film or show in which it appears: Community

Is the parent film/show streaming anywhere? Prime

About when in the parent film/show does it appear?  S06e02 - 24:48

Actual footage of the film/show can be seen (yes/no)? yes

**Comment by lynnandtonic** [comment]
It’s live! https://nestflix.fun/joelho-alto-prejuizo-moral/

Thank you!
