### ISSUE TITLE
Inglourious Basterds- "Nation's Pride (Stolz der Nation)"

### ISSUE THREAD

**Issue by seth-johnson-sp** [lynnandtonic/nestflix.fun#92]
Please add as much of the following info as you can:

Title: Nation's Pride (Stolz der Nation)

Type (film/tv show): Action Film

Film or show in which it appears: Inglourious Basterds

About when in the parent film/show does it appear?

Actual footage of the film/show can be seen (yes/no)? Yes

This is the complete film Nation's Pride: https://www.youtube.com/watch?v=p2VUGfrZyck

Is the parent film/show streaming anywhere? Prime, AppleTV, etc.
![Nation'sPrideScne](https://user-images.githubusercontent.com/6307214/129249156-61f6aeee-f19b-48c1-9cbb-30a17d1397d6.png)
![Nation's Pride Title](https://user-images.githubusercontent.com/6307214/129249158-a8882882-5bf6-4d6b-8e08-f0f7000dd859.png)

**Comment by waxpancake** [comment]
It's already in there https://nestflix.fun/stolz-der-nation/
