### ISSUE TITLE
Add O Brother Where Art Thou

### ISSUE THREAD

**Issue by dethtron5000** [lynnandtonic/nestflix.fun#93]
Please add as much of the following info as you can: 

Title: O Brother Where Art Thou (same as the Coen brothers movie)

Type (film/tv show):Film

Film or show in which it appears: Sullivan's Travels (1941)

Is the parent film/show streaming anywhere? It is streaming on the Criterion Channel.  A clip with the footage is here: https://www.tcm.com/video/273124/sullivans-travels-1942-o-brother-where-art-thou

About when in the parent film/show does it appear? At the very beginning of the movie.  

Actual footage of the film/show can be seen (yes/no)? Yes

**Comment by lynnandtonic** [comment]
Sorry is the clip you linked the footage? Does the film show them actually making O Brother Where Art Thou (or the final movie)?

**Comment by lynnandtonic** [comment]
I watched this and the film at the beginning does’t seem to be titled and it isn’t O Brother Where Art Thou. So closing this one for now. Thanks!
