### ISSUE TITLE
Add fictional movies from Seinfeld

### ISSUE THREAD

**Issue by mattl** [lynnandtonic/nestflix.fun#94]
Please add as much of the following info as you can:

https://seinfeld.fandom.com/wiki/List_of_Seinfeld_fictional_films

**Comment by lynnandtonic** [comment]
I don’t believe they ever show us any footage of these movies. We hear them in dialogue and see movie posters, but that’s it. 

If you know of any scenes they show, let me know! Otherwise, going to close this. Thank you!

**Comment by lynnandtonic** [comment]
Hey @mattl, just following up that it looks like there is footage for “Flaming Globes of Sigmund” and the “Jerry” tv show. So I have those on my list to add. Thanks again!
