### ISSUE TITLE
Add Forrest Gump 2: Gumped Again

### ISSUE THREAD

**Issue by OverlappingElvis** [lynnandtonic/nestflix.fun#95]
Please add as much of the following info as you can:

Title: Forrest Gump 2: Gumped Again

Type (film/tv show): Film

Film or show in which it appears: Cecil B. Demented (2000)

Is the parent film/show streaming anywhere? Tubi

About when in the parent film/show does it appear? 01:02:26

Actual footage of the film/show can be seen (yes/no)? Yes

**Comment by lynnandtonic** [comment]
It’s up! https://nestflix.fun/forrest-gump-2-gump-again/

Thank you!
