### ISSUE TITLE
"Choozy Doozy" from Hot Tub Time Machine 2

### ISSUE THREAD

**Issue by seth-johnson-sp** [lynnandtonic/nestflix.fun#96]
Please add as much of the following info as you can:

Title: Choozy Doozy Celebrity Edition

Type (film/tv show): Game Show

"
With Choozy Doozy, when you Chooze It, you Dooze It.
"

Film or show in which it appears: Hot Tub Time Machine 2

Is the parent film/show streaming anywhere? Prime, YouTube, AppleTV, etc.

About when in the parent film/show does it appear? Midway through

Actual footage of the film/show can be seen (yes/no)? yes
https://www.youtube.com/watch?v=0hjsG01_2aw

![Screen Shot 2021-08-12 at 3 19 49 PM](https://user-images.githubusercontent.com/6307214/129264723-941792b5-3589-4cb3-b8d0-a6448560fcd2.png)
![Screen Shot 2021-08-12 at 3 19 15 PM](https://user-images.githubusercontent.com/6307214/129264728-84204630-67e9-4463-8f5d-cab27812b098.png)
![Screen Shot 2021-08-12 at 3 18 48 PM](https://user-images.githubusercontent.com/6307214/129264731-a1d0f4c5-65c1-4c35-837b-1a03615a5646.png)
![Screen Shot 2021-08-12 at 3 18 11 PM](https://user-images.githubusercontent.com/6307214/129264732-b8ddbc44-a934-4470-9a01-e0a79f9ff8a5.png)
![Screen Shot 2021-08-12 at 3 17 49 PM](https://user-images.githubusercontent.com/6307214/129264735-bfbae982-012e-4c5d-b3aa-d6bf8364da7c.png)
![Screen Shot 2021-08-12 at 3 17 30 PM](https://user-images.githubusercontent.com/6307214/129264737-66ed4ca7-37cb-4146-a372-3cc4ce8c77a7.png)
![Screen Shot 2021-08-12 at 3 17 11 PM](https://user-images.githubusercontent.com/6307214/129264739-7a611543-8664-463b-8e87-1da83644f1b8.png)
![Screen Shot 2021-08-12 at 3 16 28 PM](https://user-images.githubusercontent.com/6307214/129264742-b05e07bb-a4d1-40d7-be3f-144c16121a22.png)
![Screen Shot 2021-08-12 at 3 16 13 PM](https://user-images.githubusercontent.com/6307214/129264745-55a78369-63de-4ef5-817e-ae2293013890.png)
![Screen Shot 2021-08-12 at 3 14 56 PM](https://user-images.githubusercontent.com/6307214/129264747-91ac94ab-2b47-4e16-b448-36699b60a0d1.png)
![Screen Shot 2021-08-12 at 3 13 39 PM](https://user-images.githubusercontent.com/6307214/129264749-201c5939-5e6e-4d29-9552-74d047670d9b.png)

**Comment by lynnandtonic** [comment]
It’s up! https://nestflix.fun/choozy-doozy-celebrity/

Thank you!
