### ISSUE TITLE
Bannigan from Lookwell

### ISSUE THREAD

**Issue by johndavis23** [lynnandtonic/nestflix.fun#97]
Please add as much of the following info as you can:

Title: Bannigan

Type (film/tv show): TV Show

Film or show in which it appears: Lookwell 

Is the parent film/show streaming anywhere? https://www.youtube.com/watch?v=dBQ3HbB0c8Y

About when in the parent film/show does it appear? ~ 5 mins; other times

Actual footage of the film/show can be seen (yes/no)? yes

**Comment by lynnandtonic** [comment]
Thank you! https://nestflix.fun/bannigan/
